CREATE DATABASE if not exists apsmgm DEFAULT CHARACTER SET utf8mb4;

use apsmgm;

create table if not exists TBL_AUTH_ASSIGNMENT
(
  ITEM_NAME  VARCHAR(64) not null,
  USER_ID    INT(10) not null,
  CREATED_AT INT(22),
  primary key (USER_ID, ITEM_NAME)
);

create table if not exists TBL_AUTH_ITEM
(
  NAME        VARCHAR(64) not null primary key,
  TYPE        INT       not null,
  DESCRIPTION VARCHAR(200),
  RULE_NAME   VARCHAR(64),
  ITEM_DATA   VARCHAR(500),
  CREATED_AT  INT(10),
  UPDATED_AT  INT(10),
  ITEM_CODE   VARCHAR(10),
  PARENT_ITEM VARCHAR(64),
  CREATE_USER INT
);

create table if not exists TBL_ROLE (
	ROLE_ID bigint(20) unsigned auto_increment primary key,
	ROLE_NAME varchar(32) unique not null,
	CREATED_AT datetime default now(),
	UPDATED_AT datetime default now()
);

create table if not exists TBL_AUTH_ITEM_CHILD
(
  PARENT VARCHAR(64) not null,
  CHILD  VARCHAR(64) not null,
  primary key (PARENT, CHILD)
);

create table if not exists TBL_MENU
(
  ID         bigint(20) auto_increment not null primary key,
  NAME       VARCHAR(128),
  PARENT     int(10),
  MENU_ROUTE VARCHAR(256),
  MENU_ORDER int(10),
  MENU_DATA  VARCHAR(500)
);

create table if not exists TBL_USER
(
  USER_ID              BIGINT(20)  auto_increment   not null primary key,
  LEAGUER_NO           VARCHAR(20)  not null,
  USER_NAME            VARCHAR(32)  not null unique,
  AUTH_KEY             VARCHAR(32)  not null,
  PASSWORD_HASH        VARCHAR(256) not null,
  PASSWORD_RESET_TOKEN VARCHAR(256),
  EMAIL                VARCHAR(256),
  USER_TYPE            VARCHAR(10)  not null,
  USER_INFO            VARCHAR(255),
  USER_STATUS          int not null,
  USER_NOTICE          VARCHAR(1024),
  REC_CRT_TS           DATETIME,
  REC_UPD_TS           DATETIME,
  PARENT_USER_NAME     VARCHAR(32)
) collate utf8_bin;

create table if not exists TBL_INS_INF
(
  INS_ID_CD          VARCHAR(11) not null primary key,
  INS_COMPANY_CD     VARCHAR(11),
  INS_TYPE           VARCHAR(1)  not null,
  INS_NAME           VARCHAR(100),
  INS_PROV_CD        VARCHAR(6),
  INS_CITY_CD        VARCHAR(6),
  INS_REGION_CD      VARCHAR(10),
  INS_STA            VARCHAR(2)  not null,
  INS_STLM_TP        VARCHAR(1),
  INS_ALO_STLM_CYCLE VARCHAR(1),
  INS_ALO_STLM_MD    VARCHAR(1),
  INS_STLM_C_NM      VARCHAR(80),
  INS_STLM_C_ACCT    VARCHAR(40),
  INS_STLM_C_BK_NO   VARCHAR(12),
  INS_STLM_C_BK_NM   VARCHAR(200),
  INS_STLM_D_NM      VARCHAR(80),
  INS_STLM_D_ACCT    VARCHAR(40),
  INS_STLM_D_BK_NO   VARCHAR(12),
  INS_STLM_D_BK_NM   VARCHAR(200),
  MSG_RESV_FLD1      VARCHAR(255),
  MSG_RESV_FLD2      VARCHAR(255),
  MSG_RESV_FLD3      VARCHAR(255),
  MSG_RESV_FLD4      VARCHAR(255),
  MSG_RESV_FLD5      VARCHAR(255),
  MSG_RESV_FLD6      VARCHAR(255),
  MSG_RESV_FLD7      VARCHAR(255),
  MSG_RESV_FLD8      VARCHAR(255),
  MSG_RESV_FLD9      VARCHAR(255),
  MSG_RESV_FLD10     VARCHAR(255),
  REC_OPR_ID         VARCHAR(1),
  REC_UPD_OPR        VARCHAR(32),
  REC_CRT_TS         DATETIME,
  REC_UPD_TS         DATETIME,
  index(INS_NAME)
);

create table if not exists TBL_CLEAR_TXN
(
	COMPANY_CD VARCHAR(11),
	INS_ID_CD VARCHAR(11),
	ACQ_INS_ID_CD VARCHAR(11),
	FWD_INS_ID_CD VARCHAR(11) not null,
	MCHT_CD VARCHAR(15),
	MCHT_NAME VARCHAR(80),
	MCHT_SHORT_NAME VARCHAR(40),
	MCC_CD VARCHAR(4),
	MCC_CD_42 VARCHAR(4),
	MCC_DESC VARCHAR(10),
	TRANS_DATE_TIME VARCHAR(10) not null,
	STLM_DATE VARCHAR(8) not null,
	TRANS_KIND VARCHAR(100),
	TXN_DESC VARCHAR(30),
	TRANS_STATE CHAR not null,
	STLM_FLG CHAR,
	TRANS_AMT VARCHAR(12),
	CREDITCARDLIMIT VARCHAR(12),
	CUP_SSN VARCHAR(6) not null,
	AUTHR_ID_RESP VARCHAR(6),
	PAN VARCHAR(19) not null,
	CARD_KIND_DIS VARCHAR(40),
	BANK_CODE VARCHAR(11),
	BANK_NAME VARCHAR(100),
	BRANCH_CD VARCHAR(12),
	BRANCH_NM VARCHAR(60),
	TERM_ID VARCHAR(8) not null,
	ORG_TRANS_DATE_TIME VARCHAR(10),
	ORG_CUP_SSN VARCHAR(6),
	POS_ENTRY_MODE VARCHAR(3),
	RSP_CODE VARCHAR(2),
	TRUE_FEE_MOD VARCHAR(12),
	TRUE_FEE_BI VARCHAR(12),
	TRUE_FEE_FD VARCHAR(12),
	TRUE_FEE_FFD VARCHAR(12),
	VAR_1 VARCHAR(12),
	VAR_2 VARCHAR(12),
	VAR_3 VARCHAR(12),
	VAR_4 VARCHAR(12),
	VIR_FEE_MOD VARCHAR(12),
	VIR_FEE_BI VARCHAR(12),
	VIR_FEE_BD VARCHAR(12),
	VIR_FEE_FD VARCHAR(12),
	MCHT_FEE VARCHAR(12),
	VAR_5 VARCHAR(12),
	MCHT_VIR_FEE VARCHAR(12),
	STAND_BANK_FEE VARCHAR(12),
	BANK_FEE VARCHAR(12),
	HZJG_FEE VARCHAR(12),
	JGSY VARCHAR(12),
	AIP_FEE VARCHAR(12),
	MCHT_SET_AMT VARCHAR(12),
	HZJGYFPPFWF VARCHAR(12),
	JGYFPPFWF VARCHAR(12),
	AIPYFPPFWF VARCHAR(12),
	ERR_FEE_IN VARCHAR(12),
	ERR_FEE_OUT VARCHAR(12),
	ERR_CODE VARCHAR(10),
	JT_MCHT_CD VARCHAR(15),
	EXPAND_ORG_CD VARCHAR(11),
	SPE_SERV_INST VARCHAR(11),
	PROP_INS VARCHAR(11),
	EXPAND_ORG_FEE VARCHAR(12),
	SPE_SERV_FEE VARCHAR(12),
	PROP_INS_FEE VARCHAR(12),
	EXPAND_ORG_PP VARCHAR(12),
	SPE_SERV_PP VARCHAR(12),
	PROP_INS_PP VARCHAR(12),
	EXPAND_FEE_IN VARCHAR(12),
	EXPAND_FEE_OUT VARCHAR(12),
	CUP_IFINSIDE_SIGN CHAR,
	SP_CHARG_TYPE VARCHAR(2),
	SP_CHARG_LEV CHAR,
	TERM_SSN VARCHAR(6),
	SN_SSN VARCHAR(6),
	UP_CHL_ID VARCHAR(11),
	CONV_MCHT_CD VARCHAR(15),
	CONV_TERM_ID VARCHAR(8),
	CHL_TRUE_FEE VARCHAR(12),
	CHL_STD_FEE VARCHAR(12),
	CHL_FEE_PRE_FLG VARCHAR(20),
	SYS_SER VARCHAR(12),
	VAR_6 VARCHAR(12),
	QUDAO_FEE VARCHAR(12),
	QUDAO_FEE_MIN VARCHAR(12),
	QUDAO_FEE_MIX VARCHAR(12),
	QUDAO_FEE_FD VARCHAR(12),
	INS_FEE VARCHAR(12),
	INS_MY_FEE VARCHAR(12),
	INS_COST_FEE VARCHAR(12),
	INS_MY_FEE_AMT VARCHAR(12),
	INS_SPLIT_FEE VARCHAR(12),
	INS_RES_FEE VARCHAR(12),
	PINP_FEE VARCHAR(12),
	PINP_FEE_INF VARCHAR(12),
	PINP_FEE_TOP VARCHAR(12),
	PINP_STAT VARCHAR(12),
	T0_STAT VARCHAR(12),
	KEY_RSP VARCHAR(255) not null,
	REMARK VARCHAR(255),
	REMARK1 VARCHAR(255),
	REMARK2 VARCHAR(255),
	REMARK3 VARCHAR(255),
	REMARK4 VARCHAR(255),
	REMARK5 VARCHAR(255),
	MA_SETTLE_DT DATE not null,
	RETRI_REF_NO VARCHAR(12),
	INDUSTRY_ADDN_INF VARCHAR(600),
	SRC_QID DECIMAL,
	PROD_CD VARCHAR(10),
    primary key(KEY_RSP),
    index(INS_ID_CD),
    index(COMPANY_CD),
    index(MCHT_CD),
    index(COMPANY_CD, INS_ID_CD, MCHT_CD),
    index(INS_ID_CD, MCHT_CD),
    index(STLM_DATE)
);


create table if not exists TBL_INS_PROD_BIZ_FEE_MAP_INF
(
	PROD_CD VARCHAR(10) not null,
	BIZ_CD VARCHAR(10) not null,
	MCC_M_TP VARCHAR(10) not null,
	MCC_S_TP VARCHAR(10) not null,
	INS_FEE_BIZ_CD VARCHAR(20) not null,
	INS_FEE_BIZ_NM VARCHAR(100),
	MSG_RESV_FLD1 VARCHAR(255),
	MSG_RESV_FLD2 VARCHAR(255),
	MSG_RESV_FLD3 VARCHAR(255),
	MSG_RESV_FLD4 VARCHAR(255),
	MSG_RESV_FLD5 VARCHAR(255),
	MSG_RESV_FLD6 VARCHAR(255),
	MSG_RESV_FLD7 VARCHAR(255),
	MSG_RESV_FLD8 VARCHAR(255),
	MSG_RESV_FLD9 VARCHAR(255),
	MSG_RESV_FLD10 VARCHAR(255),
	REC_OPR_ID VARCHAR(1),
	REC_UPD_OPR VARCHAR(32),
	REC_CRT_TS datetime default now(),
	REC_UPD_TS datetime default now(),
	primary key (PROD_CD, BIZ_CD, MCC_M_TP, MCC_S_TP)
);

create table if not exists TBL_PROD_BIZ_TRANS_MAP
(
	PROD_CD VARCHAR(20) not null,
	BIZ_CD VARCHAR(20) not null,
	TRANS_CD VARCHAR(20) not null,
	UPDATE_DATE VARCHAR(20),
	DESCRIPTION VARCHAR(20),
	RESV_FLD1 VARCHAR(20),
	RESV_FLD2 VARCHAR(20),
	RESV_FLD3 VARCHAR(20),
	primary key (PROD_CD, BIZ_CD, TRANS_CD)
);