// Code generated by protoc-gen-go. DO NOT EDIT.
// source: common.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Variable struct {
	Value                string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Type                 string   `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Variable) Reset()         { *m = Variable{} }
func (m *Variable) String() string { return proto.CompactTextString(m) }
func (*Variable) ProtoMessage()    {}
func (*Variable) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{0}
}

func (m *Variable) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Variable.Unmarshal(m, b)
}
func (m *Variable) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Variable.Marshal(b, m, deterministic)
}
func (m *Variable) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Variable.Merge(m, src)
}
func (m *Variable) XXX_Size() int {
	return xxx_messageInfo_Variable.Size(m)
}
func (m *Variable) XXX_DiscardUnknown() {
	xxx_messageInfo_Variable.DiscardUnknown(m)
}

var xxx_messageInfo_Variable proto.InternalMessageInfo

func (m *Variable) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *Variable) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

type CamundaError struct {
	Type                 string   `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CamundaError) Reset()         { *m = CamundaError{} }
func (m *CamundaError) String() string { return proto.CompactTextString(m) }
func (*CamundaError) ProtoMessage()    {}
func (*CamundaError) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{1}
}

func (m *CamundaError) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CamundaError.Unmarshal(m, b)
}
func (m *CamundaError) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CamundaError.Marshal(b, m, deterministic)
}
func (m *CamundaError) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CamundaError.Merge(m, src)
}
func (m *CamundaError) XXX_Size() int {
	return xxx_messageInfo_CamundaError.Size(m)
}
func (m *CamundaError) XXX_DiscardUnknown() {
	xxx_messageInfo_CamundaError.DiscardUnknown(m)
}

var xxx_messageInfo_CamundaError proto.InternalMessageInfo

func (m *CamundaError) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *CamundaError) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

// get请求参数， 必须是json格式
type GetQuery struct {
	Query                map[string]string `protobuf:"bytes,1,rep,name=query,proto3" json:"query,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *GetQuery) Reset()         { *m = GetQuery{} }
func (m *GetQuery) String() string { return proto.CompactTextString(m) }
func (*GetQuery) ProtoMessage()    {}
func (*GetQuery) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{2}
}

func (m *GetQuery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetQuery.Unmarshal(m, b)
}
func (m *GetQuery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetQuery.Marshal(b, m, deterministic)
}
func (m *GetQuery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetQuery.Merge(m, src)
}
func (m *GetQuery) XXX_Size() int {
	return xxx_messageInfo_GetQuery.Size(m)
}
func (m *GetQuery) XXX_DiscardUnknown() {
	xxx_messageInfo_GetQuery.DiscardUnknown(m)
}

var xxx_messageInfo_GetQuery proto.InternalMessageInfo

func (m *GetQuery) GetQuery() map[string]string {
	if m != nil {
		return m.Query
	}
	return nil
}

func init() {
	proto.RegisterType((*Variable)(nil), "pb.Variable")
	proto.RegisterType((*CamundaError)(nil), "pb.CamundaError")
	proto.RegisterType((*GetQuery)(nil), "pb.GetQuery")
	proto.RegisterMapType((map[string]string)(nil), "pb.GetQuery.QueryEntry")
}

func init() { proto.RegisterFile("common.proto", fileDescriptor_555bd8c177793206) }

var fileDescriptor_555bd8c177793206 = []byte{
	// 195 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x49, 0xce, 0xcf, 0xcd,
	0xcd, 0xcf, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2a, 0x48, 0x52, 0x32, 0xe1, 0xe2,
	0x08, 0x4b, 0x2c, 0xca, 0x4c, 0x4c, 0xca, 0x49, 0x15, 0x12, 0xe1, 0x62, 0x2d, 0x4b, 0xcc, 0x29,
	0x4d, 0x95, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x82, 0x70, 0x84, 0x84, 0xb8, 0x58, 0x4a, 0x2a,
	0x0b, 0x52, 0x25, 0x98, 0xc0, 0x82, 0x60, 0xb6, 0x92, 0x0d, 0x17, 0x8f, 0x73, 0x62, 0x6e, 0x69,
	0x5e, 0x4a, 0xa2, 0x6b, 0x51, 0x51, 0x7e, 0x11, 0x5c, 0x0d, 0x23, 0x42, 0x8d, 0x90, 0x04, 0x17,
	0x7b, 0x6e, 0x6a, 0x71, 0x71, 0x62, 0x3a, 0x4c, 0x2b, 0x8c, 0xab, 0x54, 0xcc, 0xc5, 0xe1, 0x9e,
	0x5a, 0x12, 0x58, 0x9a, 0x5a, 0x54, 0x29, 0xa4, 0xcb, 0xc5, 0x5a, 0x08, 0x62, 0x48, 0x30, 0x2a,
	0x30, 0x6b, 0x70, 0x1b, 0x89, 0xeb, 0x15, 0x24, 0xe9, 0xc1, 0x24, 0xf5, 0xc0, 0xa4, 0x6b, 0x5e,
	0x49, 0x51, 0x65, 0x10, 0x44, 0x95, 0x94, 0x05, 0x17, 0x17, 0x42, 0x50, 0x48, 0x80, 0x8b, 0x39,
	0x3b, 0xb5, 0x12, 0x6a, 0x2b, 0x88, 0x89, 0xf0, 0x02, 0x13, 0x92, 0x17, 0xac, 0x98, 0x2c, 0x18,
	0x93, 0xd8, 0xc0, 0x7e, 0x36, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0x24, 0xe1, 0x5d, 0xc3, 0x03,
	0x01, 0x00, 0x00,
}
