// Code generated by protoc-gen-go. DO NOT EDIT.
// source: task.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetListTaskReq struct {
	ProcessVariables     string   `protobuf:"bytes,1,opt,name=processVariables,proto3" json:"processVariables,omitempty"`
	ProcessDefinitionKey string   `protobuf:"bytes,2,opt,name=processDefinitionKey,proto3" json:"processDefinitionKey,omitempty"`
	ProcessInstanceId    string   `protobuf:"bytes,3,opt,name=processInstanceId,proto3" json:"processInstanceId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetListTaskReq) Reset()         { *m = GetListTaskReq{} }
func (m *GetListTaskReq) String() string { return proto.CompactTextString(m) }
func (*GetListTaskReq) ProtoMessage()    {}
func (*GetListTaskReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce5d8dd45b4a91ff, []int{0}
}

func (m *GetListTaskReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetListTaskReq.Unmarshal(m, b)
}
func (m *GetListTaskReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetListTaskReq.Marshal(b, m, deterministic)
}
func (m *GetListTaskReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetListTaskReq.Merge(m, src)
}
func (m *GetListTaskReq) XXX_Size() int {
	return xxx_messageInfo_GetListTaskReq.Size(m)
}
func (m *GetListTaskReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetListTaskReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetListTaskReq proto.InternalMessageInfo

func (m *GetListTaskReq) GetProcessVariables() string {
	if m != nil {
		return m.ProcessVariables
	}
	return ""
}

func (m *GetListTaskReq) GetProcessDefinitionKey() string {
	if m != nil {
		return m.ProcessDefinitionKey
	}
	return ""
}

func (m *GetListTaskReq) GetProcessInstanceId() string {
	if m != nil {
		return m.ProcessInstanceId
	}
	return ""
}

type GetListTaskResp struct {
	Tasks                []*TaskItem   `protobuf:"bytes,1,rep,name=tasks,proto3" json:"tasks,omitempty"`
	Code                 int64         `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	Err                  *CamundaError `protobuf:"bytes,3,opt,name=err,proto3" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *GetListTaskResp) Reset()         { *m = GetListTaskResp{} }
func (m *GetListTaskResp) String() string { return proto.CompactTextString(m) }
func (*GetListTaskResp) ProtoMessage()    {}
func (*GetListTaskResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce5d8dd45b4a91ff, []int{1}
}

func (m *GetListTaskResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetListTaskResp.Unmarshal(m, b)
}
func (m *GetListTaskResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetListTaskResp.Marshal(b, m, deterministic)
}
func (m *GetListTaskResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetListTaskResp.Merge(m, src)
}
func (m *GetListTaskResp) XXX_Size() int {
	return xxx_messageInfo_GetListTaskResp.Size(m)
}
func (m *GetListTaskResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetListTaskResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetListTaskResp proto.InternalMessageInfo

func (m *GetListTaskResp) GetTasks() []*TaskItem {
	if m != nil {
		return m.Tasks
	}
	return nil
}

func (m *GetListTaskResp) GetCode() int64 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *GetListTaskResp) GetErr() *CamundaError {
	if m != nil {
		return m.Err
	}
	return nil
}

type TaskItem struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Assignee             string   `protobuf:"bytes,3,opt,name=assignee,proto3" json:"assignee,omitempty"`
	Created              string   `protobuf:"bytes,4,opt,name=created,proto3" json:"created,omitempty"`
	Due                  string   `protobuf:"bytes,5,opt,name=due,proto3" json:"due,omitempty"`
	FollowUp             string   `protobuf:"bytes,6,opt,name=followUp,proto3" json:"followUp,omitempty"`
	DelegationState      string   `protobuf:"bytes,7,opt,name=delegationState,proto3" json:"delegationState,omitempty"`
	Description          string   `protobuf:"bytes,8,opt,name=description,proto3" json:"description,omitempty"`
	ExecutionId          string   `protobuf:"bytes,9,opt,name=executionId,proto3" json:"executionId,omitempty"`
	Owner                string   `protobuf:"bytes,10,opt,name=owner,proto3" json:"owner,omitempty"`
	ParentTaskId         string   `protobuf:"bytes,11,opt,name=parentTaskId,proto3" json:"parentTaskId,omitempty"`
	Priority             int64    `protobuf:"varint,12,opt,name=priority,proto3" json:"priority,omitempty"`
	ProcessDefinitionId  string   `protobuf:"bytes,13,opt,name=processDefinitionId,proto3" json:"processDefinitionId,omitempty"`
	ProcessInstanceId    string   `protobuf:"bytes,14,opt,name=processInstanceId,proto3" json:"processInstanceId,omitempty"`
	TaskDefinitionKey    string   `protobuf:"bytes,15,opt,name=taskDefinitionKey,proto3" json:"taskDefinitionKey,omitempty"`
	CaseExecutionId      string   `protobuf:"bytes,16,opt,name=caseExecutionId,proto3" json:"caseExecutionId,omitempty"`
	CaseInstanceId       string   `protobuf:"bytes,17,opt,name=caseInstanceId,proto3" json:"caseInstanceId,omitempty"`
	CaseDefinitionId     string   `protobuf:"bytes,18,opt,name=caseDefinitionId,proto3" json:"caseDefinitionId,omitempty"`
	Suspended            bool     `protobuf:"varint,19,opt,name=suspended,proto3" json:"suspended,omitempty"`
	FormKey              string   `protobuf:"bytes,20,opt,name=formKey,proto3" json:"formKey,omitempty"`
	TenantId             string   `protobuf:"bytes,21,opt,name=tenantId,proto3" json:"tenantId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TaskItem) Reset()         { *m = TaskItem{} }
func (m *TaskItem) String() string { return proto.CompactTextString(m) }
func (*TaskItem) ProtoMessage()    {}
func (*TaskItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce5d8dd45b4a91ff, []int{2}
}

func (m *TaskItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TaskItem.Unmarshal(m, b)
}
func (m *TaskItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TaskItem.Marshal(b, m, deterministic)
}
func (m *TaskItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TaskItem.Merge(m, src)
}
func (m *TaskItem) XXX_Size() int {
	return xxx_messageInfo_TaskItem.Size(m)
}
func (m *TaskItem) XXX_DiscardUnknown() {
	xxx_messageInfo_TaskItem.DiscardUnknown(m)
}

var xxx_messageInfo_TaskItem proto.InternalMessageInfo

func (m *TaskItem) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *TaskItem) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *TaskItem) GetAssignee() string {
	if m != nil {
		return m.Assignee
	}
	return ""
}

func (m *TaskItem) GetCreated() string {
	if m != nil {
		return m.Created
	}
	return ""
}

func (m *TaskItem) GetDue() string {
	if m != nil {
		return m.Due
	}
	return ""
}

func (m *TaskItem) GetFollowUp() string {
	if m != nil {
		return m.FollowUp
	}
	return ""
}

func (m *TaskItem) GetDelegationState() string {
	if m != nil {
		return m.DelegationState
	}
	return ""
}

func (m *TaskItem) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *TaskItem) GetExecutionId() string {
	if m != nil {
		return m.ExecutionId
	}
	return ""
}

func (m *TaskItem) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *TaskItem) GetParentTaskId() string {
	if m != nil {
		return m.ParentTaskId
	}
	return ""
}

func (m *TaskItem) GetPriority() int64 {
	if m != nil {
		return m.Priority
	}
	return 0
}

func (m *TaskItem) GetProcessDefinitionId() string {
	if m != nil {
		return m.ProcessDefinitionId
	}
	return ""
}

func (m *TaskItem) GetProcessInstanceId() string {
	if m != nil {
		return m.ProcessInstanceId
	}
	return ""
}

func (m *TaskItem) GetTaskDefinitionKey() string {
	if m != nil {
		return m.TaskDefinitionKey
	}
	return ""
}

func (m *TaskItem) GetCaseExecutionId() string {
	if m != nil {
		return m.CaseExecutionId
	}
	return ""
}

func (m *TaskItem) GetCaseInstanceId() string {
	if m != nil {
		return m.CaseInstanceId
	}
	return ""
}

func (m *TaskItem) GetCaseDefinitionId() string {
	if m != nil {
		return m.CaseDefinitionId
	}
	return ""
}

func (m *TaskItem) GetSuspended() bool {
	if m != nil {
		return m.Suspended
	}
	return false
}

func (m *TaskItem) GetFormKey() string {
	if m != nil {
		return m.FormKey
	}
	return ""
}

func (m *TaskItem) GetTenantId() string {
	if m != nil {
		return m.TenantId
	}
	return ""
}

type GetTaskReq struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTaskReq) Reset()         { *m = GetTaskReq{} }
func (m *GetTaskReq) String() string { return proto.CompactTextString(m) }
func (*GetTaskReq) ProtoMessage()    {}
func (*GetTaskReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce5d8dd45b4a91ff, []int{3}
}

func (m *GetTaskReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTaskReq.Unmarshal(m, b)
}
func (m *GetTaskReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTaskReq.Marshal(b, m, deterministic)
}
func (m *GetTaskReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTaskReq.Merge(m, src)
}
func (m *GetTaskReq) XXX_Size() int {
	return xxx_messageInfo_GetTaskReq.Size(m)
}
func (m *GetTaskReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTaskReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetTaskReq proto.InternalMessageInfo

func (m *GetTaskReq) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetTaskResp struct {
	Task                 *TaskItem     `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	Code                 int64         `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	Err                  *CamundaError `protobuf:"bytes,3,opt,name=err,proto3" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *GetTaskResp) Reset()         { *m = GetTaskResp{} }
func (m *GetTaskResp) String() string { return proto.CompactTextString(m) }
func (*GetTaskResp) ProtoMessage()    {}
func (*GetTaskResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce5d8dd45b4a91ff, []int{4}
}

func (m *GetTaskResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTaskResp.Unmarshal(m, b)
}
func (m *GetTaskResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTaskResp.Marshal(b, m, deterministic)
}
func (m *GetTaskResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTaskResp.Merge(m, src)
}
func (m *GetTaskResp) XXX_Size() int {
	return xxx_messageInfo_GetTaskResp.Size(m)
}
func (m *GetTaskResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTaskResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetTaskResp proto.InternalMessageInfo

func (m *GetTaskResp) GetTask() *TaskItem {
	if m != nil {
		return m.Task
	}
	return nil
}

func (m *GetTaskResp) GetCode() int64 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *GetTaskResp) GetErr() *CamundaError {
	if m != nil {
		return m.Err
	}
	return nil
}

type CompleteTaskReq struct {
	Id                   string               `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Body                 *CompleteTaskReqBody `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *CompleteTaskReq) Reset()         { *m = CompleteTaskReq{} }
func (m *CompleteTaskReq) String() string { return proto.CompactTextString(m) }
func (*CompleteTaskReq) ProtoMessage()    {}
func (*CompleteTaskReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce5d8dd45b4a91ff, []int{5}
}

func (m *CompleteTaskReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CompleteTaskReq.Unmarshal(m, b)
}
func (m *CompleteTaskReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CompleteTaskReq.Marshal(b, m, deterministic)
}
func (m *CompleteTaskReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CompleteTaskReq.Merge(m, src)
}
func (m *CompleteTaskReq) XXX_Size() int {
	return xxx_messageInfo_CompleteTaskReq.Size(m)
}
func (m *CompleteTaskReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CompleteTaskReq.DiscardUnknown(m)
}

var xxx_messageInfo_CompleteTaskReq proto.InternalMessageInfo

func (m *CompleteTaskReq) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *CompleteTaskReq) GetBody() *CompleteTaskReqBody {
	if m != nil {
		return m.Body
	}
	return nil
}

type CompleteTaskReqBody struct {
	Variables            map[string]*Variable `protobuf:"bytes,1,rep,name=variables,proto3" json:"variables,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *CompleteTaskReqBody) Reset()         { *m = CompleteTaskReqBody{} }
func (m *CompleteTaskReqBody) String() string { return proto.CompactTextString(m) }
func (*CompleteTaskReqBody) ProtoMessage()    {}
func (*CompleteTaskReqBody) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce5d8dd45b4a91ff, []int{6}
}

func (m *CompleteTaskReqBody) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CompleteTaskReqBody.Unmarshal(m, b)
}
func (m *CompleteTaskReqBody) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CompleteTaskReqBody.Marshal(b, m, deterministic)
}
func (m *CompleteTaskReqBody) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CompleteTaskReqBody.Merge(m, src)
}
func (m *CompleteTaskReqBody) XXX_Size() int {
	return xxx_messageInfo_CompleteTaskReqBody.Size(m)
}
func (m *CompleteTaskReqBody) XXX_DiscardUnknown() {
	xxx_messageInfo_CompleteTaskReqBody.DiscardUnknown(m)
}

var xxx_messageInfo_CompleteTaskReqBody proto.InternalMessageInfo

func (m *CompleteTaskReqBody) GetVariables() map[string]*Variable {
	if m != nil {
		return m.Variables
	}
	return nil
}

type CompleteTaskResp struct {
	Code                 int64         `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Err                  *CamundaError `protobuf:"bytes,2,opt,name=err,proto3" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *CompleteTaskResp) Reset()         { *m = CompleteTaskResp{} }
func (m *CompleteTaskResp) String() string { return proto.CompactTextString(m) }
func (*CompleteTaskResp) ProtoMessage()    {}
func (*CompleteTaskResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce5d8dd45b4a91ff, []int{7}
}

func (m *CompleteTaskResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CompleteTaskResp.Unmarshal(m, b)
}
func (m *CompleteTaskResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CompleteTaskResp.Marshal(b, m, deterministic)
}
func (m *CompleteTaskResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CompleteTaskResp.Merge(m, src)
}
func (m *CompleteTaskResp) XXX_Size() int {
	return xxx_messageInfo_CompleteTaskResp.Size(m)
}
func (m *CompleteTaskResp) XXX_DiscardUnknown() {
	xxx_messageInfo_CompleteTaskResp.DiscardUnknown(m)
}

var xxx_messageInfo_CompleteTaskResp proto.InternalMessageInfo

func (m *CompleteTaskResp) GetCode() int64 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *CompleteTaskResp) GetErr() *CamundaError {
	if m != nil {
		return m.Err
	}
	return nil
}

type GetFormValueRequest struct {
	TaskId               string   `protobuf:"bytes,1,opt,name=taskId,proto3" json:"taskId,omitempty"`
	ValueName            string   `protobuf:"bytes,2,opt,name=valueName,proto3" json:"valueName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetFormValueRequest) Reset()         { *m = GetFormValueRequest{} }
func (m *GetFormValueRequest) String() string { return proto.CompactTextString(m) }
func (*GetFormValueRequest) ProtoMessage()    {}
func (*GetFormValueRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce5d8dd45b4a91ff, []int{8}
}

func (m *GetFormValueRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetFormValueRequest.Unmarshal(m, b)
}
func (m *GetFormValueRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetFormValueRequest.Marshal(b, m, deterministic)
}
func (m *GetFormValueRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetFormValueRequest.Merge(m, src)
}
func (m *GetFormValueRequest) XXX_Size() int {
	return xxx_messageInfo_GetFormValueRequest.Size(m)
}
func (m *GetFormValueRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetFormValueRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetFormValueRequest proto.InternalMessageInfo

func (m *GetFormValueRequest) GetTaskId() string {
	if m != nil {
		return m.TaskId
	}
	return ""
}

func (m *GetFormValueRequest) GetValueName() string {
	if m != nil {
		return m.ValueName
	}
	return ""
}

type GetFormValueReply struct {
	Type                 string        `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Value                string        `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Err                  *CamundaError `protobuf:"bytes,3,opt,name=err,proto3" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *GetFormValueReply) Reset()         { *m = GetFormValueReply{} }
func (m *GetFormValueReply) String() string { return proto.CompactTextString(m) }
func (*GetFormValueReply) ProtoMessage()    {}
func (*GetFormValueReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce5d8dd45b4a91ff, []int{9}
}

func (m *GetFormValueReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetFormValueReply.Unmarshal(m, b)
}
func (m *GetFormValueReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetFormValueReply.Marshal(b, m, deterministic)
}
func (m *GetFormValueReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetFormValueReply.Merge(m, src)
}
func (m *GetFormValueReply) XXX_Size() int {
	return xxx_messageInfo_GetFormValueReply.Size(m)
}
func (m *GetFormValueReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetFormValueReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetFormValueReply proto.InternalMessageInfo

func (m *GetFormValueReply) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *GetFormValueReply) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *GetFormValueReply) GetErr() *CamundaError {
	if m != nil {
		return m.Err
	}
	return nil
}

func init() {
	proto.RegisterType((*GetListTaskReq)(nil), "pb.GetListTaskReq")
	proto.RegisterType((*GetListTaskResp)(nil), "pb.GetListTaskResp")
	proto.RegisterType((*TaskItem)(nil), "pb.TaskItem")
	proto.RegisterType((*GetTaskReq)(nil), "pb.GetTaskReq")
	proto.RegisterType((*GetTaskResp)(nil), "pb.GetTaskResp")
	proto.RegisterType((*CompleteTaskReq)(nil), "pb.CompleteTaskReq")
	proto.RegisterType((*CompleteTaskReqBody)(nil), "pb.CompleteTaskReqBody")
	proto.RegisterMapType((map[string]*Variable)(nil), "pb.CompleteTaskReqBody.VariablesEntry")
	proto.RegisterType((*CompleteTaskResp)(nil), "pb.CompleteTaskResp")
	proto.RegisterType((*GetFormValueRequest)(nil), "pb.GetFormValueRequest")
	proto.RegisterType((*GetFormValueReply)(nil), "pb.GetFormValueReply")
}

func init() { proto.RegisterFile("task.proto", fileDescriptor_ce5d8dd45b4a91ff) }

var fileDescriptor_ce5d8dd45b4a91ff = []byte{
	// 773 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x55, 0xcd, 0x8e, 0xdb, 0x36,
	0x10, 0x8e, 0x6c, 0xef, 0xae, 0x3d, 0x76, 0x6d, 0x2f, 0xbd, 0x69, 0x08, 0x23, 0x87, 0x85, 0x0e,
	0x81, 0xd1, 0x16, 0x8b, 0xc2, 0x2d, 0xd0, 0xa2, 0xa7, 0xa2, 0xc9, 0xd6, 0x50, 0x52, 0xe4, 0xa0,
	0xb6, 0xb9, 0xd3, 0xe2, 0xec, 0x42, 0x58, 0x49, 0x64, 0x48, 0x3a, 0xa9, 0x5e, 0xa6, 0xd7, 0xbe,
	0x41, 0xdf, 0xa7, 0x6f, 0x52, 0x0c, 0x25, 0xff, 0xc8, 0xf2, 0x16, 0x45, 0x6e, 0x9c, 0xef, 0x1b,
	0x8e, 0x66, 0x3e, 0xce, 0x8c, 0x00, 0x9c, 0xb0, 0x0f, 0x37, 0xda, 0x28, 0xa7, 0x58, 0x47, 0xaf,
	0xe7, 0xa3, 0x44, 0xe5, 0xb9, 0x2a, 0x2a, 0x24, 0xfc, 0x33, 0x80, 0xf1, 0x0a, 0xdd, 0x2f, 0xa9,
	0x75, 0xbf, 0x09, 0xfb, 0x10, 0xe3, 0x7b, 0xf6, 0x05, 0x4c, 0xb5, 0x51, 0x09, 0x5a, 0xfb, 0x4e,
	0x98, 0x54, 0xac, 0x33, 0xb4, 0x3c, 0xb8, 0x0e, 0x16, 0x83, 0xb8, 0x85, 0xb3, 0x25, 0x5c, 0xd5,
	0xd8, 0x2b, 0xbc, 0x4b, 0x8b, 0xd4, 0xa5, 0xaa, 0x78, 0x83, 0x25, 0xef, 0x78, 0xff, 0x93, 0x1c,
	0xfb, 0x0a, 0x2e, 0x6b, 0x3c, 0x2a, 0xac, 0x13, 0x45, 0x82, 0x91, 0xe4, 0x5d, 0x7f, 0xa1, 0x4d,
	0x84, 0x39, 0x4c, 0x1a, 0xf9, 0x59, 0xcd, 0x42, 0x38, 0xa3, 0x9a, 0x28, 0xab, 0xee, 0x62, 0xb8,
	0x1c, 0xdd, 0xe8, 0xf5, 0x0d, 0x91, 0x91, 0xc3, 0x3c, 0xae, 0x28, 0xc6, 0xa0, 0x97, 0x28, 0x89,
	0x3e, 0x91, 0x6e, 0xec, 0xcf, 0x2c, 0x84, 0x2e, 0x1a, 0xe3, 0x3f, 0x35, 0x5c, 0x4e, 0xe9, 0xd6,
	0x4b, 0x91, 0x6f, 0x0a, 0x29, 0x6e, 0x8d, 0x51, 0x26, 0x26, 0x32, 0xfc, 0xfb, 0x0c, 0xfa, 0xdb,
	0x58, 0x6c, 0x0c, 0x9d, 0x54, 0xd6, 0xb5, 0x77, 0x52, 0x49, 0x41, 0x0b, 0x91, 0x63, 0x5d, 0x9d,
	0x3f, 0xb3, 0x39, 0xf4, 0x85, 0xb5, 0xe9, 0x7d, 0x81, 0x58, 0x17, 0xb1, 0xb3, 0x19, 0x87, 0x8b,
	0xc4, 0xa0, 0x70, 0x28, 0x79, 0xcf, 0x53, 0x5b, 0x93, 0x4d, 0xa1, 0x2b, 0x37, 0xc8, 0xcf, 0x3c,
	0x4a, 0x47, 0x8a, 0x73, 0xa7, 0xb2, 0x4c, 0x7d, 0xfc, 0x5d, 0xf3, 0xf3, 0x2a, 0xce, 0xd6, 0x66,
	0x0b, 0x98, 0x48, 0xcc, 0xf0, 0x5e, 0x90, 0x84, 0xbf, 0x3a, 0xe1, 0x90, 0x5f, 0x78, 0x97, 0x63,
	0x98, 0x5d, 0xc3, 0x50, 0xa2, 0x4d, 0x4c, 0xaa, 0x09, 0xe3, 0x7d, 0xef, 0x75, 0x08, 0x91, 0x07,
	0xfe, 0x81, 0xc9, 0x86, 0x8c, 0x48, 0xf2, 0x41, 0xe5, 0x71, 0x00, 0xb1, 0x2b, 0x38, 0x53, 0x1f,
	0x0b, 0x34, 0x1c, 0x3c, 0x57, 0x19, 0x2c, 0x84, 0x91, 0x16, 0x06, 0x0b, 0xff, 0x0c, 0x91, 0xe4,
	0x43, 0x4f, 0x36, 0x30, 0xaa, 0x41, 0x9b, 0x54, 0x99, 0xd4, 0x95, 0x7c, 0xe4, 0x85, 0xdf, 0xd9,
	0xec, 0x6b, 0x98, 0xb5, 0xba, 0x21, 0x92, 0xfc, 0x33, 0x1f, 0xe6, 0x14, 0x75, 0xba, 0x4f, 0xc6,
	0x8f, 0xf4, 0x09, 0x79, 0xd3, 0xcb, 0x37, 0xdb, 0x70, 0x52, 0x79, 0xb7, 0x08, 0x52, 0x34, 0x11,
	0x16, 0x6f, 0x0f, 0x94, 0x98, 0x56, 0x8a, 0x1e, 0xc1, 0xec, 0x05, 0x8c, 0x09, 0x3a, 0x48, 0xe1,
	0xd2, 0x3b, 0x1e, 0xa1, 0x34, 0x35, 0x84, 0x34, 0x8a, 0x63, 0xd5, 0xd4, 0x1c, 0xe3, 0xec, 0x39,
	0x0c, 0xec, 0xc6, 0x6a, 0x2c, 0x24, 0x4a, 0x3e, 0xbb, 0x0e, 0x16, 0xfd, 0x78, 0x0f, 0x50, 0xd7,
	0xdc, 0x29, 0x93, 0x53, 0xfe, 0x57, 0x55, 0xd7, 0xd4, 0x26, 0xe9, 0xeb, 0xb0, 0x10, 0x85, 0x8b,
	0x24, 0x7f, 0x5a, 0xf5, 0xc8, 0xd6, 0x0e, 0x9f, 0x03, 0xac, 0x70, 0x37, 0xc3, 0x47, 0x9d, 0x1b,
	0xde, 0xc3, 0x70, 0xc7, 0x5a, 0xcd, 0xae, 0xa1, 0x47, 0x9a, 0x78, 0x87, 0xe3, 0x01, 0xf2, 0xcc,
	0x27, 0xcf, 0xcf, 0x5b, 0x98, 0xbc, 0x54, 0xb9, 0xce, 0xd0, 0xe1, 0x41, 0x2e, 0xd1, 0x2e, 0x97,
	0x48, 0xb2, 0x2f, 0xa1, 0xb7, 0x56, 0xb2, 0xda, 0x11, 0xc3, 0xe5, 0x33, 0x1f, 0xa7, 0x79, 0xe5,
	0x27, 0x25, 0xcb, 0xd8, 0x3b, 0x85, 0x7f, 0x05, 0x30, 0x3b, 0xc1, 0xb2, 0x57, 0x30, 0xf8, 0x70,
	0xb0, 0x9d, 0x68, 0x0f, 0xbc, 0x78, 0x24, 0xd2, 0xcd, 0x6e, 0x5d, 0xdd, 0x16, 0xce, 0x94, 0xf1,
	0xfe, 0xe2, 0xfc, 0x35, 0x8c, 0x9b, 0x24, 0x0d, 0xe6, 0x03, 0x96, 0x75, 0xb6, 0x74, 0xa4, 0x6d,
	0xf3, 0x41, 0x64, 0x1b, 0xac, 0xf3, 0xf5, 0x62, 0x6d, 0x2f, 0xc5, 0x15, 0xf5, 0x43, 0xe7, 0xfb,
	0x20, 0x7c, 0x0d, 0xd3, 0xe6, 0xc7, 0xad, 0xde, 0xa9, 0x18, 0xb4, 0x55, 0xec, 0xfc, 0x97, 0x8a,
	0x6f, 0x60, 0xb6, 0x42, 0xf7, 0xb3, 0x32, 0xf9, 0x3b, 0x8a, 0x1f, 0xe3, 0xfb, 0x0d, 0x5a, 0xc7,
	0x3e, 0x87, 0x73, 0x57, 0x4d, 0x5f, 0x95, 0x5f, 0x6d, 0x51, 0x3f, 0xf9, 0x3c, 0xde, 0xee, 0x97,
	0xd3, 0x1e, 0x08, 0x05, 0x5c, 0x36, 0x83, 0xe9, 0xac, 0xa4, 0xcc, 0x5c, 0xa9, 0xb1, 0x0e, 0xe4,
	0xcf, 0x34, 0xf8, 0xfb, 0x4a, 0x07, 0x75, 0x6d, 0xff, 0xe7, 0xd5, 0x97, 0xff, 0x04, 0xd0, 0xa3,
	0xa2, 0xd9, 0xb7, 0x70, 0x51, 0x6f, 0x6b, 0xc6, 0xc8, 0xb5, 0xf9, 0x6b, 0x99, 0xcf, 0x5a, 0x98,
	0xd5, 0xe1, 0x13, 0xf6, 0x1d, 0xf4, 0xb7, 0xd2, 0xb1, 0xd9, 0x89, 0x57, 0x9c, 0x5f, 0xb5, 0x41,
	0x7f, 0x71, 0x01, 0xdd, 0x15, 0x3a, 0x36, 0xae, 0xc3, 0x6e, 0xdd, 0x27, 0x0d, 0xdb, 0x7b, 0xfe,
	0x08, 0xa3, 0x43, 0x11, 0xd8, 0xb3, 0xda, 0xe5, 0x58, 0xe3, 0xf9, 0xd3, 0x36, 0xa1, 0xb3, 0x32,
	0x7c, 0xb2, 0x3e, 0xf7, 0x3f, 0xcc, 0x6f, 0xfe, 0x0d, 0x00, 0x00, 0xff, 0xff, 0xd5, 0xeb, 0x2f,
	0x9a, 0x50, 0x07, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TaskClient is the client API for Task service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TaskClient interface {
	GetList(ctx context.Context, in *GetListTaskReq, opts ...grpc.CallOption) (*GetListTaskResp, error)
	Complete(ctx context.Context, in *CompleteTaskReq, opts ...grpc.CallOption) (*CompleteTaskResp, error)
	Get(ctx context.Context, in *GetTaskReq, opts ...grpc.CallOption) (*GetTaskResp, error)
	GetFormValue(ctx context.Context, in *GetFormValueRequest, opts ...grpc.CallOption) (*GetFormValueReply, error)
}

type taskClient struct {
	cc *grpc.ClientConn
}

func NewTaskClient(cc *grpc.ClientConn) TaskClient {
	return &taskClient{cc}
}

func (c *taskClient) GetList(ctx context.Context, in *GetListTaskReq, opts ...grpc.CallOption) (*GetListTaskResp, error) {
	out := new(GetListTaskResp)
	err := c.cc.Invoke(ctx, "/pb.Task/GetList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskClient) Complete(ctx context.Context, in *CompleteTaskReq, opts ...grpc.CallOption) (*CompleteTaskResp, error) {
	out := new(CompleteTaskResp)
	err := c.cc.Invoke(ctx, "/pb.Task/Complete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskClient) Get(ctx context.Context, in *GetTaskReq, opts ...grpc.CallOption) (*GetTaskResp, error) {
	out := new(GetTaskResp)
	err := c.cc.Invoke(ctx, "/pb.Task/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskClient) GetFormValue(ctx context.Context, in *GetFormValueRequest, opts ...grpc.CallOption) (*GetFormValueReply, error) {
	out := new(GetFormValueReply)
	err := c.cc.Invoke(ctx, "/pb.Task/GetFormValue", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TaskServer is the server API for Task service.
type TaskServer interface {
	GetList(context.Context, *GetListTaskReq) (*GetListTaskResp, error)
	Complete(context.Context, *CompleteTaskReq) (*CompleteTaskResp, error)
	Get(context.Context, *GetTaskReq) (*GetTaskResp, error)
	GetFormValue(context.Context, *GetFormValueRequest) (*GetFormValueReply, error)
}

// UnimplementedTaskServer can be embedded to have forward compatible implementations.
type UnimplementedTaskServer struct {
}

func (*UnimplementedTaskServer) GetList(ctx context.Context, req *GetListTaskReq) (*GetListTaskResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetList not implemented")
}
func (*UnimplementedTaskServer) Complete(ctx context.Context, req *CompleteTaskReq) (*CompleteTaskResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Complete not implemented")
}
func (*UnimplementedTaskServer) Get(ctx context.Context, req *GetTaskReq) (*GetTaskResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (*UnimplementedTaskServer) GetFormValue(ctx context.Context, req *GetFormValueRequest) (*GetFormValueReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFormValue not implemented")
}

func RegisterTaskServer(s *grpc.Server, srv TaskServer) {
	s.RegisterService(&_Task_serviceDesc, srv)
}

func _Task_GetList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetListTaskReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServer).GetList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Task/GetList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServer).GetList(ctx, req.(*GetListTaskReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Task_Complete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompleteTaskReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServer).Complete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Task/Complete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServer).Complete(ctx, req.(*CompleteTaskReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Task_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTaskReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Task/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServer).Get(ctx, req.(*GetTaskReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Task_GetFormValue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFormValueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServer).GetFormValue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Task/GetFormValue",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServer).GetFormValue(ctx, req.(*GetFormValueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Task_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Task",
	HandlerType: (*TaskServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetList",
			Handler:    _Task_GetList_Handler,
		},
		{
			MethodName: "Complete",
			Handler:    _Task_Complete_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _Task_Get_Handler,
		},
		{
			MethodName: "GetFormValue",
			Handler:    _Task_GetFormValue_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "task.proto",
}
