// Code generated by protoc-gen-go. DO NOT EDIT.
// source: hitstory.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetListHistoryProcessInstanceResp struct {
	Item                 []*GetListHistoryProcessInstanceRespItem `protobuf:"bytes,1,rep,name=item,proto3" json:"item,omitempty"`
	Code                 int64                                    `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	Err                  *CamundaError                            `protobuf:"bytes,3,opt,name=err,proto3" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                 `json:"-"`
	XXX_unrecognized     []byte                                   `json:"-"`
	XXX_sizecache        int32                                    `json:"-"`
}

func (m *GetListHistoryProcessInstanceResp) Reset()         { *m = GetListHistoryProcessInstanceResp{} }
func (m *GetListHistoryProcessInstanceResp) String() string { return proto.CompactTextString(m) }
func (*GetListHistoryProcessInstanceResp) ProtoMessage()    {}
func (*GetListHistoryProcessInstanceResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_c2a3c2de2006a431, []int{0}
}

func (m *GetListHistoryProcessInstanceResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetListHistoryProcessInstanceResp.Unmarshal(m, b)
}
func (m *GetListHistoryProcessInstanceResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetListHistoryProcessInstanceResp.Marshal(b, m, deterministic)
}
func (m *GetListHistoryProcessInstanceResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetListHistoryProcessInstanceResp.Merge(m, src)
}
func (m *GetListHistoryProcessInstanceResp) XXX_Size() int {
	return xxx_messageInfo_GetListHistoryProcessInstanceResp.Size(m)
}
func (m *GetListHistoryProcessInstanceResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetListHistoryProcessInstanceResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetListHistoryProcessInstanceResp proto.InternalMessageInfo

func (m *GetListHistoryProcessInstanceResp) GetItem() []*GetListHistoryProcessInstanceRespItem {
	if m != nil {
		return m.Item
	}
	return nil
}

func (m *GetListHistoryProcessInstanceResp) GetCode() int64 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *GetListHistoryProcessInstanceResp) GetErr() *CamundaError {
	if m != nil {
		return m.Err
	}
	return nil
}

type GetListHistoryProcessInstanceRespItem struct {
	Id                       string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	RootProcessInstanceId    string   `protobuf:"bytes,2,opt,name=rootProcessInstanceId,proto3" json:"rootProcessInstanceId,omitempty"`
	SuperProcessInstanceId   string   `protobuf:"bytes,3,opt,name=superProcessInstanceId,proto3" json:"superProcessInstanceId,omitempty"`
	SuperCaseInstanceId      string   `protobuf:"bytes,4,opt,name=superCaseInstanceId,proto3" json:"superCaseInstanceId,omitempty"`
	ProcessDefinitionName    string   `protobuf:"bytes,5,opt,name=processDefinitionName,proto3" json:"processDefinitionName,omitempty"`
	ProcessDefinitionKey     string   `protobuf:"bytes,7,opt,name=processDefinitionKey,proto3" json:"processDefinitionKey,omitempty"`
	ProcessDefinitionVersion int64    `protobuf:"varint,8,opt,name=processDefinitionVersion,proto3" json:"processDefinitionVersion,omitempty"`
	ProcessDefinitionId      string   `protobuf:"bytes,9,opt,name=processDefinitionId,proto3" json:"processDefinitionId,omitempty"`
	BusinessKey              string   `protobuf:"bytes,10,opt,name=businessKey,proto3" json:"businessKey,omitempty"`
	StartTime                string   `protobuf:"bytes,11,opt,name=startTime,proto3" json:"startTime,omitempty"`
	EndTime                  string   `protobuf:"bytes,12,opt,name=endTime,proto3" json:"endTime,omitempty"`
	RemovalTime              string   `protobuf:"bytes,13,opt,name=removalTime,proto3" json:"removalTime,omitempty"`
	DurationInMillis         int64    `protobuf:"varint,14,opt,name=durationInMillis,proto3" json:"durationInMillis,omitempty"`
	StartUserId              string   `protobuf:"bytes,15,opt,name=startUserId,proto3" json:"startUserId,omitempty"`
	StartActivityId          string   `protobuf:"bytes,16,opt,name=startActivityId,proto3" json:"startActivityId,omitempty"`
	DeleteReason             string   `protobuf:"bytes,17,opt,name=deleteReason,proto3" json:"deleteReason,omitempty"`
	TenantId                 string   `protobuf:"bytes,18,opt,name=tenantId,proto3" json:"tenantId,omitempty"`
	State                    string   `protobuf:"bytes,19,opt,name=state,proto3" json:"state,omitempty"`
	XXX_NoUnkeyedLiteral     struct{} `json:"-"`
	XXX_unrecognized         []byte   `json:"-"`
	XXX_sizecache            int32    `json:"-"`
}

func (m *GetListHistoryProcessInstanceRespItem) Reset()         { *m = GetListHistoryProcessInstanceRespItem{} }
func (m *GetListHistoryProcessInstanceRespItem) String() string { return proto.CompactTextString(m) }
func (*GetListHistoryProcessInstanceRespItem) ProtoMessage()    {}
func (*GetListHistoryProcessInstanceRespItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_c2a3c2de2006a431, []int{1}
}

func (m *GetListHistoryProcessInstanceRespItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetListHistoryProcessInstanceRespItem.Unmarshal(m, b)
}
func (m *GetListHistoryProcessInstanceRespItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetListHistoryProcessInstanceRespItem.Marshal(b, m, deterministic)
}
func (m *GetListHistoryProcessInstanceRespItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetListHistoryProcessInstanceRespItem.Merge(m, src)
}
func (m *GetListHistoryProcessInstanceRespItem) XXX_Size() int {
	return xxx_messageInfo_GetListHistoryProcessInstanceRespItem.Size(m)
}
func (m *GetListHistoryProcessInstanceRespItem) XXX_DiscardUnknown() {
	xxx_messageInfo_GetListHistoryProcessInstanceRespItem.DiscardUnknown(m)
}

var xxx_messageInfo_GetListHistoryProcessInstanceRespItem proto.InternalMessageInfo

func (m *GetListHistoryProcessInstanceRespItem) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *GetListHistoryProcessInstanceRespItem) GetRootProcessInstanceId() string {
	if m != nil {
		return m.RootProcessInstanceId
	}
	return ""
}

func (m *GetListHistoryProcessInstanceRespItem) GetSuperProcessInstanceId() string {
	if m != nil {
		return m.SuperProcessInstanceId
	}
	return ""
}

func (m *GetListHistoryProcessInstanceRespItem) GetSuperCaseInstanceId() string {
	if m != nil {
		return m.SuperCaseInstanceId
	}
	return ""
}

func (m *GetListHistoryProcessInstanceRespItem) GetProcessDefinitionName() string {
	if m != nil {
		return m.ProcessDefinitionName
	}
	return ""
}

func (m *GetListHistoryProcessInstanceRespItem) GetProcessDefinitionKey() string {
	if m != nil {
		return m.ProcessDefinitionKey
	}
	return ""
}

func (m *GetListHistoryProcessInstanceRespItem) GetProcessDefinitionVersion() int64 {
	if m != nil {
		return m.ProcessDefinitionVersion
	}
	return 0
}

func (m *GetListHistoryProcessInstanceRespItem) GetProcessDefinitionId() string {
	if m != nil {
		return m.ProcessDefinitionId
	}
	return ""
}

func (m *GetListHistoryProcessInstanceRespItem) GetBusinessKey() string {
	if m != nil {
		return m.BusinessKey
	}
	return ""
}

func (m *GetListHistoryProcessInstanceRespItem) GetStartTime() string {
	if m != nil {
		return m.StartTime
	}
	return ""
}

func (m *GetListHistoryProcessInstanceRespItem) GetEndTime() string {
	if m != nil {
		return m.EndTime
	}
	return ""
}

func (m *GetListHistoryProcessInstanceRespItem) GetRemovalTime() string {
	if m != nil {
		return m.RemovalTime
	}
	return ""
}

func (m *GetListHistoryProcessInstanceRespItem) GetDurationInMillis() int64 {
	if m != nil {
		return m.DurationInMillis
	}
	return 0
}

func (m *GetListHistoryProcessInstanceRespItem) GetStartUserId() string {
	if m != nil {
		return m.StartUserId
	}
	return ""
}

func (m *GetListHistoryProcessInstanceRespItem) GetStartActivityId() string {
	if m != nil {
		return m.StartActivityId
	}
	return ""
}

func (m *GetListHistoryProcessInstanceRespItem) GetDeleteReason() string {
	if m != nil {
		return m.DeleteReason
	}
	return ""
}

func (m *GetListHistoryProcessInstanceRespItem) GetTenantId() string {
	if m != nil {
		return m.TenantId
	}
	return ""
}

func (m *GetListHistoryProcessInstanceRespItem) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func init() {
	proto.RegisterType((*GetListHistoryProcessInstanceResp)(nil), "pb.GetListHistoryProcessInstanceResp")
	proto.RegisterType((*GetListHistoryProcessInstanceRespItem)(nil), "pb.GetListHistoryProcessInstanceRespItem")
}

func init() { proto.RegisterFile("hitstory.proto", fileDescriptor_c2a3c2de2006a431) }

var fileDescriptor_c2a3c2de2006a431 = []byte{
	// 479 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x93, 0x4d, 0x8f, 0xd3, 0x3e,
	0x10, 0xc6, 0xff, 0xe9, 0xcb, 0xbf, 0xdb, 0x69, 0xe9, 0x96, 0xd9, 0x65, 0x65, 0x55, 0x1c, 0x4a,
	0xa5, 0x95, 0x02, 0x87, 0x0a, 0x15, 0xc4, 0x01, 0x89, 0x03, 0x5a, 0x10, 0x44, 0xbc, 0x47, 0xc0,
	0x81, 0x9b, 0x1b, 0x0f, 0xc2, 0x52, 0x63, 0x47, 0xb6, 0xb3, 0x52, 0xbf, 0x0a, 0xdf, 0x94, 0x1b,
	0xca, 0xa4, 0x40, 0x69, 0xb2, 0x62, 0x6f, 0x99, 0xe7, 0x37, 0xcf, 0xe3, 0xb1, 0xe2, 0x81, 0xc9,
	0x37, 0x1d, 0x7c, 0xb0, 0x6e, 0xbb, 0x2c, 0x9c, 0x0d, 0x16, 0x3b, 0xc5, 0x7a, 0x36, 0xce, 0x6c,
	0x9e, 0x5b, 0x53, 0x2b, 0x8b, 0xef, 0x11, 0xdc, 0x79, 0x41, 0xe1, 0xb5, 0xf6, 0xe1, 0xa5, 0xe6,
	0xd6, 0xf7, 0xce, 0x66, 0xe4, 0x7d, 0x62, 0x7c, 0x90, 0x26, 0xa3, 0x94, 0x7c, 0x81, 0x4f, 0xa0,
	0xa7, 0x03, 0xe5, 0x22, 0x9a, 0x77, 0xe3, 0xd1, 0xea, 0xee, 0xb2, 0x58, 0x2f, 0xff, 0x69, 0x4a,
	0x02, 0xe5, 0x29, 0xdb, 0x10, 0xa1, 0x97, 0x59, 0x45, 0xa2, 0x33, 0x8f, 0xe2, 0x6e, 0xca, 0xdf,
	0xb8, 0x80, 0x2e, 0x39, 0x27, 0xba, 0xf3, 0x28, 0x1e, 0xad, 0xa6, 0x55, 0xe2, 0x85, 0xcc, 0x4b,
	0xa3, 0xe4, 0x73, 0xe7, 0xac, 0x4b, 0x2b, 0xb8, 0xf8, 0xd1, 0x87, 0xf3, 0x6b, 0x9d, 0x83, 0x13,
	0xe8, 0x68, 0x25, 0xa2, 0x79, 0x14, 0x0f, 0xd3, 0x8e, 0x56, 0xf8, 0x10, 0x6e, 0x39, 0x6b, 0xc3,
	0x41, 0x7b, 0xa2, 0x78, 0x84, 0x61, 0xda, 0x0e, 0xf1, 0x11, 0x9c, 0xf9, 0xb2, 0x20, 0xd7, 0xb4,
	0x75, 0xd9, 0x76, 0x05, 0xc5, 0xfb, 0x70, 0xc2, 0xe4, 0x42, 0x7a, 0xda, 0x33, 0xf5, 0xd8, 0xd4,
	0x86, 0xaa, 0xf9, 0x8a, 0x3a, 0xe6, 0x19, 0x7d, 0xd5, 0x46, 0x07, 0x6d, 0xcd, 0x5b, 0x99, 0x93,
	0xe8, 0xd7, 0xf3, 0xb5, 0x42, 0x5c, 0xc1, 0x69, 0x03, 0xbc, 0xa2, 0xad, 0x18, 0xb0, 0xa9, 0x95,
	0xe1, 0x63, 0x10, 0x0d, 0xfd, 0x33, 0x39, 0xaf, 0xad, 0x11, 0x47, 0xfc, 0x3f, 0xae, 0xe4, 0xd5,
	0xbd, 0x1a, 0x2c, 0x51, 0x62, 0x58, 0xdf, 0xab, 0x05, 0xe1, 0x1c, 0x46, 0xeb, 0xd2, 0x6b, 0x43,
	0xde, 0x57, 0x83, 0x01, 0x77, 0xee, 0x4b, 0x78, 0x1b, 0x86, 0x3e, 0x48, 0x17, 0x3e, 0xea, 0x9c,
	0xc4, 0x88, 0xf9, 0x1f, 0x01, 0x05, 0x0c, 0xc8, 0x28, 0x66, 0x63, 0x66, 0xbf, 0xca, 0x2a, 0xd9,
	0x51, 0x6e, 0x2f, 0xe5, 0x86, 0xe9, 0x8d, 0x3a, 0x79, 0x4f, 0xc2, 0x7b, 0x30, 0x55, 0xa5, 0x93,
	0x3c, 0x89, 0x79, 0xa3, 0x37, 0x1b, 0xed, 0xc5, 0x84, 0x6f, 0xd8, 0xd0, 0xab, 0x34, 0x3e, 0xf4,
	0x93, 0x27, 0x97, 0x28, 0x71, 0x5c, 0xa7, 0xed, 0x49, 0x18, 0xc3, 0x31, 0x97, 0x4f, 0xb3, 0xa0,
	0x2f, 0x75, 0xd8, 0x26, 0x4a, 0x4c, 0xb9, 0xeb, 0x50, 0xc6, 0x05, 0x8c, 0x15, 0x6d, 0x28, 0x50,
	0x4a, 0xd2, 0x5b, 0x23, 0x6e, 0x72, 0xdb, 0x5f, 0x1a, 0xce, 0xe0, 0x28, 0x90, 0x91, 0x26, 0x24,
	0x4a, 0x20, 0xf3, 0xdf, 0x35, 0x9e, 0x42, 0xdf, 0x07, 0x19, 0x48, 0x9c, 0x30, 0xa8, 0x8b, 0xd5,
	0x17, 0x18, 0xec, 0xde, 0x3c, 0xbe, 0x83, 0xb3, 0xdd, 0x16, 0x1c, 0x3c, 0x3d, 0x1c, 0xef, 0x36,
	0xf1, 0x43, 0x49, 0x6e, 0x3b, 0x3b, 0xbf, 0xd6, 0x5e, 0x2e, 0xfe, 0x5b, 0xff, 0xcf, 0xbb, 0xff,
	0xe0, 0x67, 0x00, 0x00, 0x00, 0xff, 0xff, 0x8b, 0x51, 0x0b, 0xf8, 0x1f, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// HistoryClient is the client API for History service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type HistoryClient interface {
	GetListProcessInstance(ctx context.Context, in *GetQuery, opts ...grpc.CallOption) (*GetListHistoryProcessInstanceResp, error)
}

type historyClient struct {
	cc *grpc.ClientConn
}

func NewHistoryClient(cc *grpc.ClientConn) HistoryClient {
	return &historyClient{cc}
}

func (c *historyClient) GetListProcessInstance(ctx context.Context, in *GetQuery, opts ...grpc.CallOption) (*GetListHistoryProcessInstanceResp, error) {
	out := new(GetListHistoryProcessInstanceResp)
	err := c.cc.Invoke(ctx, "/pb.History/GetListProcessInstance", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HistoryServer is the server API for History service.
type HistoryServer interface {
	GetListProcessInstance(context.Context, *GetQuery) (*GetListHistoryProcessInstanceResp, error)
}

// UnimplementedHistoryServer can be embedded to have forward compatible implementations.
type UnimplementedHistoryServer struct {
}

func (*UnimplementedHistoryServer) GetListProcessInstance(ctx context.Context, req *GetQuery) (*GetListHistoryProcessInstanceResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetListProcessInstance not implemented")
}

func RegisterHistoryServer(s *grpc.Server, srv HistoryServer) {
	s.RegisterService(&_History_serviceDesc, srv)
}

func _History_GetListProcessInstance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetQuery)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HistoryServer).GetListProcessInstance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.History/GetListProcessInstance",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HistoryServer).GetListProcessInstance(ctx, req.(*GetQuery))
	}
	return interceptor(ctx, in, info, handler)
}

var _History_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.History",
	HandlerType: (*HistoryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetListProcessInstance",
			Handler:    _History_GetListProcessInstance_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "hitstory.proto",
}
