// Code generated by protoc-gen-go. DO NOT EDIT.
// source: merchant.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ListMerchantRequest struct {
	Page                 int32          `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Size                 int32          `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	Item                 *MerchantField `protobuf:"bytes,3,opt,name=item,proto3" json:"item,omitempty"`
	Type                 string         `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ListMerchantRequest) Reset()         { *m = ListMerchantRequest{} }
func (m *ListMerchantRequest) String() string { return proto.CompactTextString(m) }
func (*ListMerchantRequest) ProtoMessage()    {}
func (*ListMerchantRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_87fc684f407252a1, []int{0}
}

func (m *ListMerchantRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListMerchantRequest.Unmarshal(m, b)
}
func (m *ListMerchantRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListMerchantRequest.Marshal(b, m, deterministic)
}
func (m *ListMerchantRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListMerchantRequest.Merge(m, src)
}
func (m *ListMerchantRequest) XXX_Size() int {
	return xxx_messageInfo_ListMerchantRequest.Size(m)
}
func (m *ListMerchantRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListMerchantRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListMerchantRequest proto.InternalMessageInfo

func (m *ListMerchantRequest) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *ListMerchantRequest) GetSize() int32 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *ListMerchantRequest) GetItem() *MerchantField {
	if m != nil {
		return m.Item
	}
	return nil
}

func (m *ListMerchantRequest) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

type ListMerchantReply struct {
	Items                []*MerchantField `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Count                int32            `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	Size                 int32            `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	Page                 int32            `protobuf:"varint,4,opt,name=page,proto3" json:"page,omitempty"`
	Err                  *Error           `protobuf:"bytes,5,opt,name=err,proto3" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *ListMerchantReply) Reset()         { *m = ListMerchantReply{} }
func (m *ListMerchantReply) String() string { return proto.CompactTextString(m) }
func (*ListMerchantReply) ProtoMessage()    {}
func (*ListMerchantReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_87fc684f407252a1, []int{1}
}

func (m *ListMerchantReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListMerchantReply.Unmarshal(m, b)
}
func (m *ListMerchantReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListMerchantReply.Marshal(b, m, deterministic)
}
func (m *ListMerchantReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListMerchantReply.Merge(m, src)
}
func (m *ListMerchantReply) XXX_Size() int {
	return xxx_messageInfo_ListMerchantReply.Size(m)
}
func (m *ListMerchantReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ListMerchantReply.DiscardUnknown(m)
}

var xxx_messageInfo_ListMerchantReply proto.InternalMessageInfo

func (m *ListMerchantReply) GetItems() []*MerchantField {
	if m != nil {
		return m.Items
	}
	return nil
}

func (m *ListMerchantReply) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *ListMerchantReply) GetSize() int32 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *ListMerchantReply) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *ListMerchantReply) GetErr() *Error {
	if m != nil {
		return m.Err
	}
	return nil
}

type MerchantField struct {
	MchtCd                string   `protobuf:"bytes,1,opt,name=mchtCd,proto3" json:"mchtCd,omitempty"`
	Sn                    string   `protobuf:"bytes,2,opt,name=sn,proto3" json:"sn,omitempty"`
	AipBranCd             string   `protobuf:"bytes,3,opt,name=aipBranCd,proto3" json:"aipBranCd,omitempty"`
	GroupCd               string   `protobuf:"bytes,4,opt,name=groupCd,proto3" json:"groupCd,omitempty"`
	OriChnl               string   `protobuf:"bytes,5,opt,name=oriChnl,proto3" json:"oriChnl,omitempty"`
	OriChnlDesc           string   `protobuf:"bytes,6,opt,name=oriChnlDesc,proto3" json:"oriChnlDesc,omitempty"`
	BankBelongCd          string   `protobuf:"bytes,7,opt,name=bankBelongCd,proto3" json:"bankBelongCd,omitempty"`
	DvpBy                 string   `protobuf:"bytes,8,opt,name=dvpBy,proto3" json:"dvpBy,omitempty"`
	MccCd18               string   `protobuf:"bytes,9,opt,name=mccCd18,proto3" json:"mccCd18,omitempty"`
	ApplDate              string   `protobuf:"bytes,10,opt,name=applDate,proto3" json:"applDate,omitempty"`
	UpBcCd                string   `protobuf:"bytes,11,opt,name=upBcCd,proto3" json:"upBcCd,omitempty"`
	UpAcCd                string   `protobuf:"bytes,12,opt,name=upAcCd,proto3" json:"upAcCd,omitempty"`
	UpMccCd               string   `protobuf:"bytes,13,opt,name=upMccCd,proto3" json:"upMccCd,omitempty"`
	Name                  string   `protobuf:"bytes,14,opt,name=name,proto3" json:"name,omitempty"`
	NameBusi              string   `protobuf:"bytes,15,opt,name=nameBusi,proto3" json:"nameBusi,omitempty"`
	BusiLiceNo            string   `protobuf:"bytes,16,opt,name=busiLiceNo,proto3" json:"busiLiceNo,omitempty"`
	BusiRang              string   `protobuf:"bytes,17,opt,name=busiRang,proto3" json:"busiRang,omitempty"`
	BusiMain              string   `protobuf:"bytes,18,opt,name=busiMain,proto3" json:"busiMain,omitempty"`
	Certif                string   `protobuf:"bytes,19,opt,name=certif,proto3" json:"certif,omitempty"`
	CertifType            string   `protobuf:"bytes,20,opt,name=certifType,proto3" json:"certifType,omitempty"`
	CertifNo              string   `protobuf:"bytes,21,opt,name=certifNo,proto3" json:"certifNo,omitempty"`
	CityCd                string   `protobuf:"bytes,22,opt,name=cityCd,proto3" json:"cityCd,omitempty"`
	AreaCd                string   `protobuf:"bytes,23,opt,name=areaCd,proto3" json:"areaCd,omitempty"`
	RegAddr               string   `protobuf:"bytes,24,opt,name=regAddr,proto3" json:"regAddr,omitempty"`
	ContactName           string   `protobuf:"bytes,25,opt,name=contactName,proto3" json:"contactName,omitempty"`
	ContactPhoneNo        string   `protobuf:"bytes,26,opt,name=contactPhoneNo,proto3" json:"contactPhoneNo,omitempty"`
	IsGroup               string   `protobuf:"bytes,27,opt,name=isGroup,proto3" json:"isGroup,omitempty"`
	MoneyToGroup          string   `protobuf:"bytes,28,opt,name=moneyToGroup,proto3" json:"moneyToGroup,omitempty"`
	StlmWay               string   `protobuf:"bytes,29,opt,name=stlmWay,proto3" json:"stlmWay,omitempty"`
	StlmWayDesc           string   `protobuf:"bytes,30,opt,name=stlmWayDesc,proto3" json:"stlmWayDesc,omitempty"`
	StlmInsCircle         string   `protobuf:"bytes,31,opt,name=stlmInsCircle,proto3" json:"stlmInsCircle,omitempty"`
	ApprDate              string   `protobuf:"bytes,32,opt,name=apprDate,proto3" json:"apprDate,omitempty"`
	Status                string   `protobuf:"bytes,33,opt,name=status,proto3" json:"status,omitempty"`
	DeleteDate            string   `protobuf:"bytes,34,opt,name=deleteDate,proto3" json:"deleteDate,omitempty"`
	UcBcCd32              string   `protobuf:"bytes,35,opt,name=ucBcCd32,proto3" json:"ucBcCd32,omitempty"`
	K2WorkflowId          string   `protobuf:"bytes,36,opt,name=k2WorkflowId,proto3" json:"k2WorkflowId,omitempty"`
	SystemFlag            string   `protobuf:"bytes,37,opt,name=systemFlag,proto3" json:"systemFlag,omitempty"`
	ApprovalUsername      string   `protobuf:"bytes,38,opt,name=approvalUsername,proto3" json:"approvalUsername,omitempty"`
	FinalApprovalUsername string   `protobuf:"bytes,39,opt,name=finalApprovalUsername,proto3" json:"finalApprovalUsername,omitempty"`
	IsUpStandard          string   `protobuf:"bytes,40,opt,name=isUpStandard,proto3" json:"isUpStandard,omitempty"`
	BillingType           string   `protobuf:"bytes,41,opt,name=billingType,proto3" json:"billingType,omitempty"`
	BillingLevel          string   `protobuf:"bytes,42,opt,name=billingLevel,proto3" json:"billingLevel,omitempty"`
	Slogan                string   `protobuf:"bytes,43,opt,name=slogan,proto3" json:"slogan,omitempty"`
	Ext1                  string   `protobuf:"bytes,44,opt,name=ext1,proto3" json:"ext1,omitempty"`
	Ext2                  string   `protobuf:"bytes,45,opt,name=ext2,proto3" json:"ext2,omitempty"`
	Ext3                  string   `protobuf:"bytes,46,opt,name=ext3,proto3" json:"ext3,omitempty"`
	Ext4                  string   `protobuf:"bytes,47,opt,name=ext4,proto3" json:"ext4,omitempty"`
	AreaStandard          string   `protobuf:"bytes,48,opt,name=areaStandard,proto3" json:"areaStandard,omitempty"`
	MchtCdAreaCd          string   `protobuf:"bytes,49,opt,name=mchtCdAreaCd,proto3" json:"mchtCdAreaCd,omitempty"`
	UcBcCdArea            string   `protobuf:"bytes,50,opt,name=ucBcCdArea,proto3" json:"ucBcCdArea,omitempty"`
	RecOprId              string   `protobuf:"bytes,51,opt,name=recOprId,proto3" json:"recOprId,omitempty"`
	RecUpdOpr             string   `protobuf:"bytes,52,opt,name=recUpdOpr,proto3" json:"recUpdOpr,omitempty"`
	RecCrtTs              string   `protobuf:"bytes,53,opt,name=recCrtTs,proto3" json:"recCrtTs,omitempty"`
	RecUpdTs              string   `protobuf:"bytes,54,opt,name=recUpdTs,proto3" json:"recUpdTs,omitempty"`
	OperIn                string   `protobuf:"bytes,55,opt,name=operIn,proto3" json:"operIn,omitempty"`
	RecApllyTs            string   `protobuf:"bytes,56,opt,name=recApllyTs,proto3" json:"recApllyTs,omitempty"`
	OemOrgCode            string   `protobuf:"bytes,57,opt,name=oemOrgCode,proto3" json:"oemOrgCode,omitempty"`
	IsEleInvoice          string   `protobuf:"bytes,58,opt,name=isEleInvoice,proto3" json:"isEleInvoice,omitempty"`
	DutyParagraph         string   `protobuf:"bytes,59,opt,name=dutyParagraph,proto3" json:"dutyParagraph,omitempty"`
	TaxMachineBrand       string   `protobuf:"bytes,60,opt,name=taxMachineBrand,proto3" json:"taxMachineBrand,omitempty"`
	Ext5                  string   `protobuf:"bytes,61,opt,name=ext5,proto3" json:"ext5,omitempty"`
	Ext6                  string   `protobuf:"bytes,62,opt,name=ext6,proto3" json:"ext6,omitempty"`
	Ext7                  string   `protobuf:"bytes,63,opt,name=ext7,proto3" json:"ext7,omitempty"`
	Ext8                  string   `protobuf:"bytes,64,opt,name=ext8,proto3" json:"ext8,omitempty"`
	Ext9                  string   `protobuf:"bytes,65,opt,name=ext9,proto3" json:"ext9,omitempty"`
	BusiLiceSt            string   `protobuf:"bytes,66,opt,name=busiLiceSt,proto3" json:"busiLiceSt,omitempty"`
	BusiLiceDt            string   `protobuf:"bytes,67,opt,name=busiLiceDt,proto3" json:"busiLiceDt,omitempty"`
	CertifSt              string   `protobuf:"bytes,68,opt,name=certifSt,proto3" json:"certifSt,omitempty"`
	CertifDt              string   `protobuf:"bytes,69,opt,name=certifDt,proto3" json:"certifDt,omitempty"`
	XXX_NoUnkeyedLiteral  struct{} `json:"-"`
	XXX_unrecognized      []byte   `json:"-"`
	XXX_sizecache         int32    `json:"-"`
}

func (m *MerchantField) Reset()         { *m = MerchantField{} }
func (m *MerchantField) String() string { return proto.CompactTextString(m) }
func (*MerchantField) ProtoMessage()    {}
func (*MerchantField) Descriptor() ([]byte, []int) {
	return fileDescriptor_87fc684f407252a1, []int{2}
}

func (m *MerchantField) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MerchantField.Unmarshal(m, b)
}
func (m *MerchantField) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MerchantField.Marshal(b, m, deterministic)
}
func (m *MerchantField) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MerchantField.Merge(m, src)
}
func (m *MerchantField) XXX_Size() int {
	return xxx_messageInfo_MerchantField.Size(m)
}
func (m *MerchantField) XXX_DiscardUnknown() {
	xxx_messageInfo_MerchantField.DiscardUnknown(m)
}

var xxx_messageInfo_MerchantField proto.InternalMessageInfo

func (m *MerchantField) GetMchtCd() string {
	if m != nil {
		return m.MchtCd
	}
	return ""
}

func (m *MerchantField) GetSn() string {
	if m != nil {
		return m.Sn
	}
	return ""
}

func (m *MerchantField) GetAipBranCd() string {
	if m != nil {
		return m.AipBranCd
	}
	return ""
}

func (m *MerchantField) GetGroupCd() string {
	if m != nil {
		return m.GroupCd
	}
	return ""
}

func (m *MerchantField) GetOriChnl() string {
	if m != nil {
		return m.OriChnl
	}
	return ""
}

func (m *MerchantField) GetOriChnlDesc() string {
	if m != nil {
		return m.OriChnlDesc
	}
	return ""
}

func (m *MerchantField) GetBankBelongCd() string {
	if m != nil {
		return m.BankBelongCd
	}
	return ""
}

func (m *MerchantField) GetDvpBy() string {
	if m != nil {
		return m.DvpBy
	}
	return ""
}

func (m *MerchantField) GetMccCd18() string {
	if m != nil {
		return m.MccCd18
	}
	return ""
}

func (m *MerchantField) GetApplDate() string {
	if m != nil {
		return m.ApplDate
	}
	return ""
}

func (m *MerchantField) GetUpBcCd() string {
	if m != nil {
		return m.UpBcCd
	}
	return ""
}

func (m *MerchantField) GetUpAcCd() string {
	if m != nil {
		return m.UpAcCd
	}
	return ""
}

func (m *MerchantField) GetUpMccCd() string {
	if m != nil {
		return m.UpMccCd
	}
	return ""
}

func (m *MerchantField) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *MerchantField) GetNameBusi() string {
	if m != nil {
		return m.NameBusi
	}
	return ""
}

func (m *MerchantField) GetBusiLiceNo() string {
	if m != nil {
		return m.BusiLiceNo
	}
	return ""
}

func (m *MerchantField) GetBusiRang() string {
	if m != nil {
		return m.BusiRang
	}
	return ""
}

func (m *MerchantField) GetBusiMain() string {
	if m != nil {
		return m.BusiMain
	}
	return ""
}

func (m *MerchantField) GetCertif() string {
	if m != nil {
		return m.Certif
	}
	return ""
}

func (m *MerchantField) GetCertifType() string {
	if m != nil {
		return m.CertifType
	}
	return ""
}

func (m *MerchantField) GetCertifNo() string {
	if m != nil {
		return m.CertifNo
	}
	return ""
}

func (m *MerchantField) GetCityCd() string {
	if m != nil {
		return m.CityCd
	}
	return ""
}

func (m *MerchantField) GetAreaCd() string {
	if m != nil {
		return m.AreaCd
	}
	return ""
}

func (m *MerchantField) GetRegAddr() string {
	if m != nil {
		return m.RegAddr
	}
	return ""
}

func (m *MerchantField) GetContactName() string {
	if m != nil {
		return m.ContactName
	}
	return ""
}

func (m *MerchantField) GetContactPhoneNo() string {
	if m != nil {
		return m.ContactPhoneNo
	}
	return ""
}

func (m *MerchantField) GetIsGroup() string {
	if m != nil {
		return m.IsGroup
	}
	return ""
}

func (m *MerchantField) GetMoneyToGroup() string {
	if m != nil {
		return m.MoneyToGroup
	}
	return ""
}

func (m *MerchantField) GetStlmWay() string {
	if m != nil {
		return m.StlmWay
	}
	return ""
}

func (m *MerchantField) GetStlmWayDesc() string {
	if m != nil {
		return m.StlmWayDesc
	}
	return ""
}

func (m *MerchantField) GetStlmInsCircle() string {
	if m != nil {
		return m.StlmInsCircle
	}
	return ""
}

func (m *MerchantField) GetApprDate() string {
	if m != nil {
		return m.ApprDate
	}
	return ""
}

func (m *MerchantField) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *MerchantField) GetDeleteDate() string {
	if m != nil {
		return m.DeleteDate
	}
	return ""
}

func (m *MerchantField) GetUcBcCd32() string {
	if m != nil {
		return m.UcBcCd32
	}
	return ""
}

func (m *MerchantField) GetK2WorkflowId() string {
	if m != nil {
		return m.K2WorkflowId
	}
	return ""
}

func (m *MerchantField) GetSystemFlag() string {
	if m != nil {
		return m.SystemFlag
	}
	return ""
}

func (m *MerchantField) GetApprovalUsername() string {
	if m != nil {
		return m.ApprovalUsername
	}
	return ""
}

func (m *MerchantField) GetFinalApprovalUsername() string {
	if m != nil {
		return m.FinalApprovalUsername
	}
	return ""
}

func (m *MerchantField) GetIsUpStandard() string {
	if m != nil {
		return m.IsUpStandard
	}
	return ""
}

func (m *MerchantField) GetBillingType() string {
	if m != nil {
		return m.BillingType
	}
	return ""
}

func (m *MerchantField) GetBillingLevel() string {
	if m != nil {
		return m.BillingLevel
	}
	return ""
}

func (m *MerchantField) GetSlogan() string {
	if m != nil {
		return m.Slogan
	}
	return ""
}

func (m *MerchantField) GetExt1() string {
	if m != nil {
		return m.Ext1
	}
	return ""
}

func (m *MerchantField) GetExt2() string {
	if m != nil {
		return m.Ext2
	}
	return ""
}

func (m *MerchantField) GetExt3() string {
	if m != nil {
		return m.Ext3
	}
	return ""
}

func (m *MerchantField) GetExt4() string {
	if m != nil {
		return m.Ext4
	}
	return ""
}

func (m *MerchantField) GetAreaStandard() string {
	if m != nil {
		return m.AreaStandard
	}
	return ""
}

func (m *MerchantField) GetMchtCdAreaCd() string {
	if m != nil {
		return m.MchtCdAreaCd
	}
	return ""
}

func (m *MerchantField) GetUcBcCdArea() string {
	if m != nil {
		return m.UcBcCdArea
	}
	return ""
}

func (m *MerchantField) GetRecOprId() string {
	if m != nil {
		return m.RecOprId
	}
	return ""
}

func (m *MerchantField) GetRecUpdOpr() string {
	if m != nil {
		return m.RecUpdOpr
	}
	return ""
}

func (m *MerchantField) GetRecCrtTs() string {
	if m != nil {
		return m.RecCrtTs
	}
	return ""
}

func (m *MerchantField) GetRecUpdTs() string {
	if m != nil {
		return m.RecUpdTs
	}
	return ""
}

func (m *MerchantField) GetOperIn() string {
	if m != nil {
		return m.OperIn
	}
	return ""
}

func (m *MerchantField) GetRecApllyTs() string {
	if m != nil {
		return m.RecApllyTs
	}
	return ""
}

func (m *MerchantField) GetOemOrgCode() string {
	if m != nil {
		return m.OemOrgCode
	}
	return ""
}

func (m *MerchantField) GetIsEleInvoice() string {
	if m != nil {
		return m.IsEleInvoice
	}
	return ""
}

func (m *MerchantField) GetDutyParagraph() string {
	if m != nil {
		return m.DutyParagraph
	}
	return ""
}

func (m *MerchantField) GetTaxMachineBrand() string {
	if m != nil {
		return m.TaxMachineBrand
	}
	return ""
}

func (m *MerchantField) GetExt5() string {
	if m != nil {
		return m.Ext5
	}
	return ""
}

func (m *MerchantField) GetExt6() string {
	if m != nil {
		return m.Ext6
	}
	return ""
}

func (m *MerchantField) GetExt7() string {
	if m != nil {
		return m.Ext7
	}
	return ""
}

func (m *MerchantField) GetExt8() string {
	if m != nil {
		return m.Ext8
	}
	return ""
}

func (m *MerchantField) GetExt9() string {
	if m != nil {
		return m.Ext9
	}
	return ""
}

func (m *MerchantField) GetBusiLiceSt() string {
	if m != nil {
		return m.BusiLiceSt
	}
	return ""
}

func (m *MerchantField) GetBusiLiceDt() string {
	if m != nil {
		return m.BusiLiceDt
	}
	return ""
}

func (m *MerchantField) GetCertifSt() string {
	if m != nil {
		return m.CertifSt
	}
	return ""
}

func (m *MerchantField) GetCertifDt() string {
	if m != nil {
		return m.CertifDt
	}
	return ""
}

type MerchantGroupField struct {
	JtMchtCd             string   `protobuf:"bytes,1,opt,name=jtMchtCd,proto3" json:"jtMchtCd,omitempty"`
	JtMchtNm             string   `protobuf:"bytes,2,opt,name=jtMchtNm,proto3" json:"jtMchtNm,omitempty"`
	JtArea               string   `protobuf:"bytes,3,opt,name=jtArea,proto3" json:"jtArea,omitempty"`
	MchtStlmCNm          string   `protobuf:"bytes,4,opt,name=mchtStlmCNm,proto3" json:"mchtStlmCNm,omitempty"`
	MchtStlmCAcct        string   `protobuf:"bytes,5,opt,name=mchtStlmCAcct,proto3" json:"mchtStlmCAcct,omitempty"`
	ChtStlmInsIdCd       string   `protobuf:"bytes,6,opt,name=chtStlmInsIdCd,proto3" json:"chtStlmInsIdCd,omitempty"`
	MchtStlmInsNm        string   `protobuf:"bytes,7,opt,name=mchtStlmInsNm,proto3" json:"mchtStlmInsNm,omitempty"`
	MchtPaySysAcct       string   `protobuf:"bytes,8,opt,name=mchtPaySysAcct,proto3" json:"mchtPaySysAcct,omitempty"`
	ProvCd               string   `protobuf:"bytes,9,opt,name=provCd,proto3" json:"provCd,omitempty"`
	CityCd               string   `protobuf:"bytes,10,opt,name=cityCd,proto3" json:"cityCd,omitempty"`
	AipBranCd            string   `protobuf:"bytes,11,opt,name=aipBranCd,proto3" json:"aipBranCd,omitempty"`
	SystemFlag           string   `protobuf:"bytes,12,opt,name=systemFlag,proto3" json:"systemFlag,omitempty"`
	Status               string   `protobuf:"bytes,13,opt,name=status,proto3" json:"status,omitempty"`
	UpdatedAt            string   `protobuf:"bytes,14,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	CreatedAt            string   `protobuf:"bytes,15,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	RecOprId             string   `protobuf:"bytes,16,opt,name=recOprId,proto3" json:"recOprId,omitempty"`
	RecUpdOpr            string   `protobuf:"bytes,17,opt,name=recUpdOpr,proto3" json:"recUpdOpr,omitempty"`
	JtAddr               string   `protobuf:"bytes,18,opt,name=jtAddr,proto3" json:"jtAddr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MerchantGroupField) Reset()         { *m = MerchantGroupField{} }
func (m *MerchantGroupField) String() string { return proto.CompactTextString(m) }
func (*MerchantGroupField) ProtoMessage()    {}
func (*MerchantGroupField) Descriptor() ([]byte, []int) {
	return fileDescriptor_87fc684f407252a1, []int{3}
}

func (m *MerchantGroupField) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MerchantGroupField.Unmarshal(m, b)
}
func (m *MerchantGroupField) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MerchantGroupField.Marshal(b, m, deterministic)
}
func (m *MerchantGroupField) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MerchantGroupField.Merge(m, src)
}
func (m *MerchantGroupField) XXX_Size() int {
	return xxx_messageInfo_MerchantGroupField.Size(m)
}
func (m *MerchantGroupField) XXX_DiscardUnknown() {
	xxx_messageInfo_MerchantGroupField.DiscardUnknown(m)
}

var xxx_messageInfo_MerchantGroupField proto.InternalMessageInfo

func (m *MerchantGroupField) GetJtMchtCd() string {
	if m != nil {
		return m.JtMchtCd
	}
	return ""
}

func (m *MerchantGroupField) GetJtMchtNm() string {
	if m != nil {
		return m.JtMchtNm
	}
	return ""
}

func (m *MerchantGroupField) GetJtArea() string {
	if m != nil {
		return m.JtArea
	}
	return ""
}

func (m *MerchantGroupField) GetMchtStlmCNm() string {
	if m != nil {
		return m.MchtStlmCNm
	}
	return ""
}

func (m *MerchantGroupField) GetMchtStlmCAcct() string {
	if m != nil {
		return m.MchtStlmCAcct
	}
	return ""
}

func (m *MerchantGroupField) GetChtStlmInsIdCd() string {
	if m != nil {
		return m.ChtStlmInsIdCd
	}
	return ""
}

func (m *MerchantGroupField) GetMchtStlmInsNm() string {
	if m != nil {
		return m.MchtStlmInsNm
	}
	return ""
}

func (m *MerchantGroupField) GetMchtPaySysAcct() string {
	if m != nil {
		return m.MchtPaySysAcct
	}
	return ""
}

func (m *MerchantGroupField) GetProvCd() string {
	if m != nil {
		return m.ProvCd
	}
	return ""
}

func (m *MerchantGroupField) GetCityCd() string {
	if m != nil {
		return m.CityCd
	}
	return ""
}

func (m *MerchantGroupField) GetAipBranCd() string {
	if m != nil {
		return m.AipBranCd
	}
	return ""
}

func (m *MerchantGroupField) GetSystemFlag() string {
	if m != nil {
		return m.SystemFlag
	}
	return ""
}

func (m *MerchantGroupField) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *MerchantGroupField) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

func (m *MerchantGroupField) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *MerchantGroupField) GetRecOprId() string {
	if m != nil {
		return m.RecOprId
	}
	return ""
}

func (m *MerchantGroupField) GetRecUpdOpr() string {
	if m != nil {
		return m.RecUpdOpr
	}
	return ""
}

func (m *MerchantGroupField) GetJtAddr() string {
	if m != nil {
		return m.JtAddr
	}
	return ""
}

type ListGroupMerchantRequest struct {
	Page                 int32               `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Size                 int32               `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	Item                 *MerchantGroupField `protobuf:"bytes,3,opt,name=item,proto3" json:"item,omitempty"`
	Type                 string              `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *ListGroupMerchantRequest) Reset()         { *m = ListGroupMerchantRequest{} }
func (m *ListGroupMerchantRequest) String() string { return proto.CompactTextString(m) }
func (*ListGroupMerchantRequest) ProtoMessage()    {}
func (*ListGroupMerchantRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_87fc684f407252a1, []int{4}
}

func (m *ListGroupMerchantRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListGroupMerchantRequest.Unmarshal(m, b)
}
func (m *ListGroupMerchantRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListGroupMerchantRequest.Marshal(b, m, deterministic)
}
func (m *ListGroupMerchantRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListGroupMerchantRequest.Merge(m, src)
}
func (m *ListGroupMerchantRequest) XXX_Size() int {
	return xxx_messageInfo_ListGroupMerchantRequest.Size(m)
}
func (m *ListGroupMerchantRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListGroupMerchantRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListGroupMerchantRequest proto.InternalMessageInfo

func (m *ListGroupMerchantRequest) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *ListGroupMerchantRequest) GetSize() int32 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *ListGroupMerchantRequest) GetItem() *MerchantGroupField {
	if m != nil {
		return m.Item
	}
	return nil
}

func (m *ListGroupMerchantRequest) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

type ListGroupMerchantReply struct {
	Items                []*MerchantGroupField `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Count                int32                 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	Size                 int32                 `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	Page                 int32                 `protobuf:"varint,4,opt,name=page,proto3" json:"page,omitempty"`
	Err                  *Error                `protobuf:"bytes,5,opt,name=err,proto3" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *ListGroupMerchantReply) Reset()         { *m = ListGroupMerchantReply{} }
func (m *ListGroupMerchantReply) String() string { return proto.CompactTextString(m) }
func (*ListGroupMerchantReply) ProtoMessage()    {}
func (*ListGroupMerchantReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_87fc684f407252a1, []int{5}
}

func (m *ListGroupMerchantReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListGroupMerchantReply.Unmarshal(m, b)
}
func (m *ListGroupMerchantReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListGroupMerchantReply.Marshal(b, m, deterministic)
}
func (m *ListGroupMerchantReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListGroupMerchantReply.Merge(m, src)
}
func (m *ListGroupMerchantReply) XXX_Size() int {
	return xxx_messageInfo_ListGroupMerchantReply.Size(m)
}
func (m *ListGroupMerchantReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ListGroupMerchantReply.DiscardUnknown(m)
}

var xxx_messageInfo_ListGroupMerchantReply proto.InternalMessageInfo

func (m *ListGroupMerchantReply) GetItems() []*MerchantGroupField {
	if m != nil {
		return m.Items
	}
	return nil
}

func (m *ListGroupMerchantReply) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *ListGroupMerchantReply) GetSize() int32 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *ListGroupMerchantReply) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *ListGroupMerchantReply) GetErr() *Error {
	if m != nil {
		return m.Err
	}
	return nil
}

type SaveMerchantRequest struct {
	Item                 *MerchantField `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *SaveMerchantRequest) Reset()         { *m = SaveMerchantRequest{} }
func (m *SaveMerchantRequest) String() string { return proto.CompactTextString(m) }
func (*SaveMerchantRequest) ProtoMessage()    {}
func (*SaveMerchantRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_87fc684f407252a1, []int{6}
}

func (m *SaveMerchantRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SaveMerchantRequest.Unmarshal(m, b)
}
func (m *SaveMerchantRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SaveMerchantRequest.Marshal(b, m, deterministic)
}
func (m *SaveMerchantRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SaveMerchantRequest.Merge(m, src)
}
func (m *SaveMerchantRequest) XXX_Size() int {
	return xxx_messageInfo_SaveMerchantRequest.Size(m)
}
func (m *SaveMerchantRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SaveMerchantRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SaveMerchantRequest proto.InternalMessageInfo

func (m *SaveMerchantRequest) GetItem() *MerchantField {
	if m != nil {
		return m.Item
	}
	return nil
}

type SaveMerchantReply struct {
	Err                  *Error   `protobuf:"bytes,1,opt,name=err,proto3" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SaveMerchantReply) Reset()         { *m = SaveMerchantReply{} }
func (m *SaveMerchantReply) String() string { return proto.CompactTextString(m) }
func (*SaveMerchantReply) ProtoMessage()    {}
func (*SaveMerchantReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_87fc684f407252a1, []int{7}
}

func (m *SaveMerchantReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SaveMerchantReply.Unmarshal(m, b)
}
func (m *SaveMerchantReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SaveMerchantReply.Marshal(b, m, deterministic)
}
func (m *SaveMerchantReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SaveMerchantReply.Merge(m, src)
}
func (m *SaveMerchantReply) XXX_Size() int {
	return xxx_messageInfo_SaveMerchantReply.Size(m)
}
func (m *SaveMerchantReply) XXX_DiscardUnknown() {
	xxx_messageInfo_SaveMerchantReply.DiscardUnknown(m)
}

var xxx_messageInfo_SaveMerchantReply proto.InternalMessageInfo

func (m *SaveMerchantReply) GetErr() *Error {
	if m != nil {
		return m.Err
	}
	return nil
}

type MerchantBankAccountField struct {
	OwnerCd              string   `protobuf:"bytes,1,opt,name=ownerCd,proto3" json:"ownerCd,omitempty"`
	AccountType          string   `protobuf:"bytes,2,opt,name=accountType,proto3" json:"accountType,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Account              string   `protobuf:"bytes,4,opt,name=account,proto3" json:"account,omitempty"`
	UcBcCd               string   `protobuf:"bytes,5,opt,name=ucBcCd,proto3" json:"ucBcCd,omitempty"`
	Province             string   `protobuf:"bytes,6,opt,name=province,proto3" json:"province,omitempty"`
	City                 string   `protobuf:"bytes,7,opt,name=city,proto3" json:"city,omitempty"`
	BankCode             string   `protobuf:"bytes,8,opt,name=bankCode,proto3" json:"bankCode,omitempty"`
	BankName             string   `protobuf:"bytes,9,opt,name=bankName,proto3" json:"bankName,omitempty"`
	OperIn               string   `protobuf:"bytes,10,opt,name=operIn,proto3" json:"operIn,omitempty"`
	RecOprId             string   `protobuf:"bytes,11,opt,name=recOprId,proto3" json:"recOprId,omitempty"`
	RecUpdOpr            string   `protobuf:"bytes,12,opt,name=recUpdOpr,proto3" json:"recUpdOpr,omitempty"`
	MsgResvFld1          string   `protobuf:"bytes,13,opt,name=msgResvFld1,proto3" json:"msgResvFld1,omitempty"`
	MsgResvFld2          string   `protobuf:"bytes,14,opt,name=msgResvFld2,proto3" json:"msgResvFld2,omitempty"`
	MsgResvFld3          string   `protobuf:"bytes,15,opt,name=msgResvFld3,proto3" json:"msgResvFld3,omitempty"`
	MsgResvFld4          string   `protobuf:"bytes,16,opt,name=msgResvFld4,proto3" json:"msgResvFld4,omitempty"`
	MsgResvFld5          string   `protobuf:"bytes,17,opt,name=msgResvFld5,proto3" json:"msgResvFld5,omitempty"`
	MsgResvFld6          string   `protobuf:"bytes,18,opt,name=msgResvFld6,proto3" json:"msgResvFld6,omitempty"`
	MsgResvFld7          string   `protobuf:"bytes,19,opt,name=msgResvFld7,proto3" json:"msgResvFld7,omitempty"`
	MsgResvFld8          string   `protobuf:"bytes,20,opt,name=msgResvFld8,proto3" json:"msgResvFld8,omitempty"`
	MsgResvFld9          string   `protobuf:"bytes,21,opt,name=msgResvFld9,proto3" json:"msgResvFld9,omitempty"`
	MsgResvFld10         string   `protobuf:"bytes,22,opt,name=msgResvFld10,proto3" json:"msgResvFld10,omitempty"`
	CreatedAt            string   `protobuf:"bytes,23,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt            string   `protobuf:"bytes,24,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MerchantBankAccountField) Reset()         { *m = MerchantBankAccountField{} }
func (m *MerchantBankAccountField) String() string { return proto.CompactTextString(m) }
func (*MerchantBankAccountField) ProtoMessage()    {}
func (*MerchantBankAccountField) Descriptor() ([]byte, []int) {
	return fileDescriptor_87fc684f407252a1, []int{8}
}

func (m *MerchantBankAccountField) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MerchantBankAccountField.Unmarshal(m, b)
}
func (m *MerchantBankAccountField) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MerchantBankAccountField.Marshal(b, m, deterministic)
}
func (m *MerchantBankAccountField) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MerchantBankAccountField.Merge(m, src)
}
func (m *MerchantBankAccountField) XXX_Size() int {
	return xxx_messageInfo_MerchantBankAccountField.Size(m)
}
func (m *MerchantBankAccountField) XXX_DiscardUnknown() {
	xxx_messageInfo_MerchantBankAccountField.DiscardUnknown(m)
}

var xxx_messageInfo_MerchantBankAccountField proto.InternalMessageInfo

func (m *MerchantBankAccountField) GetOwnerCd() string {
	if m != nil {
		return m.OwnerCd
	}
	return ""
}

func (m *MerchantBankAccountField) GetAccountType() string {
	if m != nil {
		return m.AccountType
	}
	return ""
}

func (m *MerchantBankAccountField) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *MerchantBankAccountField) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *MerchantBankAccountField) GetUcBcCd() string {
	if m != nil {
		return m.UcBcCd
	}
	return ""
}

func (m *MerchantBankAccountField) GetProvince() string {
	if m != nil {
		return m.Province
	}
	return ""
}

func (m *MerchantBankAccountField) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

func (m *MerchantBankAccountField) GetBankCode() string {
	if m != nil {
		return m.BankCode
	}
	return ""
}

func (m *MerchantBankAccountField) GetBankName() string {
	if m != nil {
		return m.BankName
	}
	return ""
}

func (m *MerchantBankAccountField) GetOperIn() string {
	if m != nil {
		return m.OperIn
	}
	return ""
}

func (m *MerchantBankAccountField) GetRecOprId() string {
	if m != nil {
		return m.RecOprId
	}
	return ""
}

func (m *MerchantBankAccountField) GetRecUpdOpr() string {
	if m != nil {
		return m.RecUpdOpr
	}
	return ""
}

func (m *MerchantBankAccountField) GetMsgResvFld1() string {
	if m != nil {
		return m.MsgResvFld1
	}
	return ""
}

func (m *MerchantBankAccountField) GetMsgResvFld2() string {
	if m != nil {
		return m.MsgResvFld2
	}
	return ""
}

func (m *MerchantBankAccountField) GetMsgResvFld3() string {
	if m != nil {
		return m.MsgResvFld3
	}
	return ""
}

func (m *MerchantBankAccountField) GetMsgResvFld4() string {
	if m != nil {
		return m.MsgResvFld4
	}
	return ""
}

func (m *MerchantBankAccountField) GetMsgResvFld5() string {
	if m != nil {
		return m.MsgResvFld5
	}
	return ""
}

func (m *MerchantBankAccountField) GetMsgResvFld6() string {
	if m != nil {
		return m.MsgResvFld6
	}
	return ""
}

func (m *MerchantBankAccountField) GetMsgResvFld7() string {
	if m != nil {
		return m.MsgResvFld7
	}
	return ""
}

func (m *MerchantBankAccountField) GetMsgResvFld8() string {
	if m != nil {
		return m.MsgResvFld8
	}
	return ""
}

func (m *MerchantBankAccountField) GetMsgResvFld9() string {
	if m != nil {
		return m.MsgResvFld9
	}
	return ""
}

func (m *MerchantBankAccountField) GetMsgResvFld10() string {
	if m != nil {
		return m.MsgResvFld10
	}
	return ""
}

func (m *MerchantBankAccountField) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *MerchantBankAccountField) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

type SaveMerchantBankAccountRequest struct {
	Item                 *MerchantBankAccountField `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *SaveMerchantBankAccountRequest) Reset()         { *m = SaveMerchantBankAccountRequest{} }
func (m *SaveMerchantBankAccountRequest) String() string { return proto.CompactTextString(m) }
func (*SaveMerchantBankAccountRequest) ProtoMessage()    {}
func (*SaveMerchantBankAccountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_87fc684f407252a1, []int{9}
}

func (m *SaveMerchantBankAccountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SaveMerchantBankAccountRequest.Unmarshal(m, b)
}
func (m *SaveMerchantBankAccountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SaveMerchantBankAccountRequest.Marshal(b, m, deterministic)
}
func (m *SaveMerchantBankAccountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SaveMerchantBankAccountRequest.Merge(m, src)
}
func (m *SaveMerchantBankAccountRequest) XXX_Size() int {
	return xxx_messageInfo_SaveMerchantBankAccountRequest.Size(m)
}
func (m *SaveMerchantBankAccountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SaveMerchantBankAccountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SaveMerchantBankAccountRequest proto.InternalMessageInfo

func (m *SaveMerchantBankAccountRequest) GetItem() *MerchantBankAccountField {
	if m != nil {
		return m.Item
	}
	return nil
}

type SaveMerchantBankAccountReply struct {
	Err                  *Error   `protobuf:"bytes,1,opt,name=err,proto3" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SaveMerchantBankAccountReply) Reset()         { *m = SaveMerchantBankAccountReply{} }
func (m *SaveMerchantBankAccountReply) String() string { return proto.CompactTextString(m) }
func (*SaveMerchantBankAccountReply) ProtoMessage()    {}
func (*SaveMerchantBankAccountReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_87fc684f407252a1, []int{10}
}

func (m *SaveMerchantBankAccountReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SaveMerchantBankAccountReply.Unmarshal(m, b)
}
func (m *SaveMerchantBankAccountReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SaveMerchantBankAccountReply.Marshal(b, m, deterministic)
}
func (m *SaveMerchantBankAccountReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SaveMerchantBankAccountReply.Merge(m, src)
}
func (m *SaveMerchantBankAccountReply) XXX_Size() int {
	return xxx_messageInfo_SaveMerchantBankAccountReply.Size(m)
}
func (m *SaveMerchantBankAccountReply) XXX_DiscardUnknown() {
	xxx_messageInfo_SaveMerchantBankAccountReply.DiscardUnknown(m)
}

var xxx_messageInfo_SaveMerchantBankAccountReply proto.InternalMessageInfo

func (m *SaveMerchantBankAccountReply) GetErr() *Error {
	if m != nil {
		return m.Err
	}
	return nil
}

type MerchantBizDealField struct {
	MchtCd               string   `protobuf:"bytes,1,opt,name=mchtCd,proto3" json:"mchtCd,omitempty"`
	ProdCd               string   `protobuf:"bytes,2,opt,name=prodCd,proto3" json:"prodCd,omitempty"`
	BizCd                string   `protobuf:"bytes,3,opt,name=bizCd,proto3" json:"bizCd,omitempty"`
	TransCd              string   `protobuf:"bytes,4,opt,name=transCd,proto3" json:"transCd,omitempty"`
	OperIn               string   `protobuf:"bytes,5,opt,name=operIn,proto3" json:"operIn,omitempty"`
	RecOprId             string   `protobuf:"bytes,6,opt,name=recOprId,proto3" json:"recOprId,omitempty"`
	RecUpdOpr            string   `protobuf:"bytes,7,opt,name=recUpdOpr,proto3" json:"recUpdOpr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MerchantBizDealField) Reset()         { *m = MerchantBizDealField{} }
func (m *MerchantBizDealField) String() string { return proto.CompactTextString(m) }
func (*MerchantBizDealField) ProtoMessage()    {}
func (*MerchantBizDealField) Descriptor() ([]byte, []int) {
	return fileDescriptor_87fc684f407252a1, []int{11}
}

func (m *MerchantBizDealField) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MerchantBizDealField.Unmarshal(m, b)
}
func (m *MerchantBizDealField) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MerchantBizDealField.Marshal(b, m, deterministic)
}
func (m *MerchantBizDealField) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MerchantBizDealField.Merge(m, src)
}
func (m *MerchantBizDealField) XXX_Size() int {
	return xxx_messageInfo_MerchantBizDealField.Size(m)
}
func (m *MerchantBizDealField) XXX_DiscardUnknown() {
	xxx_messageInfo_MerchantBizDealField.DiscardUnknown(m)
}

var xxx_messageInfo_MerchantBizDealField proto.InternalMessageInfo

func (m *MerchantBizDealField) GetMchtCd() string {
	if m != nil {
		return m.MchtCd
	}
	return ""
}

func (m *MerchantBizDealField) GetProdCd() string {
	if m != nil {
		return m.ProdCd
	}
	return ""
}

func (m *MerchantBizDealField) GetBizCd() string {
	if m != nil {
		return m.BizCd
	}
	return ""
}

func (m *MerchantBizDealField) GetTransCd() string {
	if m != nil {
		return m.TransCd
	}
	return ""
}

func (m *MerchantBizDealField) GetOperIn() string {
	if m != nil {
		return m.OperIn
	}
	return ""
}

func (m *MerchantBizDealField) GetRecOprId() string {
	if m != nil {
		return m.RecOprId
	}
	return ""
}

func (m *MerchantBizDealField) GetRecUpdOpr() string {
	if m != nil {
		return m.RecUpdOpr
	}
	return ""
}

type SaveMerchantBizDealRequest struct {
	Item                 *MerchantBizDealField `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *SaveMerchantBizDealRequest) Reset()         { *m = SaveMerchantBizDealRequest{} }
func (m *SaveMerchantBizDealRequest) String() string { return proto.CompactTextString(m) }
func (*SaveMerchantBizDealRequest) ProtoMessage()    {}
func (*SaveMerchantBizDealRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_87fc684f407252a1, []int{12}
}

func (m *SaveMerchantBizDealRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SaveMerchantBizDealRequest.Unmarshal(m, b)
}
func (m *SaveMerchantBizDealRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SaveMerchantBizDealRequest.Marshal(b, m, deterministic)
}
func (m *SaveMerchantBizDealRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SaveMerchantBizDealRequest.Merge(m, src)
}
func (m *SaveMerchantBizDealRequest) XXX_Size() int {
	return xxx_messageInfo_SaveMerchantBizDealRequest.Size(m)
}
func (m *SaveMerchantBizDealRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SaveMerchantBizDealRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SaveMerchantBizDealRequest proto.InternalMessageInfo

func (m *SaveMerchantBizDealRequest) GetItem() *MerchantBizDealField {
	if m != nil {
		return m.Item
	}
	return nil
}

type SaveMerchantBizDealReply struct {
	Err                  *Error   `protobuf:"bytes,1,opt,name=err,proto3" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SaveMerchantBizDealReply) Reset()         { *m = SaveMerchantBizDealReply{} }
func (m *SaveMerchantBizDealReply) String() string { return proto.CompactTextString(m) }
func (*SaveMerchantBizDealReply) ProtoMessage()    {}
func (*SaveMerchantBizDealReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_87fc684f407252a1, []int{13}
}

func (m *SaveMerchantBizDealReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SaveMerchantBizDealReply.Unmarshal(m, b)
}
func (m *SaveMerchantBizDealReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SaveMerchantBizDealReply.Marshal(b, m, deterministic)
}
func (m *SaveMerchantBizDealReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SaveMerchantBizDealReply.Merge(m, src)
}
func (m *SaveMerchantBizDealReply) XXX_Size() int {
	return xxx_messageInfo_SaveMerchantBizDealReply.Size(m)
}
func (m *SaveMerchantBizDealReply) XXX_DiscardUnknown() {
	xxx_messageInfo_SaveMerchantBizDealReply.DiscardUnknown(m)
}

var xxx_messageInfo_SaveMerchantBizDealReply proto.InternalMessageInfo

func (m *SaveMerchantBizDealReply) GetErr() *Error {
	if m != nil {
		return m.Err
	}
	return nil
}

type MerchantBizFeeField struct {
	MchtCd               string   `protobuf:"bytes,1,opt,name=mchtCd,proto3" json:"mchtCd,omitempty"`
	ProdCd               string   `protobuf:"bytes,2,opt,name=prodCd,proto3" json:"prodCd,omitempty"`
	BizCd                string   `protobuf:"bytes,3,opt,name=bizCd,proto3" json:"bizCd,omitempty"`
	SubBizCd             string   `protobuf:"bytes,4,opt,name=subBizCd,proto3" json:"subBizCd,omitempty"`
	MchtFeeMd            string   `protobuf:"bytes,5,opt,name=mchtFeeMd,proto3" json:"mchtFeeMd,omitempty"`
	MchtFeePercent       float64  `protobuf:"fixed64,6,opt,name=mchtFeePercent,proto3" json:"mchtFeePercent,omitempty"`
	MchtFeePctMin        float64  `protobuf:"fixed64,7,opt,name=mchtFeePctMin,proto3" json:"mchtFeePctMin,omitempty"`
	MchtFeePctMax        float64  `protobuf:"fixed64,8,opt,name=mchtFeePctMax,proto3" json:"mchtFeePctMax,omitempty"`
	MchtFeeSingle        float64  `protobuf:"fixed64,9,opt,name=mchtFeeSingle,proto3" json:"mchtFeeSingle,omitempty"`
	MchtAFeeSame         string   `protobuf:"bytes,10,opt,name=mchtAFeeSame,proto3" json:"mchtAFeeSame,omitempty"`
	MchtAFeeMd           string   `protobuf:"bytes,11,opt,name=mchtAFeeMd,proto3" json:"mchtAFeeMd,omitempty"`
	MchtAFeePercent      float64  `protobuf:"fixed64,12,opt,name=mchtAFeePercent,proto3" json:"mchtAFeePercent,omitempty"`
	MchtAFeePctMin       float64  `protobuf:"fixed64,13,opt,name=mchtAFeePctMin,proto3" json:"mchtAFeePctMin,omitempty"`
	MchtAFeePctMax       float64  `protobuf:"fixed64,14,opt,name=mchtAFeePctMax,proto3" json:"mchtAFeePctMax,omitempty"`
	MchtAFeeSingle       float64  `protobuf:"fixed64,15,opt,name=mchtAFeeSingle,proto3" json:"mchtAFeeSingle,omitempty"`
	OperIn               string   `protobuf:"bytes,16,opt,name=operIn,proto3" json:"operIn,omitempty"`
	RecOprId             string   `protobuf:"bytes,17,opt,name=recOprId,proto3" json:"recOprId,omitempty"`
	RecUpdOpr            string   `protobuf:"bytes,18,opt,name=recUpdOpr,proto3" json:"recUpdOpr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MerchantBizFeeField) Reset()         { *m = MerchantBizFeeField{} }
func (m *MerchantBizFeeField) String() string { return proto.CompactTextString(m) }
func (*MerchantBizFeeField) ProtoMessage()    {}
func (*MerchantBizFeeField) Descriptor() ([]byte, []int) {
	return fileDescriptor_87fc684f407252a1, []int{14}
}

func (m *MerchantBizFeeField) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MerchantBizFeeField.Unmarshal(m, b)
}
func (m *MerchantBizFeeField) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MerchantBizFeeField.Marshal(b, m, deterministic)
}
func (m *MerchantBizFeeField) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MerchantBizFeeField.Merge(m, src)
}
func (m *MerchantBizFeeField) XXX_Size() int {
	return xxx_messageInfo_MerchantBizFeeField.Size(m)
}
func (m *MerchantBizFeeField) XXX_DiscardUnknown() {
	xxx_messageInfo_MerchantBizFeeField.DiscardUnknown(m)
}

var xxx_messageInfo_MerchantBizFeeField proto.InternalMessageInfo

func (m *MerchantBizFeeField) GetMchtCd() string {
	if m != nil {
		return m.MchtCd
	}
	return ""
}

func (m *MerchantBizFeeField) GetProdCd() string {
	if m != nil {
		return m.ProdCd
	}
	return ""
}

func (m *MerchantBizFeeField) GetBizCd() string {
	if m != nil {
		return m.BizCd
	}
	return ""
}

func (m *MerchantBizFeeField) GetSubBizCd() string {
	if m != nil {
		return m.SubBizCd
	}
	return ""
}

func (m *MerchantBizFeeField) GetMchtFeeMd() string {
	if m != nil {
		return m.MchtFeeMd
	}
	return ""
}

func (m *MerchantBizFeeField) GetMchtFeePercent() float64 {
	if m != nil {
		return m.MchtFeePercent
	}
	return 0
}

func (m *MerchantBizFeeField) GetMchtFeePctMin() float64 {
	if m != nil {
		return m.MchtFeePctMin
	}
	return 0
}

func (m *MerchantBizFeeField) GetMchtFeePctMax() float64 {
	if m != nil {
		return m.MchtFeePctMax
	}
	return 0
}

func (m *MerchantBizFeeField) GetMchtFeeSingle() float64 {
	if m != nil {
		return m.MchtFeeSingle
	}
	return 0
}

func (m *MerchantBizFeeField) GetMchtAFeeSame() string {
	if m != nil {
		return m.MchtAFeeSame
	}
	return ""
}

func (m *MerchantBizFeeField) GetMchtAFeeMd() string {
	if m != nil {
		return m.MchtAFeeMd
	}
	return ""
}

func (m *MerchantBizFeeField) GetMchtAFeePercent() float64 {
	if m != nil {
		return m.MchtAFeePercent
	}
	return 0
}

func (m *MerchantBizFeeField) GetMchtAFeePctMin() float64 {
	if m != nil {
		return m.MchtAFeePctMin
	}
	return 0
}

func (m *MerchantBizFeeField) GetMchtAFeePctMax() float64 {
	if m != nil {
		return m.MchtAFeePctMax
	}
	return 0
}

func (m *MerchantBizFeeField) GetMchtAFeeSingle() float64 {
	if m != nil {
		return m.MchtAFeeSingle
	}
	return 0
}

func (m *MerchantBizFeeField) GetOperIn() string {
	if m != nil {
		return m.OperIn
	}
	return ""
}

func (m *MerchantBizFeeField) GetRecOprId() string {
	if m != nil {
		return m.RecOprId
	}
	return ""
}

func (m *MerchantBizFeeField) GetRecUpdOpr() string {
	if m != nil {
		return m.RecUpdOpr
	}
	return ""
}

type MerchantBusinessField struct {
	MchtCd                 string   `protobuf:"bytes,1,opt,name=mchtCd,proto3" json:"mchtCd,omitempty"`
	ProdCd                 string   `protobuf:"bytes,2,opt,name=prodCd,proto3" json:"prodCd,omitempty"`
	ProdCdText             string   `protobuf:"bytes,3,opt,name=prodCdText,proto3" json:"prodCdText,omitempty"`
	FeeMoneyCd             string   `protobuf:"bytes,4,opt,name=feeMoneyCd,proto3" json:"feeMoneyCd,omitempty"`
	FeeModeType            string   `protobuf:"bytes,5,opt,name=feeModeType,proto3" json:"feeModeType,omitempty"`
	FeeSettlementType      string   `protobuf:"bytes,6,opt,name=feeSettlementType,proto3" json:"feeSettlementType,omitempty"`
	FeeHoliday             string   `protobuf:"bytes,7,opt,name=feeHoliday,proto3" json:"feeHoliday,omitempty"`
	ServiceFeeType         string   `protobuf:"bytes,8,opt,name=serviceFeeType,proto3" json:"serviceFeeType,omitempty"`
	ServiceFeeStaticAmount float64  `protobuf:"fixed64,9,opt,name=serviceFeeStaticAmount,proto3" json:"serviceFeeStaticAmount,omitempty"`
	ServiceFeeLevelCount   int64    `protobuf:"varint,10,opt,name=serviceFeeLevelCount,proto3" json:"serviceFeeLevelCount,omitempty"`
	ServiceFeeMode         string   `protobuf:"bytes,11,opt,name=serviceFeeMode,proto3" json:"serviceFeeMode,omitempty"`
	ServiceFeeUnit         string   `protobuf:"bytes,12,opt,name=serviceFeeUnit,proto3" json:"serviceFeeUnit,omitempty"`
	ServiceFeeTerm         string   `protobuf:"bytes,13,opt,name=serviceFeeTerm,proto3" json:"serviceFeeTerm,omitempty"`
	ServiceFeeSumto        string   `protobuf:"bytes,14,opt,name=serviceFeeSumto,proto3" json:"serviceFeeSumto,omitempty"`
	ServiceFeeCircle       string   `protobuf:"bytes,15,opt,name=serviceFeeCircle,proto3" json:"serviceFeeCircle,omitempty"`
	ServiceFeeOthers       string   `protobuf:"bytes,16,opt,name=serviceFeeOthers,proto3" json:"serviceFeeOthers,omitempty"`
	ServiceFeeStart        string   `protobuf:"bytes,17,opt,name=serviceFeeStart,proto3" json:"serviceFeeStart,omitempty"`
	ServiceFeeClct         string   `protobuf:"bytes,18,opt,name=serviceFeeClct,proto3" json:"serviceFeeClct,omitempty"`
	ServiceFeeClctOthers   string   `protobuf:"bytes,19,opt,name=serviceFeeClctOthers,proto3" json:"serviceFeeClctOthers,omitempty"`
	SystemFlag             string   `protobuf:"bytes,20,opt,name=systemFlag,proto3" json:"systemFlag,omitempty"`
	Ext1                   string   `protobuf:"bytes,21,opt,name=ext1,proto3" json:"ext1,omitempty"`
	Ext2                   string   `protobuf:"bytes,22,opt,name=ext2,proto3" json:"ext2,omitempty"`
	Ext3                   string   `protobuf:"bytes,23,opt,name=ext3,proto3" json:"ext3,omitempty"`
	Ext4                   string   `protobuf:"bytes,24,opt,name=ext4,proto3" json:"ext4,omitempty"`
	ServiceFeeYesNo        string   `protobuf:"bytes,25,opt,name=serviceFeeYesNo,proto3" json:"serviceFeeYesNo,omitempty"`
	RecOprId               string   `protobuf:"bytes,26,opt,name=recOprId,proto3" json:"recOprId,omitempty"`
	RecUpdOpr              string   `protobuf:"bytes,27,opt,name=recUpdOpr,proto3" json:"recUpdOpr,omitempty"`
	OperIn                 string   `protobuf:"bytes,28,opt,name=operIn,proto3" json:"operIn,omitempty"`
	XXX_NoUnkeyedLiteral   struct{} `json:"-"`
	XXX_unrecognized       []byte   `json:"-"`
	XXX_sizecache          int32    `json:"-"`
}

func (m *MerchantBusinessField) Reset()         { *m = MerchantBusinessField{} }
func (m *MerchantBusinessField) String() string { return proto.CompactTextString(m) }
func (*MerchantBusinessField) ProtoMessage()    {}
func (*MerchantBusinessField) Descriptor() ([]byte, []int) {
	return fileDescriptor_87fc684f407252a1, []int{15}
}

func (m *MerchantBusinessField) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MerchantBusinessField.Unmarshal(m, b)
}
func (m *MerchantBusinessField) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MerchantBusinessField.Marshal(b, m, deterministic)
}
func (m *MerchantBusinessField) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MerchantBusinessField.Merge(m, src)
}
func (m *MerchantBusinessField) XXX_Size() int {
	return xxx_messageInfo_MerchantBusinessField.Size(m)
}
func (m *MerchantBusinessField) XXX_DiscardUnknown() {
	xxx_messageInfo_MerchantBusinessField.DiscardUnknown(m)
}

var xxx_messageInfo_MerchantBusinessField proto.InternalMessageInfo

func (m *MerchantBusinessField) GetMchtCd() string {
	if m != nil {
		return m.MchtCd
	}
	return ""
}

func (m *MerchantBusinessField) GetProdCd() string {
	if m != nil {
		return m.ProdCd
	}
	return ""
}

func (m *MerchantBusinessField) GetProdCdText() string {
	if m != nil {
		return m.ProdCdText
	}
	return ""
}

func (m *MerchantBusinessField) GetFeeMoneyCd() string {
	if m != nil {
		return m.FeeMoneyCd
	}
	return ""
}

func (m *MerchantBusinessField) GetFeeModeType() string {
	if m != nil {
		return m.FeeModeType
	}
	return ""
}

func (m *MerchantBusinessField) GetFeeSettlementType() string {
	if m != nil {
		return m.FeeSettlementType
	}
	return ""
}

func (m *MerchantBusinessField) GetFeeHoliday() string {
	if m != nil {
		return m.FeeHoliday
	}
	return ""
}

func (m *MerchantBusinessField) GetServiceFeeType() string {
	if m != nil {
		return m.ServiceFeeType
	}
	return ""
}

func (m *MerchantBusinessField) GetServiceFeeStaticAmount() float64 {
	if m != nil {
		return m.ServiceFeeStaticAmount
	}
	return 0
}

func (m *MerchantBusinessField) GetServiceFeeLevelCount() int64 {
	if m != nil {
		return m.ServiceFeeLevelCount
	}
	return 0
}

func (m *MerchantBusinessField) GetServiceFeeMode() string {
	if m != nil {
		return m.ServiceFeeMode
	}
	return ""
}

func (m *MerchantBusinessField) GetServiceFeeUnit() string {
	if m != nil {
		return m.ServiceFeeUnit
	}
	return ""
}

func (m *MerchantBusinessField) GetServiceFeeTerm() string {
	if m != nil {
		return m.ServiceFeeTerm
	}
	return ""
}

func (m *MerchantBusinessField) GetServiceFeeSumto() string {
	if m != nil {
		return m.ServiceFeeSumto
	}
	return ""
}

func (m *MerchantBusinessField) GetServiceFeeCircle() string {
	if m != nil {
		return m.ServiceFeeCircle
	}
	return ""
}

func (m *MerchantBusinessField) GetServiceFeeOthers() string {
	if m != nil {
		return m.ServiceFeeOthers
	}
	return ""
}

func (m *MerchantBusinessField) GetServiceFeeStart() string {
	if m != nil {
		return m.ServiceFeeStart
	}
	return ""
}

func (m *MerchantBusinessField) GetServiceFeeClct() string {
	if m != nil {
		return m.ServiceFeeClct
	}
	return ""
}

func (m *MerchantBusinessField) GetServiceFeeClctOthers() string {
	if m != nil {
		return m.ServiceFeeClctOthers
	}
	return ""
}

func (m *MerchantBusinessField) GetSystemFlag() string {
	if m != nil {
		return m.SystemFlag
	}
	return ""
}

func (m *MerchantBusinessField) GetExt1() string {
	if m != nil {
		return m.Ext1
	}
	return ""
}

func (m *MerchantBusinessField) GetExt2() string {
	if m != nil {
		return m.Ext2
	}
	return ""
}

func (m *MerchantBusinessField) GetExt3() string {
	if m != nil {
		return m.Ext3
	}
	return ""
}

func (m *MerchantBusinessField) GetExt4() string {
	if m != nil {
		return m.Ext4
	}
	return ""
}

func (m *MerchantBusinessField) GetServiceFeeYesNo() string {
	if m != nil {
		return m.ServiceFeeYesNo
	}
	return ""
}

func (m *MerchantBusinessField) GetRecOprId() string {
	if m != nil {
		return m.RecOprId
	}
	return ""
}

func (m *MerchantBusinessField) GetRecUpdOpr() string {
	if m != nil {
		return m.RecUpdOpr
	}
	return ""
}

func (m *MerchantBusinessField) GetOperIn() string {
	if m != nil {
		return m.OperIn
	}
	return ""
}

type MerchantPictureField struct {
	FileId               string   `protobuf:"bytes,1,opt,name=FileId,proto3" json:"FileId,omitempty"`
	MchtCd               string   `protobuf:"bytes,2,opt,name=MchtCd,proto3" json:"MchtCd,omitempty"`
	DocType              string   `protobuf:"bytes,3,opt,name=DocType,proto3" json:"DocType,omitempty"`
	FileType             string   `protobuf:"bytes,4,opt,name=FileType,proto3" json:"FileType,omitempty"`
	FileName             string   `protobuf:"bytes,5,opt,name=FileName,proto3" json:"FileName,omitempty"`
	PIndex               int64    `protobuf:"varint,6,opt,name=PIndex,proto3" json:"PIndex,omitempty"`
	PCode                string   `protobuf:"bytes,7,opt,name=PCode,proto3" json:"PCode,omitempty"`
	Url                  string   `protobuf:"bytes,8,opt,name=Url,proto3" json:"Url,omitempty"`
	SystemFlag           string   `protobuf:"bytes,9,opt,name=SystemFlag,proto3" json:"SystemFlag,omitempty"`
	Status               string   `protobuf:"bytes,10,opt,name=Status,proto3" json:"Status,omitempty"`
	RecOprId             string   `protobuf:"bytes,11,opt,name=RecOprId,proto3" json:"RecOprId,omitempty"`
	RecUpdOpr            string   `protobuf:"bytes,12,opt,name=RecUpdOpr,proto3" json:"RecUpdOpr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MerchantPictureField) Reset()         { *m = MerchantPictureField{} }
func (m *MerchantPictureField) String() string { return proto.CompactTextString(m) }
func (*MerchantPictureField) ProtoMessage()    {}
func (*MerchantPictureField) Descriptor() ([]byte, []int) {
	return fileDescriptor_87fc684f407252a1, []int{16}
}

func (m *MerchantPictureField) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MerchantPictureField.Unmarshal(m, b)
}
func (m *MerchantPictureField) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MerchantPictureField.Marshal(b, m, deterministic)
}
func (m *MerchantPictureField) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MerchantPictureField.Merge(m, src)
}
func (m *MerchantPictureField) XXX_Size() int {
	return xxx_messageInfo_MerchantPictureField.Size(m)
}
func (m *MerchantPictureField) XXX_DiscardUnknown() {
	xxx_messageInfo_MerchantPictureField.DiscardUnknown(m)
}

var xxx_messageInfo_MerchantPictureField proto.InternalMessageInfo

func (m *MerchantPictureField) GetFileId() string {
	if m != nil {
		return m.FileId
	}
	return ""
}

func (m *MerchantPictureField) GetMchtCd() string {
	if m != nil {
		return m.MchtCd
	}
	return ""
}

func (m *MerchantPictureField) GetDocType() string {
	if m != nil {
		return m.DocType
	}
	return ""
}

func (m *MerchantPictureField) GetFileType() string {
	if m != nil {
		return m.FileType
	}
	return ""
}

func (m *MerchantPictureField) GetFileName() string {
	if m != nil {
		return m.FileName
	}
	return ""
}

func (m *MerchantPictureField) GetPIndex() int64 {
	if m != nil {
		return m.PIndex
	}
	return 0
}

func (m *MerchantPictureField) GetPCode() string {
	if m != nil {
		return m.PCode
	}
	return ""
}

func (m *MerchantPictureField) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *MerchantPictureField) GetSystemFlag() string {
	if m != nil {
		return m.SystemFlag
	}
	return ""
}

func (m *MerchantPictureField) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *MerchantPictureField) GetRecOprId() string {
	if m != nil {
		return m.RecOprId
	}
	return ""
}

func (m *MerchantPictureField) GetRecUpdOpr() string {
	if m != nil {
		return m.RecUpdOpr
	}
	return ""
}

func init() {
	proto.RegisterType((*ListMerchantRequest)(nil), "pb.ListMerchantRequest")
	proto.RegisterType((*ListMerchantReply)(nil), "pb.ListMerchantReply")
	proto.RegisterType((*MerchantField)(nil), "pb.MerchantField")
	proto.RegisterType((*MerchantGroupField)(nil), "pb.MerchantGroupField")
	proto.RegisterType((*ListGroupMerchantRequest)(nil), "pb.ListGroupMerchantRequest")
	proto.RegisterType((*ListGroupMerchantReply)(nil), "pb.ListGroupMerchantReply")
	proto.RegisterType((*SaveMerchantRequest)(nil), "pb.SaveMerchantRequest")
	proto.RegisterType((*SaveMerchantReply)(nil), "pb.SaveMerchantReply")
	proto.RegisterType((*MerchantBankAccountField)(nil), "pb.MerchantBankAccountField")
	proto.RegisterType((*SaveMerchantBankAccountRequest)(nil), "pb.SaveMerchantBankAccountRequest")
	proto.RegisterType((*SaveMerchantBankAccountReply)(nil), "pb.SaveMerchantBankAccountReply")
	proto.RegisterType((*MerchantBizDealField)(nil), "pb.MerchantBizDealField")
	proto.RegisterType((*SaveMerchantBizDealRequest)(nil), "pb.SaveMerchantBizDealRequest")
	proto.RegisterType((*SaveMerchantBizDealReply)(nil), "pb.SaveMerchantBizDealReply")
	proto.RegisterType((*MerchantBizFeeField)(nil), "pb.MerchantBizFeeField")
	proto.RegisterType((*MerchantBusinessField)(nil), "pb.MerchantBusinessField")
	proto.RegisterType((*MerchantPictureField)(nil), "pb.MerchantPictureField")
}

func init() { proto.RegisterFile("merchant.proto", fileDescriptor_87fc684f407252a1) }

var fileDescriptor_87fc684f407252a1 = []byte{
	// 2264 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x59, 0xdd, 0x52, 0x1b, 0xc9,
	0x15, 0x5e, 0xf1, 0x63, 0x50, 0x83, 0x6d, 0x18, 0xdb, 0xb8, 0xa3, 0x25, 0x0e, 0x51, 0xf6, 0x87,
	0x38, 0x8e, 0x63, 0x03, 0x06, 0x9c, 0xdd, 0x24, 0x16, 0x62, 0x49, 0x94, 0x32, 0x3f, 0x25, 0x41,
	0x6d, 0xe5, 0xb2, 0x99, 0x69, 0xc4, 0x2c, 0xa3, 0x99, 0x49, 0x4f, 0x8b, 0x45, 0xbe, 0xcc, 0x4b,
	0xa4, 0x72, 0x99, 0x97, 0xc8, 0x33, 0xa4, 0xf2, 0x12, 0xb9, 0x4c, 0xde, 0x20, 0xb7, 0xa9, 0xd3,
	0xe7, 0xcc, 0x4c, 0xf7, 0x48, 0xb0, 0x55, 0x5b, 0xc9, 0x15, 0xf3, 0x7d, 0xe7, 0xf4, 0xdf, 0xe9,
	0xf3, 0xd7, 0x82, 0x3d, 0x18, 0x48, 0xe5, 0x5f, 0x8a, 0x58, 0xbf, 0x4c, 0x55, 0xa2, 0x13, 0x6f,
	0x2a, 0x3d, 0x6f, 0x2c, 0x48, 0xa5, 0x12, 0x85, 0x44, 0xf3, 0x86, 0x3d, 0x7a, 0x1f, 0x66, 0xfa,
	0x90, 0xd4, 0xba, 0xf2, 0x8f, 0x43, 0x99, 0x69, 0xcf, 0x63, 0x33, 0xa9, 0xe8, 0x4b, 0x5e, 0x5b,
	0xab, 0xad, 0xcf, 0x76, 0xcd, 0x37, 0x70, 0x59, 0xf8, 0x41, 0xf2, 0x29, 0xe4, 0xe0, 0xdb, 0xfb,
	0x94, 0xcd, 0x84, 0x5a, 0x0e, 0xf8, 0xf4, 0x5a, 0x6d, 0x7d, 0x61, 0x63, 0xf9, 0x65, 0x7a, 0xfe,
	0x32, 0x9f, 0xea, 0x20, 0x94, 0x51, 0xd0, 0x35, 0x62, 0x18, 0xaa, 0x47, 0xa9, 0xe4, 0x33, 0x6b,
	0xb5, 0xf5, 0x7a, 0xd7, 0x7c, 0x37, 0xff, 0x5c, 0x63, 0xcb, 0xee, 0xd2, 0x69, 0x34, 0xf2, 0x3e,
	0x67, 0xb3, 0x30, 0x22, 0xe3, 0xb5, 0xb5, 0xe9, 0xc9, 0x33, 0xa2, 0xdc, 0x7b, 0xcc, 0x66, 0xfd,
	0x64, 0x18, 0x6b, 0xda, 0x0e, 0x82, 0x62, 0x8f, 0xd3, 0xd6, 0x1e, 0xf3, 0xb3, 0xcc, 0x58, 0x67,
	0xf9, 0x98, 0x4d, 0x4b, 0xa5, 0xf8, 0xac, 0xd9, 0x76, 0x1d, 0x16, 0x31, 0x46, 0xe9, 0x02, 0xdb,
	0xfc, 0xe7, 0x43, 0x76, 0xdf, 0x59, 0xd3, 0x5b, 0x61, 0xf7, 0x06, 0xfe, 0xa5, 0x6e, 0x07, 0xc6,
	0x20, 0xf5, 0x2e, 0x21, 0xef, 0x01, 0x9b, 0xca, 0x62, 0xb3, 0x83, 0x7a, 0x77, 0x2a, 0x8b, 0xbd,
	0x55, 0x56, 0x17, 0x61, 0xba, 0xa7, 0x44, 0xdc, 0x0e, 0xcc, 0x1e, 0xea, 0xdd, 0x92, 0xf0, 0x38,
	0x9b, 0xeb, 0xab, 0x64, 0x98, 0xb6, 0x03, 0x32, 0x44, 0x0e, 0x41, 0x92, 0xa8, 0xb0, 0x7d, 0x19,
	0x47, 0x66, 0x4b, 0xf5, 0x6e, 0x0e, 0xbd, 0x35, 0xb6, 0x40, 0x9f, 0xfb, 0x32, 0xf3, 0xf9, 0x3d,
	0x23, 0xb5, 0x29, 0xaf, 0xc9, 0x16, 0xcf, 0x45, 0x7c, 0xb5, 0x27, 0xa3, 0x24, 0xee, 0xb7, 0x03,
	0x3e, 0x67, 0x54, 0x1c, 0x0e, 0x8c, 0x15, 0x5c, 0xa7, 0x7b, 0x23, 0x3e, 0x6f, 0x84, 0x08, 0x60,
	0xd5, 0x81, 0xef, 0xb7, 0x83, 0xd7, 0xbb, 0xbc, 0x8e, 0xab, 0x12, 0xf4, 0x1a, 0x6c, 0x5e, 0xa4,
	0x69, 0xb4, 0x2f, 0xb4, 0xe4, 0xcc, 0x88, 0x0a, 0x0c, 0xb6, 0x18, 0xa6, 0x7b, 0x7e, 0x3b, 0xe0,
	0x0b, 0x68, 0x0b, 0x44, 0xc8, 0xb7, 0x80, 0x5f, 0xcc, 0x79, 0x40, 0xb0, 0xca, 0x30, 0x3d, 0x84,
	0x89, 0xf9, 0x7d, 0x5c, 0x85, 0x20, 0x5c, 0x4c, 0x2c, 0x06, 0x92, 0x3f, 0x40, 0xaf, 0x80, 0x6f,
	0x58, 0x19, 0xfe, 0xee, 0x0d, 0xb3, 0x90, 0x3f, 0xc4, 0x95, 0x73, 0xec, 0x3d, 0x63, 0xec, 0x7c,
	0x98, 0x85, 0xef, 0x43, 0x5f, 0x1e, 0x25, 0x7c, 0xc9, 0x48, 0x2d, 0x06, 0xc6, 0x02, 0xea, 0x8a,
	0xb8, 0xcf, 0x97, 0x71, 0x6c, 0x8e, 0x73, 0xd9, 0xa1, 0x08, 0x63, 0xee, 0x95, 0x32, 0xc0, 0xb0,
	0x73, 0x5f, 0x2a, 0x1d, 0x5e, 0xf0, 0x47, 0xb8, 0x73, 0x44, 0xb0, 0x1e, 0x7e, 0x9d, 0x82, 0xef,
	0x3e, 0xc6, 0xf5, 0x4a, 0x06, 0xe6, 0x44, 0x74, 0x94, 0xf0, 0x27, 0x38, 0x67, 0x8e, 0xcd, 0x9c,
	0xa1, 0x1e, 0xb5, 0x03, 0xbe, 0x42, 0x73, 0x1a, 0x04, 0xbc, 0x50, 0x52, 0xb4, 0x03, 0xfe, 0x14,
	0x79, 0x44, 0x60, 0x25, 0x25, 0xfb, 0xad, 0x20, 0x50, 0x9c, 0xa3, 0x95, 0x08, 0x82, 0x07, 0xf8,
	0x49, 0xac, 0x85, 0xaf, 0x8f, 0xc0, 0x58, 0x3f, 0x40, 0x0f, 0xb0, 0x28, 0xef, 0x33, 0xf6, 0x80,
	0xe0, 0xc9, 0x65, 0x12, 0x83, 0x6d, 0x1a, 0x46, 0xa9, 0xc2, 0xc2, 0x1a, 0x61, 0xf6, 0x5b, 0x70,
	0x39, 0xfe, 0x31, 0xae, 0x41, 0x10, 0x7c, 0x68, 0x90, 0xc4, 0x72, 0x74, 0x9a, 0xa0, 0x78, 0x15,
	0x7d, 0xc8, 0xe6, 0x60, 0x74, 0xa6, 0xa3, 0xc1, 0xd7, 0x62, 0xc4, 0x7f, 0x88, 0xa3, 0x09, 0xc2,
	0x0e, 0xe9, 0xd3, 0xf8, 0xe8, 0x33, 0xdc, 0xa1, 0x45, 0x79, 0x9f, 0xb0, 0xfb, 0x00, 0x3b, 0x71,
	0xd6, 0x0e, 0x95, 0x1f, 0x49, 0xfe, 0x23, 0xa3, 0xe3, 0x92, 0xe4, 0x75, 0xca, 0x78, 0xdd, 0x5a,
	0xe1, 0x75, 0x2a, 0xf7, 0xba, 0x4c, 0x0b, 0x3d, 0xcc, 0xf8, 0x8f, 0xd1, 0x6e, 0x88, 0xe0, 0x8e,
	0x02, 0x19, 0x49, 0x2d, 0xcd, 0xa8, 0x26, 0xde, 0x51, 0xc9, 0xc0, 0x9c, 0x43, 0x1f, 0xfc, 0x73,
	0x73, 0x83, 0xff, 0x04, 0xe7, 0xcc, 0x31, 0x9c, 0xfa, 0x6a, 0xe3, 0xeb, 0x44, 0x5d, 0x5d, 0x44,
	0xc9, 0xb7, 0x9d, 0x80, 0x7f, 0x82, 0xa7, 0xb6, 0x39, 0x98, 0x3f, 0x1b, 0x65, 0x5a, 0x0e, 0x0e,
	0x22, 0xd1, 0xe7, 0x9f, 0xe2, 0xfc, 0x25, 0xe3, 0x3d, 0x67, 0x4b, 0xb0, 0xc7, 0xe4, 0x5a, 0x44,
	0x67, 0x99, 0x54, 0xc6, 0x9f, 0x3f, 0x33, 0x5a, 0x63, 0xbc, 0xb7, 0xc5, 0x9e, 0x5c, 0x84, 0xb1,
	0x88, 0x5a, 0xd5, 0x01, 0x9f, 0x9b, 0x01, 0x93, 0x85, 0xb0, 0xcb, 0x30, 0x3b, 0x4b, 0x7b, 0x5a,
	0xc4, 0x81, 0x50, 0x01, 0x5f, 0xc7, 0x5d, 0xda, 0x1c, 0xdc, 0xc0, 0x79, 0x18, 0x45, 0x61, 0xdc,
	0x37, 0xae, 0xfa, 0x53, 0xbc, 0x01, 0x8b, 0x32, 0x59, 0x02, 0xe1, 0x7b, 0x79, 0x2d, 0x23, 0xfe,
	0x9c, 0xb2, 0x84, 0xc5, 0x19, 0x1b, 0x47, 0x49, 0x5f, 0xc4, 0xfc, 0x67, 0x64, 0x63, 0x83, 0x20,
	0x4e, 0xe5, 0x8d, 0x7e, 0xcd, 0x5f, 0x60, 0x9c, 0xc2, 0x37, 0x71, 0x1b, 0xfc, 0xe7, 0x05, 0xb7,
	0x41, 0xdc, 0x26, 0x7f, 0x59, 0x70, 0x9b, 0xc4, 0x6d, 0xf1, 0x5f, 0x14, 0xdc, 0x16, 0xec, 0x05,
	0xbc, 0xbe, 0x38, 0xd1, 0x2b, 0xdc, 0x8b, 0xcd, 0x19, 0x8f, 0x34, 0x39, 0xb6, 0x85, 0xd1, 0xf2,
	0x9a, 0x3c, 0xd2, 0xe2, 0xe0, 0x6e, 0xf0, 0x2e, 0x01, 0xf3, 0x0d, 0xbc, 0x9b, 0x92, 0x81, 0xbb,
	0x57, 0xd2, 0x3f, 0x4e, 0x55, 0x27, 0xe0, 0x9b, 0x78, 0xf7, 0x39, 0x86, 0x4c, 0xad, 0xa4, 0x7f,
	0x96, 0x06, 0xc7, 0xa9, 0xe2, 0x5b, 0x98, 0xa9, 0x0b, 0x82, 0x46, 0xb6, 0x95, 0x3e, 0xcd, 0xf8,
	0x9b, 0x62, 0xa4, 0xc1, 0x24, 0x3b, 0x4b, 0x83, 0xd3, 0x8c, 0x6f, 0x17, 0x32, 0x83, 0xc1, 0x82,
	0x49, 0x2a, 0x55, 0x27, 0xe6, 0x3b, 0x68, 0x41, 0x44, 0xb0, 0x53, 0x25, 0xfd, 0x56, 0x1a, 0x45,
	0xa3, 0xd3, 0x8c, 0xef, 0xe2, 0x4e, 0x4b, 0x06, 0xe4, 0x89, 0x1c, 0x1c, 0xab, 0x7e, 0x3b, 0x09,
	0x24, 0x7f, 0x8b, 0xf2, 0x92, 0x41, 0x1f, 0xf8, 0x2a, 0x92, 0x9d, 0xf8, 0x3a, 0x09, 0x7d, 0xc9,
	0x7f, 0x99, 0xfb, 0x40, 0xc9, 0x41, 0x8c, 0x05, 0x43, 0x3d, 0x3a, 0x11, 0x4a, 0xf4, 0x95, 0x48,
	0x2f, 0xf9, 0x17, 0x18, 0x63, 0x0e, 0xe9, 0xad, 0xb3, 0x87, 0x5a, 0xdc, 0x1c, 0x0a, 0xff, 0x32,
	0x8c, 0x25, 0xd4, 0xa5, 0x80, 0x7f, 0x69, 0xf4, 0xaa, 0x34, 0xdd, 0xdc, 0x1b, 0xfe, 0xab, 0xe2,
	0xe6, 0xde, 0x10, 0xb7, 0xcd, 0x7f, 0x5d, 0x70, 0xdb, 0xc4, 0xed, 0xf0, 0xdf, 0x14, 0xdc, 0x0e,
	0x71, 0xbb, 0xfc, 0x5d, 0xc1, 0xed, 0x12, 0xf7, 0x96, 0xb7, 0x0a, 0xee, 0xad, 0x9d, 0xd1, 0x7b,
	0x9a, 0xef, 0xb9, 0x19, 0xbd, 0xa7, 0x6d, 0xf9, 0xbe, 0xe6, 0x6d, 0x57, 0xbe, 0xaf, 0xcb, 0x0c,
	0xdc, 0xd3, 0x7c, 0xdf, 0xce, 0xc0, 0x3d, 0x4b, 0xb6, 0xaf, 0xf9, 0x57, 0xb6, 0x6c, 0x5f, 0x37,
	0xff, 0x36, 0xc3, 0xbc, 0xbc, 0xc2, 0x9b, 0xec, 0x86, 0x65, 0xbe, 0xc1, 0xe6, 0xbf, 0xd1, 0x87,
	0x76, 0xa1, 0x2f, 0x70, 0x29, 0x3b, 0x1a, 0x50, 0xc1, 0x2f, 0x30, 0x5c, 0xfb, 0x37, 0xda, 0x38,
	0x21, 0xd6, 0x7c, 0x42, 0x10, 0x96, 0xe0, 0xb0, 0x3d, 0x1d, 0x0d, 0xda, 0x47, 0x03, 0x2a, 0xfa,
	0x36, 0x05, 0x97, 0x56, 0xc0, 0x96, 0xef, 0x6b, 0x2a, 0xff, 0x2e, 0x69, 0x12, 0x3c, 0xe2, 0x4e,
	0x9c, 0x75, 0x82, 0x76, 0x40, 0x7d, 0x40, 0x85, 0xb5, 0x67, 0xeb, 0xc4, 0xd9, 0xd1, 0x80, 0x7a,
	0x01, 0x97, 0x84, 0xd9, 0x80, 0x38, 0x11, 0xa3, 0xde, 0x28, 0x33, 0x8b, 0x62, 0x57, 0x50, 0x61,
	0xe1, 0x54, 0x90, 0x8a, 0xda, 0x01, 0x75, 0x07, 0x84, 0xac, 0xd2, 0xc6, 0x9c, 0xd2, 0xe6, 0x34,
	0x3f, 0x0b, 0xd5, 0xe6, 0xc7, 0x4d, 0xa4, 0x8b, 0x63, 0x89, 0xb4, 0x4c, 0xf0, 0xf7, 0x9d, 0x04,
	0xbf, 0xca, 0xea, 0xc3, 0x34, 0x10, 0x5a, 0x06, 0x2d, 0x4d, 0x9d, 0x42, 0x49, 0x80, 0xd4, 0x57,
	0x92, 0xa4, 0xd8, 0x2f, 0x94, 0x84, 0x93, 0x00, 0x96, 0xee, 0x4a, 0x00, 0xcb, 0xd5, 0x04, 0x80,
	0x37, 0x0a, 0xd5, 0xd8, 0x2b, 0x6e, 0x34, 0x08, 0x54, 0xf3, 0x4f, 0x35, 0xc6, 0xa1, 0x69, 0x35,
	0x4e, 0xf3, 0x7d, 0x9b, 0xe6, 0xe7, 0x4e, 0xd3, 0xbc, 0x62, 0xb7, 0xb8, 0xa5, 0x33, 0xde, 0xd1,
	0x39, 0xff, 0xb5, 0xc6, 0x56, 0x26, 0x6c, 0x02, 0xda, 0xe7, 0x17, 0x6e, 0xfb, 0x7c, 0xdb, 0xdc,
	0xff, 0xff, 0x1e, 0xfa, 0x4b, 0xf6, 0xa8, 0x27, 0xae, 0x65, 0xd5, 0x44, 0xf9, 0x7b, 0xa1, 0x76,
	0xe7, 0x7b, 0xa1, 0xf9, 0x8a, 0x2d, 0xbb, 0xa3, 0xe1, 0x6c, 0xb4, 0x5e, 0x6d, 0xe2, 0x7a, 0xff,
	0x9e, 0x65, 0x3c, 0x57, 0xdf, 0x13, 0xf1, 0x55, 0xcb, 0x37, 0x87, 0xc1, 0xb8, 0x86, 0xf6, 0xfa,
	0xdb, 0x58, 0xaa, 0x22, 0xac, 0x73, 0x08, 0x11, 0x2a, 0x50, 0xd3, 0x14, 0x4e, 0x0c, 0x6c, 0x9b,
	0x2a, 0x9a, 0xd4, 0x69, 0xab, 0x49, 0xe5, 0x6c, 0x8e, 0x54, 0xf2, 0x46, 0x9e, 0xa0, 0x69, 0x82,
	0x4d, 0x01, 0xa2, 0x40, 0x26, 0x04, 0x9e, 0x08, 0xd1, 0x13, 0xc6, 0xbe, 0xa4, 0xd8, 0x2d, 0x30,
	0xac, 0x00, 0x11, 0x44, 0xc1, 0x6a, 0xbe, 0x4d, 0xbb, 0x2a, 0xe2, 0x2b, 0x53, 0x0e, 0xe6, 0xa9,
	0x5d, 0x25, 0x9c, 0xcb, 0x4c, 0x37, 0x58, 0x2f, 0x65, 0xa6, 0x15, 0x2c, 0x0b, 0x10, 0x73, 0x0a,
	0x90, 0x1d, 0x09, 0x0b, 0x77, 0x45, 0xc2, 0x62, 0x35, 0x12, 0x20, 0x87, 0x65, 0xfd, 0xae, 0xcc,
	0xae, 0x0f, 0xa2, 0xe0, 0x35, 0x05, 0xa7, 0x4d, 0xb9, 0x1a, 0x1b, 0x14, 0xa3, 0x36, 0xe5, 0x6a,
	0x6c, 0x52, 0x9c, 0xda, 0x94, 0xab, 0xb1, 0x45, 0xc1, 0x6a, 0x53, 0xae, 0xc6, 0x1b, 0x8a, 0x58,
	0x9b, 0x72, 0x35, 0xb6, 0x29, 0x70, 0x6d, 0xca, 0xd5, 0xd8, 0xa1, 0x6e, 0xdf, 0xa6, 0x5c, 0x8d,
	0x5d, 0xea, 0xf9, 0x6d, 0xca, 0xd5, 0x78, 0x4b, 0x7d, 0xbf, 0x4d, 0x99, 0xd6, 0xa5, 0x34, 0xcf,
	0x2b, 0x7a, 0x00, 0x38, 0x9c, 0x9b, 0xb7, 0x9e, 0x56, 0xf3, 0x96, 0x93, 0xf3, 0x78, 0x25, 0xe7,
	0x35, 0xbb, 0xec, 0x99, 0x1d, 0x1c, 0x96, 0xb7, 0xe7, 0x51, 0xf6, 0xca, 0x89, 0xb2, 0x55, 0x3b,
	0xca, 0xaa, 0xb1, 0x41, 0x01, 0xf7, 0x05, 0x5b, 0xbd, 0x75, 0xce, 0xef, 0x8c, 0xbd, 0xbf, 0xd7,
	0xd8, 0xe3, 0x62, 0x64, 0xf8, 0x61, 0x5f, 0x8a, 0xe8, 0xee, 0x67, 0x33, 0x56, 0x16, 0xa8, 0x63,
	0x53, 0x45, 0x65, 0x09, 0xf0, 0x99, 0x7a, 0x1e, 0x7e, 0x28, 0x9e, 0xce, 0x08, 0x20, 0xda, 0xb4,
	0x12, 0x71, 0x56, 0x3e, 0x9b, 0x09, 0x5a, 0xde, 0x3e, 0x7b, 0xab, 0xb7, 0xdf, 0xbb, 0xcb, 0xdb,
	0xe7, 0x2a, 0xde, 0xde, 0xfc, 0x3d, 0x6b, 0x38, 0x76, 0xc0, 0xd3, 0xe4, 0x76, 0x7d, 0xe1, 0xd8,
	0x95, 0x3b, 0x76, 0xb5, 0xce, 0x4d, 0x36, 0xdd, 0x61, 0x7c, 0xe2, 0x5c, 0xdf, 0x69, 0xcf, 0x7f,
	0xcd, 0xb0, 0x47, 0xd6, 0xa8, 0x03, 0x29, 0xff, 0x97, 0xe6, 0x6c, 0xb0, 0xf9, 0x6c, 0x78, 0xbe,
	0x67, 0x04, 0x68, 0xcf, 0x02, 0x83, 0x71, 0x60, 0xce, 0x03, 0x29, 0x0f, 0xf3, 0x0c, 0x56, 0x12,
	0x79, 0xe3, 0x70, 0x20, 0xe5, 0x89, 0x54, 0xbe, 0x8c, 0xb5, 0x31, 0x6e, 0xad, 0x5b, 0x61, 0xf3,
	0x36, 0x04, 0x18, 0x5f, 0x1f, 0x86, 0xb1, 0x31, 0x73, 0xad, 0xeb, 0x92, 0x15, 0x2d, 0x71, 0x63,
	0xf2, 0x9c, 0xab, 0x25, 0x6e, 0x2c, 0xad, 0x5e, 0x18, 0xf7, 0x23, 0xcc, 0x78, 0xa5, 0x16, 0x92,
	0xf9, 0x6b, 0xa1, 0x05, 0x0c, 0xa4, 0x45, 0x56, 0xbe, 0x16, 0x72, 0x0e, 0x1a, 0x90, 0x1c, 0x1f,
	0xe6, 0x49, 0xd0, 0x62, 0xa0, 0x33, 0xce, 0x51, 0x7e, 0xbc, 0x45, 0xb3, 0x56, 0x95, 0xce, 0xed,
	0xd0, 0x2a, 0x0f, 0x78, 0xbf, 0xb4, 0x43, 0xc9, 0x56, 0xf5, 0xc4, 0x8d, 0xc9, 0x8d, 0x15, 0x3d,
	0x71, 0x63, 0xeb, 0xd1, 0x21, 0x1f, 0xba, 0x7a, 0x74, 0xca, 0xd2, 0xdd, 0x97, 0x6e, 0x75, 0xf7,
	0xe5, 0xbb, 0xdc, 0xdd, 0xab, 0xba, 0xfb, 0x7f, 0xe6, 0xd8, 0x93, 0xc2, 0xd3, 0x86, 0x59, 0x18,
	0xcb, 0x2c, 0xfb, 0x7e, 0xbe, 0xf6, 0x8c, 0x31, 0xfc, 0x3a, 0x95, 0x37, 0x9a, 0x1c, 0xce, 0x62,
	0x40, 0x7e, 0x21, 0xe5, 0x61, 0x12, 0xcb, 0x51, 0xe1, 0x77, 0x16, 0x03, 0x69, 0xd5, 0xa0, 0x40,
	0x9a, 0x42, 0x8c, 0xbe, 0x67, 0x53, 0xde, 0x0b, 0xb6, 0x7c, 0x21, 0x65, 0x4f, 0x6a, 0x1d, 0xc9,
	0x81, 0xa4, 0x82, 0x8d, 0xd1, 0x3d, 0x2e, 0xa0, 0xf5, 0x7e, 0x97, 0x44, 0x61, 0x20, 0xf2, 0xd2,
	0x6a, 0x31, 0x60, 0xf3, 0x4c, 0xaa, 0xeb, 0xd0, 0x97, 0x07, 0x12, 0x97, 0xa4, 0x26, 0xd8, 0x65,
	0xbd, 0x6d, 0xb6, 0x52, 0x32, 0x3d, 0x2d, 0x74, 0xe8, 0xb7, 0x06, 0xa6, 0xf2, 0xa3, 0x23, 0xde,
	0x22, 0xf5, 0x36, 0xd8, 0xe3, 0x52, 0x62, 0x9e, 0xd7, 0x6d, 0x33, 0x0a, 0x3c, 0x73, 0xba, 0x3b,
	0x51, 0xe6, 0xee, 0x09, 0xce, 0x4d, 0x5e, 0x5a, 0x61, 0x5d, 0xbd, 0xb3, 0x38, 0xd4, 0x54, 0xb5,
	0x2b, 0x6c, 0xe5, 0x8c, 0x52, 0x0d, 0xa8, 0x7a, 0x57, 0x58, 0xf0, 0x7c, 0xeb, 0x14, 0xc3, 0x81,
	0x4e, 0xa8, 0x88, 0x57, 0x69, 0xef, 0x39, 0x5b, 0x2a, 0x29, 0xfa, 0x29, 0x07, 0xab, 0xf9, 0x18,
	0xef, 0xea, 0x1e, 0xeb, 0x4b, 0xa9, 0x32, 0xf2, 0xdb, 0x31, 0xbe, 0xb2, 0x03, 0x2d, 0x94, 0x26,
	0x47, 0xae, 0xd2, 0xee, 0x99, 0xda, 0x91, 0xaf, 0xc9, 0xa9, 0x2b, 0xac, 0x6b, 0x7f, 0x60, 0x68,
	0x07, 0x58, 0xf3, 0x27, 0xca, 0x2a, 0x4f, 0x94, 0xc7, 0x63, 0x4f, 0x94, 0xfc, 0x77, 0x90, 0x27,
	0x13, 0x7e, 0x07, 0x59, 0x99, 0xf0, 0x3b, 0xc8, 0xd3, 0x09, 0xbf, 0x83, 0x70, 0xeb, 0x77, 0x10,
	0xe7, 0xd4, 0x7f, 0x90, 0xd9, 0x51, 0x42, 0xbf, 0xee, 0x55, 0x69, 0x27, 0xc2, 0x1b, 0x77, 0x45,
	0xf8, 0xc7, 0x13, 0x1e, 0x32, 0x94, 0x33, 0x56, 0xed, 0x9c, 0xd1, 0xfc, 0xc7, 0x54, 0x59, 0xb3,
	0x4f, 0x42, 0x5f, 0x0f, 0x55, 0x59, 0x64, 0x0e, 0xc2, 0x48, 0x76, 0x8a, 0xc0, 0x47, 0x04, 0x3c,
	0xbd, 0x8c, 0x29, 0xf0, 0xe9, 0x5d, 0xcc, 0xd9, 0xdc, 0x7e, 0xe2, 0x9b, 0x08, 0xc2, 0xa8, 0xcf,
	0x21, 0x6c, 0x1a, 0xc6, 0x9e, 0x96, 0xcf, 0x97, 0x02, 0xe7, 0x32, 0xd3, 0xc3, 0xce, 0x96, 0xb2,
	0xbc, 0x87, 0x3d, 0xe9, 0xc4, 0x81, 0xbc, 0x31, 0xd1, 0x3d, 0xdd, 0x25, 0x04, 0xe5, 0xec, 0xc4,
	0x34, 0xc4, 0x18, 0xcd, 0x08, 0xbc, 0x25, 0x36, 0x7d, 0xa6, 0x22, 0x8a, 0x5e, 0xf8, 0x84, 0x6b,
	0xec, 0x95, 0xd7, 0x88, 0x1d, 0xb2, 0xc5, 0xc0, 0xfc, 0x3d, 0x7c, 0x69, 0x52, 0x8f, 0x8c, 0x08,
	0xf6, 0xd4, 0xad, 0xf4, 0xc8, 0x5d, 0xcb, 0xc8, 0xdd, 0x6a, 0x8f, 0x5c, 0x10, 0x1b, 0x7f, 0x99,
	0x66, 0xf3, 0xb9, 0x31, 0xbd, 0x77, 0x6c, 0xd1, 0xfe, 0xb7, 0x86, 0xf7, 0x14, 0xaa, 0xfb, 0x84,
	0xff, 0xb1, 0x34, 0x9e, 0x8c, 0x0b, 0xd2, 0x68, 0xd4, 0xfc, 0xc8, 0x3b, 0xc6, 0x7f, 0x8c, 0x38,
	0xcf, 0x3b, 0x6f, 0x35, 0xd7, 0x9e, 0xf4, 0xf4, 0x6c, 0x34, 0x6e, 0x91, 0xe2, 0x84, 0xef, 0xd8,
	0xa2, 0xdd, 0x89, 0xe0, 0x96, 0x26, 0x3c, 0xcf, 0x70, 0x4b, 0x63, 0x2f, 0xaf, 0xe6, 0x47, 0x9e,
	0x60, 0x4f, 0x6f, 0xe9, 0x0f, 0xbd, 0x66, 0x75, 0xcc, 0x78, 0x43, 0xda, 0x58, 0xbb, 0x53, 0x07,
	0x97, 0x38, 0x73, 0x5f, 0x8c, 0xd4, 0x2e, 0x79, 0xcf, 0xc6, 0x86, 0x3a, 0x3d, 0x59, 0x63, 0xf5,
	0x56, 0xb9, 0x99, 0xf6, 0xfc, 0x9e, 0xf9, 0x3f, 0xd7, 0xe6, 0x7f, 0x03, 0x00, 0x00, 0xff, 0xff,
	0xe1, 0x7f, 0x05, 0x38, 0x0a, 0x1b, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MerchantClient is the client API for Merchant service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MerchantClient interface {
	ListMerchant(ctx context.Context, in *ListMerchantRequest, opts ...grpc.CallOption) (*ListMerchantReply, error)
	ListGroupMerchant(ctx context.Context, in *ListGroupMerchantRequest, opts ...grpc.CallOption) (*ListGroupMerchantReply, error)
	SaveMerchant(ctx context.Context, in *SaveMerchantRequest, opts ...grpc.CallOption) (*SaveMerchantReply, error)
	SaveMerchantBankAccount(ctx context.Context, in *SaveMerchantBankAccountRequest, opts ...grpc.CallOption) (*SaveMerchantBankAccountReply, error)
	SaveMerchantBizDeal(ctx context.Context, in *SaveMerchantBizDealRequest, opts ...grpc.CallOption) (*SaveMerchantBizDealReply, error)
}

type merchantClient struct {
	cc *grpc.ClientConn
}

func NewMerchantClient(cc *grpc.ClientConn) MerchantClient {
	return &merchantClient{cc}
}

func (c *merchantClient) ListMerchant(ctx context.Context, in *ListMerchantRequest, opts ...grpc.CallOption) (*ListMerchantReply, error) {
	out := new(ListMerchantReply)
	err := c.cc.Invoke(ctx, "/pb.Merchant/ListMerchant", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *merchantClient) ListGroupMerchant(ctx context.Context, in *ListGroupMerchantRequest, opts ...grpc.CallOption) (*ListGroupMerchantReply, error) {
	out := new(ListGroupMerchantReply)
	err := c.cc.Invoke(ctx, "/pb.Merchant/ListGroupMerchant", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *merchantClient) SaveMerchant(ctx context.Context, in *SaveMerchantRequest, opts ...grpc.CallOption) (*SaveMerchantReply, error) {
	out := new(SaveMerchantReply)
	err := c.cc.Invoke(ctx, "/pb.Merchant/SaveMerchant", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *merchantClient) SaveMerchantBankAccount(ctx context.Context, in *SaveMerchantBankAccountRequest, opts ...grpc.CallOption) (*SaveMerchantBankAccountReply, error) {
	out := new(SaveMerchantBankAccountReply)
	err := c.cc.Invoke(ctx, "/pb.Merchant/SaveMerchantBankAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *merchantClient) SaveMerchantBizDeal(ctx context.Context, in *SaveMerchantBizDealRequest, opts ...grpc.CallOption) (*SaveMerchantBizDealReply, error) {
	out := new(SaveMerchantBizDealReply)
	err := c.cc.Invoke(ctx, "/pb.Merchant/SaveMerchantBizDeal", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MerchantServer is the server API for Merchant service.
type MerchantServer interface {
	ListMerchant(context.Context, *ListMerchantRequest) (*ListMerchantReply, error)
	ListGroupMerchant(context.Context, *ListGroupMerchantRequest) (*ListGroupMerchantReply, error)
	SaveMerchant(context.Context, *SaveMerchantRequest) (*SaveMerchantReply, error)
	SaveMerchantBankAccount(context.Context, *SaveMerchantBankAccountRequest) (*SaveMerchantBankAccountReply, error)
	SaveMerchantBizDeal(context.Context, *SaveMerchantBizDealRequest) (*SaveMerchantBizDealReply, error)
}

// UnimplementedMerchantServer can be embedded to have forward compatible implementations.
type UnimplementedMerchantServer struct {
}

func (*UnimplementedMerchantServer) ListMerchant(ctx context.Context, req *ListMerchantRequest) (*ListMerchantReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListMerchant not implemented")
}
func (*UnimplementedMerchantServer) ListGroupMerchant(ctx context.Context, req *ListGroupMerchantRequest) (*ListGroupMerchantReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListGroupMerchant not implemented")
}
func (*UnimplementedMerchantServer) SaveMerchant(ctx context.Context, req *SaveMerchantRequest) (*SaveMerchantReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaveMerchant not implemented")
}
func (*UnimplementedMerchantServer) SaveMerchantBankAccount(ctx context.Context, req *SaveMerchantBankAccountRequest) (*SaveMerchantBankAccountReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaveMerchantBankAccount not implemented")
}
func (*UnimplementedMerchantServer) SaveMerchantBizDeal(ctx context.Context, req *SaveMerchantBizDealRequest) (*SaveMerchantBizDealReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaveMerchantBizDeal not implemented")
}

func RegisterMerchantServer(s *grpc.Server, srv MerchantServer) {
	s.RegisterService(&_Merchant_serviceDesc, srv)
}

func _Merchant_ListMerchant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMerchantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MerchantServer).ListMerchant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Merchant/ListMerchant",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MerchantServer).ListMerchant(ctx, req.(*ListMerchantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Merchant_ListGroupMerchant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListGroupMerchantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MerchantServer).ListGroupMerchant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Merchant/ListGroupMerchant",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MerchantServer).ListGroupMerchant(ctx, req.(*ListGroupMerchantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Merchant_SaveMerchant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveMerchantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MerchantServer).SaveMerchant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Merchant/SaveMerchant",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MerchantServer).SaveMerchant(ctx, req.(*SaveMerchantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Merchant_SaveMerchantBankAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveMerchantBankAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MerchantServer).SaveMerchantBankAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Merchant/SaveMerchantBankAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MerchantServer).SaveMerchantBankAccount(ctx, req.(*SaveMerchantBankAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Merchant_SaveMerchantBizDeal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveMerchantBizDealRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MerchantServer).SaveMerchantBizDeal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Merchant/SaveMerchantBizDeal",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MerchantServer).SaveMerchantBizDeal(ctx, req.(*SaveMerchantBizDealRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Merchant_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Merchant",
	HandlerType: (*MerchantServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListMerchant",
			Handler:    _Merchant_ListMerchant_Handler,
		},
		{
			MethodName: "ListGroupMerchant",
			Handler:    _Merchant_ListGroupMerchant_Handler,
		},
		{
			MethodName: "SaveMerchant",
			Handler:    _Merchant_SaveMerchant_Handler,
		},
		{
			MethodName: "SaveMerchantBankAccount",
			Handler:    _Merchant_SaveMerchantBankAccount_Handler,
		},
		{
			MethodName: "SaveMerchantBizDeal",
			Handler:    _Merchant_SaveMerchantBizDeal_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "merchant.proto",
}
