// Code generated by protoc-gen-go. DO NOT EDIT.
// source: merchant.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ListMerchantRequest struct {
	Page                 int32          `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Size                 int32          `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	Merchant             *MerchantField `protobuf:"bytes,3,opt,name=merchant,proto3" json:"merchant,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ListMerchantRequest) Reset()         { *m = ListMerchantRequest{} }
func (m *ListMerchantRequest) String() string { return proto.CompactTextString(m) }
func (*ListMerchantRequest) ProtoMessage()    {}
func (*ListMerchantRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_87fc684f407252a1, []int{0}
}

func (m *ListMerchantRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListMerchantRequest.Unmarshal(m, b)
}
func (m *ListMerchantRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListMerchantRequest.Marshal(b, m, deterministic)
}
func (m *ListMerchantRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListMerchantRequest.Merge(m, src)
}
func (m *ListMerchantRequest) XXX_Size() int {
	return xxx_messageInfo_ListMerchantRequest.Size(m)
}
func (m *ListMerchantRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListMerchantRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListMerchantRequest proto.InternalMessageInfo

func (m *ListMerchantRequest) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *ListMerchantRequest) GetSize() int32 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *ListMerchantRequest) GetMerchant() *MerchantField {
	if m != nil {
		return m.Merchant
	}
	return nil
}

type ListMerchantReply struct {
	Merchants            []*MerchantField `protobuf:"bytes,1,rep,name=merchants,proto3" json:"merchants,omitempty"`
	Count                int32            `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	Size                 int32            `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	Page                 int32            `protobuf:"varint,4,opt,name=page,proto3" json:"page,omitempty"`
	Err                  *Error           `protobuf:"bytes,5,opt,name=err,proto3" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *ListMerchantReply) Reset()         { *m = ListMerchantReply{} }
func (m *ListMerchantReply) String() string { return proto.CompactTextString(m) }
func (*ListMerchantReply) ProtoMessage()    {}
func (*ListMerchantReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_87fc684f407252a1, []int{1}
}

func (m *ListMerchantReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListMerchantReply.Unmarshal(m, b)
}
func (m *ListMerchantReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListMerchantReply.Marshal(b, m, deterministic)
}
func (m *ListMerchantReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListMerchantReply.Merge(m, src)
}
func (m *ListMerchantReply) XXX_Size() int {
	return xxx_messageInfo_ListMerchantReply.Size(m)
}
func (m *ListMerchantReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ListMerchantReply.DiscardUnknown(m)
}

var xxx_messageInfo_ListMerchantReply proto.InternalMessageInfo

func (m *ListMerchantReply) GetMerchants() []*MerchantField {
	if m != nil {
		return m.Merchants
	}
	return nil
}

func (m *ListMerchantReply) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *ListMerchantReply) GetSize() int32 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *ListMerchantReply) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *ListMerchantReply) GetErr() *Error {
	if m != nil {
		return m.Err
	}
	return nil
}

type MerchantField struct {
	MchtCd                string   `protobuf:"bytes,1,opt,name=mchtCd,proto3" json:"mchtCd,omitempty"`
	Sn                    string   `protobuf:"bytes,2,opt,name=sn,proto3" json:"sn,omitempty"`
	AipBranCd             string   `protobuf:"bytes,3,opt,name=aipBranCd,proto3" json:"aipBranCd,omitempty"`
	GroupCd               string   `protobuf:"bytes,4,opt,name=groupCd,proto3" json:"groupCd,omitempty"`
	OriChnl               string   `protobuf:"bytes,5,opt,name=oriChnl,proto3" json:"oriChnl,omitempty"`
	OriChnlDesc           string   `protobuf:"bytes,6,opt,name=oriChnlDesc,proto3" json:"oriChnlDesc,omitempty"`
	BankBelongCd          string   `protobuf:"bytes,7,opt,name=bankBelongCd,proto3" json:"bankBelongCd,omitempty"`
	DvpBy                 string   `protobuf:"bytes,8,opt,name=dvpBy,proto3" json:"dvpBy,omitempty"`
	MccCd18               string   `protobuf:"bytes,9,opt,name=mccCd18,proto3" json:"mccCd18,omitempty"`
	ApplDate              string   `protobuf:"bytes,10,opt,name=applDate,proto3" json:"applDate,omitempty"`
	UpBcCd                string   `protobuf:"bytes,11,opt,name=upBcCd,proto3" json:"upBcCd,omitempty"`
	UpAcCd                string   `protobuf:"bytes,12,opt,name=upAcCd,proto3" json:"upAcCd,omitempty"`
	UpMccCd               string   `protobuf:"bytes,13,opt,name=upMccCd,proto3" json:"upMccCd,omitempty"`
	Name                  string   `protobuf:"bytes,14,opt,name=name,proto3" json:"name,omitempty"`
	NameBusi              string   `protobuf:"bytes,15,opt,name=nameBusi,proto3" json:"nameBusi,omitempty"`
	BusiLiceNo            string   `protobuf:"bytes,16,opt,name=busiLiceNo,proto3" json:"busiLiceNo,omitempty"`
	BusiRang              string   `protobuf:"bytes,17,opt,name=busiRang,proto3" json:"busiRang,omitempty"`
	BusiMain              string   `protobuf:"bytes,18,opt,name=busiMain,proto3" json:"busiMain,omitempty"`
	Certif                string   `protobuf:"bytes,19,opt,name=certif,proto3" json:"certif,omitempty"`
	CertifType            string   `protobuf:"bytes,20,opt,name=certifType,proto3" json:"certifType,omitempty"`
	CertifNo              string   `protobuf:"bytes,21,opt,name=certifNo,proto3" json:"certifNo,omitempty"`
	CityCd                string   `protobuf:"bytes,22,opt,name=cityCd,proto3" json:"cityCd,omitempty"`
	AreaCd                string   `protobuf:"bytes,23,opt,name=areaCd,proto3" json:"areaCd,omitempty"`
	RegAddr               string   `protobuf:"bytes,24,opt,name=regAddr,proto3" json:"regAddr,omitempty"`
	ContactName           string   `protobuf:"bytes,25,opt,name=contactName,proto3" json:"contactName,omitempty"`
	ContactPhoneNo        string   `protobuf:"bytes,26,opt,name=contactPhoneNo,proto3" json:"contactPhoneNo,omitempty"`
	IsGroup               string   `protobuf:"bytes,27,opt,name=isGroup,proto3" json:"isGroup,omitempty"`
	MoneyToGroup          string   `protobuf:"bytes,28,opt,name=moneyToGroup,proto3" json:"moneyToGroup,omitempty"`
	StlmWay               string   `protobuf:"bytes,29,opt,name=stlmWay,proto3" json:"stlmWay,omitempty"`
	StlmWayDesc           string   `protobuf:"bytes,30,opt,name=stlmWayDesc,proto3" json:"stlmWayDesc,omitempty"`
	StlmInsCircle         string   `protobuf:"bytes,31,opt,name=stlmInsCircle,proto3" json:"stlmInsCircle,omitempty"`
	ApprDate              string   `protobuf:"bytes,32,opt,name=apprDate,proto3" json:"apprDate,omitempty"`
	Status                string   `protobuf:"bytes,33,opt,name=status,proto3" json:"status,omitempty"`
	DeleteDate            string   `protobuf:"bytes,34,opt,name=deleteDate,proto3" json:"deleteDate,omitempty"`
	UcBcCd32              string   `protobuf:"bytes,35,opt,name=ucBcCd32,proto3" json:"ucBcCd32,omitempty"`
	K2WorkflowId          string   `protobuf:"bytes,36,opt,name=k2WorkflowId,proto3" json:"k2WorkflowId,omitempty"`
	SystemFlag            string   `protobuf:"bytes,37,opt,name=systemFlag,proto3" json:"systemFlag,omitempty"`
	ApprovalUsername      string   `protobuf:"bytes,38,opt,name=approvalUsername,proto3" json:"approvalUsername,omitempty"`
	FinalApprovalUsername string   `protobuf:"bytes,39,opt,name=finalApprovalUsername,proto3" json:"finalApprovalUsername,omitempty"`
	IsUpStandard          string   `protobuf:"bytes,40,opt,name=isUpStandard,proto3" json:"isUpStandard,omitempty"`
	BillingType           string   `protobuf:"bytes,41,opt,name=billingType,proto3" json:"billingType,omitempty"`
	BillingLevel          string   `protobuf:"bytes,42,opt,name=billingLevel,proto3" json:"billingLevel,omitempty"`
	Slogan                string   `protobuf:"bytes,43,opt,name=slogan,proto3" json:"slogan,omitempty"`
	Ext1                  string   `protobuf:"bytes,44,opt,name=ext1,proto3" json:"ext1,omitempty"`
	Ext2                  string   `protobuf:"bytes,45,opt,name=ext2,proto3" json:"ext2,omitempty"`
	Ext3                  string   `protobuf:"bytes,46,opt,name=ext3,proto3" json:"ext3,omitempty"`
	Ext4                  string   `protobuf:"bytes,47,opt,name=ext4,proto3" json:"ext4,omitempty"`
	AreaStandard          string   `protobuf:"bytes,48,opt,name=areaStandard,proto3" json:"areaStandard,omitempty"`
	MchtCdAreaCd          string   `protobuf:"bytes,49,opt,name=mchtCdAreaCd,proto3" json:"mchtCdAreaCd,omitempty"`
	UcBcCdArea            string   `protobuf:"bytes,50,opt,name=ucBcCdArea,proto3" json:"ucBcCdArea,omitempty"`
	RecOprId              string   `protobuf:"bytes,51,opt,name=recOprId,proto3" json:"recOprId,omitempty"`
	RecUpdOpr             string   `protobuf:"bytes,52,opt,name=recUpdOpr,proto3" json:"recUpdOpr,omitempty"`
	RecCrtTs              string   `protobuf:"bytes,53,opt,name=recCrtTs,proto3" json:"recCrtTs,omitempty"`
	RecUpdTs              string   `protobuf:"bytes,54,opt,name=recUpdTs,proto3" json:"recUpdTs,omitempty"`
	OperIn                string   `protobuf:"bytes,55,opt,name=operIn,proto3" json:"operIn,omitempty"`
	RecApllyTs            string   `protobuf:"bytes,56,opt,name=recApllyTs,proto3" json:"recApllyTs,omitempty"`
	OemOrgCode            string   `protobuf:"bytes,57,opt,name=oemOrgCode,proto3" json:"oemOrgCode,omitempty"`
	IsEleInvoice          string   `protobuf:"bytes,58,opt,name=isEleInvoice,proto3" json:"isEleInvoice,omitempty"`
	DutyParagraph         string   `protobuf:"bytes,59,opt,name=dutyParagraph,proto3" json:"dutyParagraph,omitempty"`
	TaxMachineBrand       string   `protobuf:"bytes,60,opt,name=taxMachineBrand,proto3" json:"taxMachineBrand,omitempty"`
	Ext5                  string   `protobuf:"bytes,61,opt,name=ext5,proto3" json:"ext5,omitempty"`
	Ext6                  string   `protobuf:"bytes,62,opt,name=ext6,proto3" json:"ext6,omitempty"`
	Ext7                  string   `protobuf:"bytes,63,opt,name=ext7,proto3" json:"ext7,omitempty"`
	Ext8                  string   `protobuf:"bytes,64,opt,name=ext8,proto3" json:"ext8,omitempty"`
	Ext9                  string   `protobuf:"bytes,65,opt,name=ext9,proto3" json:"ext9,omitempty"`
	BusiLiceSt            string   `protobuf:"bytes,66,opt,name=busiLiceSt,proto3" json:"busiLiceSt,omitempty"`
	BusiLiceDt            string   `protobuf:"bytes,67,opt,name=busiLiceDt,proto3" json:"busiLiceDt,omitempty"`
	CertifSt              string   `protobuf:"bytes,68,opt,name=certifSt,proto3" json:"certifSt,omitempty"`
	CertifDt              string   `protobuf:"bytes,69,opt,name=certifDt,proto3" json:"certifDt,omitempty"`
	XXX_NoUnkeyedLiteral  struct{} `json:"-"`
	XXX_unrecognized      []byte   `json:"-"`
	XXX_sizecache         int32    `json:"-"`
}

func (m *MerchantField) Reset()         { *m = MerchantField{} }
func (m *MerchantField) String() string { return proto.CompactTextString(m) }
func (*MerchantField) ProtoMessage()    {}
func (*MerchantField) Descriptor() ([]byte, []int) {
	return fileDescriptor_87fc684f407252a1, []int{2}
}

func (m *MerchantField) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MerchantField.Unmarshal(m, b)
}
func (m *MerchantField) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MerchantField.Marshal(b, m, deterministic)
}
func (m *MerchantField) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MerchantField.Merge(m, src)
}
func (m *MerchantField) XXX_Size() int {
	return xxx_messageInfo_MerchantField.Size(m)
}
func (m *MerchantField) XXX_DiscardUnknown() {
	xxx_messageInfo_MerchantField.DiscardUnknown(m)
}

var xxx_messageInfo_MerchantField proto.InternalMessageInfo

func (m *MerchantField) GetMchtCd() string {
	if m != nil {
		return m.MchtCd
	}
	return ""
}

func (m *MerchantField) GetSn() string {
	if m != nil {
		return m.Sn
	}
	return ""
}

func (m *MerchantField) GetAipBranCd() string {
	if m != nil {
		return m.AipBranCd
	}
	return ""
}

func (m *MerchantField) GetGroupCd() string {
	if m != nil {
		return m.GroupCd
	}
	return ""
}

func (m *MerchantField) GetOriChnl() string {
	if m != nil {
		return m.OriChnl
	}
	return ""
}

func (m *MerchantField) GetOriChnlDesc() string {
	if m != nil {
		return m.OriChnlDesc
	}
	return ""
}

func (m *MerchantField) GetBankBelongCd() string {
	if m != nil {
		return m.BankBelongCd
	}
	return ""
}

func (m *MerchantField) GetDvpBy() string {
	if m != nil {
		return m.DvpBy
	}
	return ""
}

func (m *MerchantField) GetMccCd18() string {
	if m != nil {
		return m.MccCd18
	}
	return ""
}

func (m *MerchantField) GetApplDate() string {
	if m != nil {
		return m.ApplDate
	}
	return ""
}

func (m *MerchantField) GetUpBcCd() string {
	if m != nil {
		return m.UpBcCd
	}
	return ""
}

func (m *MerchantField) GetUpAcCd() string {
	if m != nil {
		return m.UpAcCd
	}
	return ""
}

func (m *MerchantField) GetUpMccCd() string {
	if m != nil {
		return m.UpMccCd
	}
	return ""
}

func (m *MerchantField) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *MerchantField) GetNameBusi() string {
	if m != nil {
		return m.NameBusi
	}
	return ""
}

func (m *MerchantField) GetBusiLiceNo() string {
	if m != nil {
		return m.BusiLiceNo
	}
	return ""
}

func (m *MerchantField) GetBusiRang() string {
	if m != nil {
		return m.BusiRang
	}
	return ""
}

func (m *MerchantField) GetBusiMain() string {
	if m != nil {
		return m.BusiMain
	}
	return ""
}

func (m *MerchantField) GetCertif() string {
	if m != nil {
		return m.Certif
	}
	return ""
}

func (m *MerchantField) GetCertifType() string {
	if m != nil {
		return m.CertifType
	}
	return ""
}

func (m *MerchantField) GetCertifNo() string {
	if m != nil {
		return m.CertifNo
	}
	return ""
}

func (m *MerchantField) GetCityCd() string {
	if m != nil {
		return m.CityCd
	}
	return ""
}

func (m *MerchantField) GetAreaCd() string {
	if m != nil {
		return m.AreaCd
	}
	return ""
}

func (m *MerchantField) GetRegAddr() string {
	if m != nil {
		return m.RegAddr
	}
	return ""
}

func (m *MerchantField) GetContactName() string {
	if m != nil {
		return m.ContactName
	}
	return ""
}

func (m *MerchantField) GetContactPhoneNo() string {
	if m != nil {
		return m.ContactPhoneNo
	}
	return ""
}

func (m *MerchantField) GetIsGroup() string {
	if m != nil {
		return m.IsGroup
	}
	return ""
}

func (m *MerchantField) GetMoneyToGroup() string {
	if m != nil {
		return m.MoneyToGroup
	}
	return ""
}

func (m *MerchantField) GetStlmWay() string {
	if m != nil {
		return m.StlmWay
	}
	return ""
}

func (m *MerchantField) GetStlmWayDesc() string {
	if m != nil {
		return m.StlmWayDesc
	}
	return ""
}

func (m *MerchantField) GetStlmInsCircle() string {
	if m != nil {
		return m.StlmInsCircle
	}
	return ""
}

func (m *MerchantField) GetApprDate() string {
	if m != nil {
		return m.ApprDate
	}
	return ""
}

func (m *MerchantField) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *MerchantField) GetDeleteDate() string {
	if m != nil {
		return m.DeleteDate
	}
	return ""
}

func (m *MerchantField) GetUcBcCd32() string {
	if m != nil {
		return m.UcBcCd32
	}
	return ""
}

func (m *MerchantField) GetK2WorkflowId() string {
	if m != nil {
		return m.K2WorkflowId
	}
	return ""
}

func (m *MerchantField) GetSystemFlag() string {
	if m != nil {
		return m.SystemFlag
	}
	return ""
}

func (m *MerchantField) GetApprovalUsername() string {
	if m != nil {
		return m.ApprovalUsername
	}
	return ""
}

func (m *MerchantField) GetFinalApprovalUsername() string {
	if m != nil {
		return m.FinalApprovalUsername
	}
	return ""
}

func (m *MerchantField) GetIsUpStandard() string {
	if m != nil {
		return m.IsUpStandard
	}
	return ""
}

func (m *MerchantField) GetBillingType() string {
	if m != nil {
		return m.BillingType
	}
	return ""
}

func (m *MerchantField) GetBillingLevel() string {
	if m != nil {
		return m.BillingLevel
	}
	return ""
}

func (m *MerchantField) GetSlogan() string {
	if m != nil {
		return m.Slogan
	}
	return ""
}

func (m *MerchantField) GetExt1() string {
	if m != nil {
		return m.Ext1
	}
	return ""
}

func (m *MerchantField) GetExt2() string {
	if m != nil {
		return m.Ext2
	}
	return ""
}

func (m *MerchantField) GetExt3() string {
	if m != nil {
		return m.Ext3
	}
	return ""
}

func (m *MerchantField) GetExt4() string {
	if m != nil {
		return m.Ext4
	}
	return ""
}

func (m *MerchantField) GetAreaStandard() string {
	if m != nil {
		return m.AreaStandard
	}
	return ""
}

func (m *MerchantField) GetMchtCdAreaCd() string {
	if m != nil {
		return m.MchtCdAreaCd
	}
	return ""
}

func (m *MerchantField) GetUcBcCdArea() string {
	if m != nil {
		return m.UcBcCdArea
	}
	return ""
}

func (m *MerchantField) GetRecOprId() string {
	if m != nil {
		return m.RecOprId
	}
	return ""
}

func (m *MerchantField) GetRecUpdOpr() string {
	if m != nil {
		return m.RecUpdOpr
	}
	return ""
}

func (m *MerchantField) GetRecCrtTs() string {
	if m != nil {
		return m.RecCrtTs
	}
	return ""
}

func (m *MerchantField) GetRecUpdTs() string {
	if m != nil {
		return m.RecUpdTs
	}
	return ""
}

func (m *MerchantField) GetOperIn() string {
	if m != nil {
		return m.OperIn
	}
	return ""
}

func (m *MerchantField) GetRecApllyTs() string {
	if m != nil {
		return m.RecApllyTs
	}
	return ""
}

func (m *MerchantField) GetOemOrgCode() string {
	if m != nil {
		return m.OemOrgCode
	}
	return ""
}

func (m *MerchantField) GetIsEleInvoice() string {
	if m != nil {
		return m.IsEleInvoice
	}
	return ""
}

func (m *MerchantField) GetDutyParagraph() string {
	if m != nil {
		return m.DutyParagraph
	}
	return ""
}

func (m *MerchantField) GetTaxMachineBrand() string {
	if m != nil {
		return m.TaxMachineBrand
	}
	return ""
}

func (m *MerchantField) GetExt5() string {
	if m != nil {
		return m.Ext5
	}
	return ""
}

func (m *MerchantField) GetExt6() string {
	if m != nil {
		return m.Ext6
	}
	return ""
}

func (m *MerchantField) GetExt7() string {
	if m != nil {
		return m.Ext7
	}
	return ""
}

func (m *MerchantField) GetExt8() string {
	if m != nil {
		return m.Ext8
	}
	return ""
}

func (m *MerchantField) GetExt9() string {
	if m != nil {
		return m.Ext9
	}
	return ""
}

func (m *MerchantField) GetBusiLiceSt() string {
	if m != nil {
		return m.BusiLiceSt
	}
	return ""
}

func (m *MerchantField) GetBusiLiceDt() string {
	if m != nil {
		return m.BusiLiceDt
	}
	return ""
}

func (m *MerchantField) GetCertifSt() string {
	if m != nil {
		return m.CertifSt
	}
	return ""
}

func (m *MerchantField) GetCertifDt() string {
	if m != nil {
		return m.CertifDt
	}
	return ""
}

type MerchantGroupField struct {
	JtMchtCd             string   `protobuf:"bytes,1,opt,name=jtMchtCd,proto3" json:"jtMchtCd,omitempty"`
	JtMchtNm             string   `protobuf:"bytes,2,opt,name=jtMchtNm,proto3" json:"jtMchtNm,omitempty"`
	JtArea               string   `protobuf:"bytes,3,opt,name=jtArea,proto3" json:"jtArea,omitempty"`
	MchtStlmCNm          string   `protobuf:"bytes,4,opt,name=mchtStlmCNm,proto3" json:"mchtStlmCNm,omitempty"`
	MchtStlmCAcct        string   `protobuf:"bytes,5,opt,name=mchtStlmCAcct,proto3" json:"mchtStlmCAcct,omitempty"`
	ChtStlmInsIdCd       string   `protobuf:"bytes,6,opt,name=chtStlmInsIdCd,proto3" json:"chtStlmInsIdCd,omitempty"`
	MchtStlmInsNm        string   `protobuf:"bytes,7,opt,name=mchtStlmInsNm,proto3" json:"mchtStlmInsNm,omitempty"`
	MchtPaySysAcct       string   `protobuf:"bytes,8,opt,name=mchtPaySysAcct,proto3" json:"mchtPaySysAcct,omitempty"`
	ProvCd               string   `protobuf:"bytes,9,opt,name=provCd,proto3" json:"provCd,omitempty"`
	CityCd               string   `protobuf:"bytes,10,opt,name=cityCd,proto3" json:"cityCd,omitempty"`
	AipBranCd            string   `protobuf:"bytes,11,opt,name=aipBranCd,proto3" json:"aipBranCd,omitempty"`
	SystemFlag           string   `protobuf:"bytes,12,opt,name=systemFlag,proto3" json:"systemFlag,omitempty"`
	Status               string   `protobuf:"bytes,13,opt,name=status,proto3" json:"status,omitempty"`
	UpdatedAt            string   `protobuf:"bytes,14,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	CreatedAt            string   `protobuf:"bytes,15,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	RecOprId             string   `protobuf:"bytes,16,opt,name=recOprId,proto3" json:"recOprId,omitempty"`
	RecUpdOpr            string   `protobuf:"bytes,17,opt,name=recUpdOpr,proto3" json:"recUpdOpr,omitempty"`
	JtAddr               string   `protobuf:"bytes,18,opt,name=jtAddr,proto3" json:"jtAddr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MerchantGroupField) Reset()         { *m = MerchantGroupField{} }
func (m *MerchantGroupField) String() string { return proto.CompactTextString(m) }
func (*MerchantGroupField) ProtoMessage()    {}
func (*MerchantGroupField) Descriptor() ([]byte, []int) {
	return fileDescriptor_87fc684f407252a1, []int{3}
}

func (m *MerchantGroupField) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MerchantGroupField.Unmarshal(m, b)
}
func (m *MerchantGroupField) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MerchantGroupField.Marshal(b, m, deterministic)
}
func (m *MerchantGroupField) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MerchantGroupField.Merge(m, src)
}
func (m *MerchantGroupField) XXX_Size() int {
	return xxx_messageInfo_MerchantGroupField.Size(m)
}
func (m *MerchantGroupField) XXX_DiscardUnknown() {
	xxx_messageInfo_MerchantGroupField.DiscardUnknown(m)
}

var xxx_messageInfo_MerchantGroupField proto.InternalMessageInfo

func (m *MerchantGroupField) GetJtMchtCd() string {
	if m != nil {
		return m.JtMchtCd
	}
	return ""
}

func (m *MerchantGroupField) GetJtMchtNm() string {
	if m != nil {
		return m.JtMchtNm
	}
	return ""
}

func (m *MerchantGroupField) GetJtArea() string {
	if m != nil {
		return m.JtArea
	}
	return ""
}

func (m *MerchantGroupField) GetMchtStlmCNm() string {
	if m != nil {
		return m.MchtStlmCNm
	}
	return ""
}

func (m *MerchantGroupField) GetMchtStlmCAcct() string {
	if m != nil {
		return m.MchtStlmCAcct
	}
	return ""
}

func (m *MerchantGroupField) GetChtStlmInsIdCd() string {
	if m != nil {
		return m.ChtStlmInsIdCd
	}
	return ""
}

func (m *MerchantGroupField) GetMchtStlmInsNm() string {
	if m != nil {
		return m.MchtStlmInsNm
	}
	return ""
}

func (m *MerchantGroupField) GetMchtPaySysAcct() string {
	if m != nil {
		return m.MchtPaySysAcct
	}
	return ""
}

func (m *MerchantGroupField) GetProvCd() string {
	if m != nil {
		return m.ProvCd
	}
	return ""
}

func (m *MerchantGroupField) GetCityCd() string {
	if m != nil {
		return m.CityCd
	}
	return ""
}

func (m *MerchantGroupField) GetAipBranCd() string {
	if m != nil {
		return m.AipBranCd
	}
	return ""
}

func (m *MerchantGroupField) GetSystemFlag() string {
	if m != nil {
		return m.SystemFlag
	}
	return ""
}

func (m *MerchantGroupField) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *MerchantGroupField) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

func (m *MerchantGroupField) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *MerchantGroupField) GetRecOprId() string {
	if m != nil {
		return m.RecOprId
	}
	return ""
}

func (m *MerchantGroupField) GetRecUpdOpr() string {
	if m != nil {
		return m.RecUpdOpr
	}
	return ""
}

func (m *MerchantGroupField) GetJtAddr() string {
	if m != nil {
		return m.JtAddr
	}
	return ""
}

type ListGroupMerchantRequest struct {
	Page                 int32               `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Size                 int32               `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	Group                *MerchantGroupField `protobuf:"bytes,3,opt,name=group,proto3" json:"group,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *ListGroupMerchantRequest) Reset()         { *m = ListGroupMerchantRequest{} }
func (m *ListGroupMerchantRequest) String() string { return proto.CompactTextString(m) }
func (*ListGroupMerchantRequest) ProtoMessage()    {}
func (*ListGroupMerchantRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_87fc684f407252a1, []int{4}
}

func (m *ListGroupMerchantRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListGroupMerchantRequest.Unmarshal(m, b)
}
func (m *ListGroupMerchantRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListGroupMerchantRequest.Marshal(b, m, deterministic)
}
func (m *ListGroupMerchantRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListGroupMerchantRequest.Merge(m, src)
}
func (m *ListGroupMerchantRequest) XXX_Size() int {
	return xxx_messageInfo_ListGroupMerchantRequest.Size(m)
}
func (m *ListGroupMerchantRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListGroupMerchantRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListGroupMerchantRequest proto.InternalMessageInfo

func (m *ListGroupMerchantRequest) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *ListGroupMerchantRequest) GetSize() int32 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *ListGroupMerchantRequest) GetGroup() *MerchantGroupField {
	if m != nil {
		return m.Group
	}
	return nil
}

type ListGroupMerchantReply struct {
	Groups               []*MerchantGroupField `protobuf:"bytes,1,rep,name=groups,proto3" json:"groups,omitempty"`
	Count                int32                 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	Size                 int32                 `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	Page                 int32                 `protobuf:"varint,4,opt,name=page,proto3" json:"page,omitempty"`
	Err                  *Error                `protobuf:"bytes,5,opt,name=err,proto3" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *ListGroupMerchantReply) Reset()         { *m = ListGroupMerchantReply{} }
func (m *ListGroupMerchantReply) String() string { return proto.CompactTextString(m) }
func (*ListGroupMerchantReply) ProtoMessage()    {}
func (*ListGroupMerchantReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_87fc684f407252a1, []int{5}
}

func (m *ListGroupMerchantReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListGroupMerchantReply.Unmarshal(m, b)
}
func (m *ListGroupMerchantReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListGroupMerchantReply.Marshal(b, m, deterministic)
}
func (m *ListGroupMerchantReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListGroupMerchantReply.Merge(m, src)
}
func (m *ListGroupMerchantReply) XXX_Size() int {
	return xxx_messageInfo_ListGroupMerchantReply.Size(m)
}
func (m *ListGroupMerchantReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ListGroupMerchantReply.DiscardUnknown(m)
}

var xxx_messageInfo_ListGroupMerchantReply proto.InternalMessageInfo

func (m *ListGroupMerchantReply) GetGroups() []*MerchantGroupField {
	if m != nil {
		return m.Groups
	}
	return nil
}

func (m *ListGroupMerchantReply) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *ListGroupMerchantReply) GetSize() int32 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *ListGroupMerchantReply) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *ListGroupMerchantReply) GetErr() *Error {
	if m != nil {
		return m.Err
	}
	return nil
}

func init() {
	proto.RegisterType((*ListMerchantRequest)(nil), "pb.ListMerchantRequest")
	proto.RegisterType((*ListMerchantReply)(nil), "pb.ListMerchantReply")
	proto.RegisterType((*MerchantField)(nil), "pb.MerchantField")
	proto.RegisterType((*MerchantGroupField)(nil), "pb.MerchantGroupField")
	proto.RegisterType((*ListGroupMerchantRequest)(nil), "pb.ListGroupMerchantRequest")
	proto.RegisterType((*ListGroupMerchantReply)(nil), "pb.ListGroupMerchantReply")
}

func init() { proto.RegisterFile("merchant.proto", fileDescriptor_87fc684f407252a1) }

var fileDescriptor_87fc684f407252a1 = []byte{
	// 1320 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x57, 0x6d, 0x73, 0xd3, 0x46,
	0x10, 0xae, 0x13, 0x12, 0xe2, 0xcb, 0x0b, 0xe4, 0x80, 0xb0, 0x35, 0x29, 0x4d, 0x5d, 0x4a, 0x53,
	0x0a, 0xa1, 0x38, 0x01, 0x42, 0x5f, 0x71, 0x64, 0xe8, 0x78, 0x86, 0x24, 0x8c, 0x9d, 0x0c, 0x9f,
	0x2f, 0xba, 0xc3, 0x11, 0xc8, 0x92, 0x7a, 0x3a, 0xa7, 0xa8, 0xff, 0xa5, 0xd3, 0x0f, 0xfd, 0x0f,
	0xfd, 0x3b, 0xfd, 0x2b, 0x9d, 0xbd, 0x3d, 0xbd, 0x99, 0xd0, 0x0f, 0x9d, 0xe9, 0x27, 0xeb, 0x79,
	0x76, 0x6f, 0x77, 0xb5, 0xbb, 0xda, 0x5b, 0xb3, 0x95, 0xb1, 0xd2, 0xfe, 0xa9, 0x88, 0xcc, 0x56,
	0xa2, 0x63, 0x13, 0xf3, 0x99, 0xe4, 0xa4, 0xb5, 0xa8, 0xb4, 0x8e, 0x35, 0x11, 0xed, 0x90, 0x5d,
	0x79, 0x11, 0xa4, 0x66, 0xdf, 0xa9, 0x0d, 0xd4, 0x2f, 0x13, 0x95, 0x1a, 0xce, 0xd9, 0x85, 0x44,
	0x8c, 0x14, 0x34, 0x36, 0x1a, 0x9b, 0x73, 0x03, 0xfb, 0x8c, 0x5c, 0x1a, 0xfc, 0xa6, 0x60, 0x86,
	0x38, 0x7c, 0xe6, 0xf7, 0xd8, 0x42, 0xee, 0x01, 0x66, 0x37, 0x1a, 0x9b, 0x8b, 0x9d, 0xd5, 0xad,
	0xe4, 0x64, 0x2b, 0x37, 0xf7, 0x3c, 0x50, 0xa1, 0x1c, 0x14, 0x2a, 0xed, 0x3f, 0x1a, 0x6c, 0xb5,
	0xee, 0x2e, 0x09, 0x33, 0x7e, 0x9f, 0x35, 0x73, 0x8d, 0x14, 0x1a, 0x1b, 0xb3, 0xe7, 0x5b, 0x29,
	0x75, 0xf8, 0x55, 0x36, 0xe7, 0xc7, 0x93, 0xc8, 0xb8, 0x50, 0x08, 0x14, 0xf1, 0xcd, 0x56, 0xe2,
	0xcb, 0xdf, 0xe3, 0x42, 0xe5, 0x3d, 0x6e, 0xb0, 0x59, 0xa5, 0x35, 0xcc, 0xd9, 0x70, 0x9b, 0xe8,
	0xc8, 0x26, 0x64, 0x80, 0x6c, 0xfb, 0xef, 0x4b, 0x6c, 0xb9, 0xe6, 0x97, 0xaf, 0xb1, 0xf9, 0xb1,
	0x7f, 0x6a, 0x3c, 0x69, 0x93, 0xd1, 0x1c, 0x38, 0xc4, 0x57, 0xd8, 0x4c, 0x1a, 0xd9, 0x08, 0x9a,
	0x83, 0x99, 0x34, 0xe2, 0xeb, 0xac, 0x29, 0x82, 0x64, 0x4f, 0x8b, 0xc8, 0x93, 0x36, 0x86, 0xe6,
	0xa0, 0x24, 0x38, 0xb0, 0x8b, 0x23, 0x1d, 0x4f, 0x12, 0x4f, 0xda, 0x58, 0x9a, 0x83, 0x1c, 0xa2,
	0x24, 0xd6, 0x81, 0x77, 0x1a, 0x85, 0x36, 0xa4, 0xe6, 0x20, 0x87, 0x7c, 0x83, 0x2d, 0xba, 0xc7,
	0x9e, 0x4a, 0x7d, 0x98, 0xb7, 0xd2, 0x2a, 0xc5, 0xdb, 0x6c, 0xe9, 0x44, 0x44, 0x6f, 0xf7, 0x54,
	0x18, 0x47, 0x23, 0x4f, 0xc2, 0x45, 0xab, 0x52, 0xe3, 0x30, 0x59, 0xf2, 0x2c, 0xd9, 0xcb, 0x60,
	0xc1, 0x0a, 0x09, 0xa0, 0xd7, 0xb1, 0xef, 0x7b, 0xf2, 0xc1, 0x2e, 0x34, 0xc9, 0xab, 0x83, 0xbc,
	0xc5, 0x16, 0x44, 0x92, 0x84, 0x3d, 0x61, 0x14, 0x30, 0x2b, 0x2a, 0x30, 0xe6, 0x62, 0x92, 0xec,
	0xf9, 0x9e, 0x84, 0x45, 0xca, 0x05, 0x21, 0xe2, 0xbb, 0xc8, 0x2f, 0xe5, 0x3c, 0x22, 0xf4, 0x32,
	0x49, 0xf6, 0xd1, 0x30, 0x2c, 0x93, 0x17, 0x07, 0xb1, 0x30, 0x91, 0x18, 0x2b, 0x58, 0xb1, 0xb4,
	0x7d, 0x46, 0xcf, 0xf8, 0xbb, 0x37, 0x49, 0x03, 0xb8, 0x44, 0x9e, 0x73, 0xcc, 0x6f, 0x32, 0x76,
	0x32, 0x49, 0x83, 0x17, 0x81, 0xaf, 0x0e, 0x62, 0xb8, 0x6c, 0xa5, 0x15, 0x06, 0xcf, 0x22, 0x1a,
	0x88, 0x68, 0x04, 0xab, 0x74, 0x36, 0xc7, 0xb9, 0x6c, 0x5f, 0x04, 0x11, 0xf0, 0x52, 0x86, 0x18,
	0x23, 0xf7, 0x95, 0x36, 0xc1, 0x6b, 0xb8, 0x42, 0x91, 0x13, 0x42, 0x7f, 0xf4, 0x74, 0x94, 0x25,
	0x0a, 0xae, 0x92, 0xbf, 0x92, 0x41, 0x9b, 0x84, 0x0e, 0x62, 0xb8, 0x46, 0x36, 0x73, 0x6c, 0x6d,
	0x06, 0x26, 0xf3, 0x24, 0xac, 0x39, 0x9b, 0x16, 0x21, 0x2f, 0xb4, 0x12, 0x9e, 0x84, 0xeb, 0xc4,
	0x13, 0xc2, 0x2c, 0x69, 0x35, 0xea, 0x4a, 0xa9, 0x01, 0x28, 0x4b, 0x0e, 0x62, 0x07, 0xf8, 0x71,
	0x64, 0x84, 0x6f, 0x0e, 0x30, 0x59, 0x1f, 0x53, 0x07, 0x54, 0x28, 0x7e, 0x9b, 0xad, 0x38, 0xf8,
	0xf2, 0x34, 0x8e, 0x30, 0x37, 0x2d, 0xab, 0x34, 0xc5, 0xa2, 0x8f, 0x20, 0xfd, 0x19, 0x5b, 0x0e,
	0x6e, 0x90, 0x0f, 0x07, 0xb1, 0x87, 0xc6, 0x71, 0xa4, 0xb2, 0xa3, 0x98, 0xc4, 0xeb, 0xd4, 0x43,
	0x55, 0x0e, 0x4f, 0xa7, 0x26, 0x1c, 0xbf, 0x12, 0x19, 0x7c, 0x42, 0xa7, 0x1d, 0xc4, 0x08, 0xdd,
	0xa3, 0xed, 0xd1, 0x9b, 0x14, 0x61, 0x85, 0xe2, 0xb7, 0xd8, 0x32, 0xc2, 0x7e, 0x94, 0x7a, 0x81,
	0xf6, 0x43, 0x05, 0x9f, 0x5a, 0x9d, 0x3a, 0xe9, 0xba, 0x4e, 0xdb, 0xae, 0xdb, 0x28, 0xba, 0x4e,
	0xe7, 0x5d, 0x97, 0x1a, 0x61, 0x26, 0x29, 0x7c, 0x46, 0x79, 0x23, 0x84, 0x35, 0x92, 0x2a, 0x54,
	0x46, 0xd9, 0x53, 0x6d, 0xaa, 0x51, 0xc9, 0xa0, 0xcd, 0x89, 0x8f, 0xfd, 0xb9, 0xdd, 0x81, 0xcf,
	0xc9, 0x66, 0x8e, 0xf1, 0xad, 0xdf, 0x76, 0x5e, 0xc5, 0xfa, 0xed, 0xeb, 0x30, 0xfe, 0xb5, 0x2f,
	0xe1, 0x16, 0xbd, 0x75, 0x95, 0x43, 0xfb, 0x69, 0x96, 0x1a, 0x35, 0x7e, 0x1e, 0x8a, 0x11, 0x7c,
	0x41, 0xf6, 0x4b, 0x86, 0xdf, 0x61, 0x97, 0x31, 0xc6, 0xf8, 0x4c, 0x84, 0xc7, 0xa9, 0xd2, 0xb6,
	0x9f, 0x6f, 0x5b, 0xad, 0xf7, 0x78, 0xbe, 0xc3, 0xae, 0xbd, 0x0e, 0x22, 0x11, 0x76, 0xa7, 0x0f,
	0x7c, 0x69, 0x0f, 0x9c, 0x2f, 0xc4, 0x28, 0x83, 0xf4, 0x38, 0x19, 0x1a, 0x11, 0x49, 0xa1, 0x25,
	0x6c, 0x52, 0x94, 0x55, 0x0e, 0x2b, 0x70, 0x12, 0x84, 0x61, 0x10, 0x8d, 0x6c, 0xab, 0x7e, 0x45,
	0x15, 0xa8, 0x50, 0x76, 0x4a, 0x10, 0x7c, 0xa1, 0xce, 0x54, 0x08, 0x77, 0xdc, 0x94, 0xa8, 0x70,
	0x36, 0xc7, 0x61, 0x3c, 0x12, 0x11, 0x7c, 0xed, 0x72, 0x6c, 0x11, 0x7e, 0xa7, 0xea, 0x9d, 0x79,
	0x00, 0x77, 0xe9, 0x3b, 0xc5, 0x67, 0xc7, 0x75, 0xe0, 0x5e, 0xc1, 0x75, 0x1c, 0xb7, 0x0d, 0x5b,
	0x05, 0xb7, 0xed, 0xb8, 0x1d, 0xb8, 0x5f, 0x70, 0x3b, 0x18, 0x0b, 0x76, 0x7d, 0xf1, 0x46, 0xdf,
	0x50, 0x2c, 0x55, 0xce, 0x76, 0xa4, 0x9d, 0xb1, 0x5d, 0xfa, 0x5a, 0x1e, 0xb8, 0x8e, 0xac, 0x70,
	0x58, 0x1b, 0xaa, 0x25, 0x62, 0xe8, 0x50, 0x6d, 0x4a, 0x06, 0x6b, 0xaf, 0x95, 0x7f, 0x98, 0xe8,
	0xbe, 0x84, 0x6d, 0xaa, 0x7d, 0x8e, 0x71, 0x52, 0x6b, 0xe5, 0x1f, 0x27, 0xf2, 0x30, 0xd1, 0xb0,
	0x43, 0x93, 0xba, 0x20, 0xdc, 0x49, 0x4f, 0x9b, 0xa3, 0x14, 0x1e, 0x16, 0x27, 0x2d, 0x76, 0xb2,
	0xe3, 0x44, 0x1e, 0xa5, 0xf0, 0xa8, 0x90, 0x59, 0x8c, 0x19, 0x8c, 0x13, 0xa5, 0xfb, 0x11, 0x3c,
	0xa6, 0x0c, 0x12, 0xc2, 0x48, 0xb5, 0xf2, 0xbb, 0x49, 0x18, 0x66, 0x47, 0x29, 0xec, 0x52, 0xa4,
	0x25, 0x83, 0xf2, 0x58, 0x8d, 0x0f, 0xf5, 0xc8, 0x8b, 0xa5, 0x82, 0x27, 0x24, 0x2f, 0x19, 0xea,
	0x81, 0x67, 0xa1, 0xea, 0x47, 0x67, 0x71, 0xe0, 0x2b, 0xf8, 0x36, 0xef, 0x81, 0x92, 0xc3, 0x6f,
	0x4c, 0x4e, 0x4c, 0xf6, 0x52, 0x68, 0x31, 0xd2, 0x22, 0x39, 0x85, 0xef, 0xe8, 0x1b, 0xab, 0x91,
	0x7c, 0x93, 0x5d, 0x32, 0xe2, 0xdd, 0xbe, 0xf0, 0x4f, 0x83, 0x48, 0xe1, 0xbd, 0x24, 0xe1, 0x7b,
	0xab, 0x37, 0x4d, 0xbb, 0xca, 0x3d, 0x84, 0x1f, 0x8a, 0xca, 0x3d, 0x74, 0xdc, 0x23, 0xf8, 0xb1,
	0xe0, 0x1e, 0x39, 0xee, 0x31, 0xfc, 0x54, 0x70, 0x8f, 0x1d, 0xb7, 0x0b, 0x4f, 0x0b, 0x6e, 0xd7,
	0x71, 0x4f, 0xa0, 0x5b, 0x70, 0x4f, 0xaa, 0x13, 0x7d, 0x68, 0x60, 0xaf, 0x3e, 0xd1, 0x87, 0xa6,
	0x2a, 0xef, 0x19, 0xf0, 0xea, 0xf2, 0x9e, 0x29, 0x27, 0xf0, 0xd0, 0x40, 0xaf, 0x3a, 0x81, 0x87,
	0x15, 0x59, 0xcf, 0xc0, 0xb3, 0xaa, 0xac, 0x67, 0xda, 0x7f, 0x5d, 0x60, 0x3c, 0xbf, 0xe1, 0xed,
	0x74, 0xa3, 0x6b, 0xbe, 0xc5, 0x16, 0xde, 0x98, 0xfd, 0xea, 0x45, 0x5f, 0xe0, 0x52, 0x76, 0x30,
	0x76, 0x17, 0x7e, 0x81, 0xb1, 0xec, 0x6f, 0x8c, 0x6d, 0x42, 0xba, 0xf3, 0x1d, 0xc2, 0xcf, 0x12,
	0x1b, 0x76, 0x68, 0xc2, 0xb1, 0x77, 0x30, 0x76, 0x97, 0x7e, 0x95, 0xc2, 0xa2, 0x15, 0xb0, 0xeb,
	0xfb, 0xc6, 0x5d, 0xff, 0x75, 0xd2, 0x0e, 0x78, 0xc2, 0xfd, 0x28, 0xed, 0x4b, 0x4f, 0xba, 0x3d,
	0x60, 0x8a, 0xad, 0x5a, 0xeb, 0x47, 0xe9, 0xc1, 0xd8, 0xed, 0x02, 0x75, 0x12, 0xad, 0x21, 0xf1,
	0x52, 0x64, 0xc3, 0x2c, 0xb5, 0x4e, 0x69, 0x2b, 0x98, 0x62, 0xf1, 0xad, 0x70, 0x14, 0x79, 0xd2,
	0x6d, 0x07, 0x0e, 0x55, 0xae, 0x36, 0x56, 0xbb, 0xda, 0x6a, 0xcb, 0xcf, 0xe2, 0xf4, 0xf2, 0x53,
	0x1f, 0xa4, 0x4b, 0xef, 0x0d, 0xd2, 0x72, 0xc0, 0x2f, 0xd7, 0x06, 0xfc, 0x3a, 0x6b, 0x4e, 0x12,
	0x29, 0x8c, 0x92, 0x5d, 0xe3, 0x36, 0x85, 0x92, 0x40, 0xa9, 0xaf, 0x95, 0x93, 0xd2, 0xbe, 0x50,
	0x12, 0xb5, 0x01, 0x70, 0xf9, 0xdf, 0x06, 0xc0, 0xea, 0xf4, 0x00, 0xa0, 0x8a, 0xe2, 0x6d, 0xcc,
	0x8b, 0x8a, 0x4a, 0xa9, 0xdb, 0x09, 0x03, 0xdc, 0x5d, 0x6d, 0xcf, 0xfc, 0xd7, 0x7d, 0xf9, 0x2e,
	0x9b, 0xb3, 0x7b, 0x9f, 0x5b, 0x96, 0xd7, 0xaa, 0x6b, 0x6e, 0xd9, 0x8c, 0x03, 0x52, 0x6a, 0xff,
	0xd9, 0x60, 0x6b, 0xe7, 0xb8, 0xc4, 0x9d, 0x79, 0x8b, 0xcd, 0x5b, 0x9d, 0x7c, 0x61, 0xfe, 0x90,
	0x25, 0xa7, 0xf5, 0x3f, 0xae, 0xcc, 0x9d, 0xdf, 0x1b, 0x6c, 0x21, 0xf7, 0xcc, 0x9f, 0xb2, 0xa5,
	0xea, 0x82, 0xcf, 0xaf, 0xa3, 0xf2, 0x39, 0xff, 0x30, 0x5a, 0xd7, 0xde, 0x17, 0x24, 0x61, 0xd6,
	0xfe, 0x88, 0x1f, 0xd2, 0x5f, 0x84, 0xda, 0x3b, 0xf3, 0xf5, 0x5c, 0xfb, 0xbc, 0xec, 0xb7, 0x5a,
	0x1f, 0x90, 0x5a, 0x83, 0x27, 0xf3, 0xf6, 0x9f, 0xce, 0xf6, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff,
	0x7b, 0x49, 0xbf, 0x64, 0x0c, 0x0d, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MerchantClient is the client API for Merchant service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MerchantClient interface {
	ListMerchant(ctx context.Context, in *ListMerchantRequest, opts ...grpc.CallOption) (*ListMerchantReply, error)
	ListGroupMerchant(ctx context.Context, in *ListGroupMerchantRequest, opts ...grpc.CallOption) (*ListGroupMerchantReply, error)
}

type merchantClient struct {
	cc *grpc.ClientConn
}

func NewMerchantClient(cc *grpc.ClientConn) MerchantClient {
	return &merchantClient{cc}
}

func (c *merchantClient) ListMerchant(ctx context.Context, in *ListMerchantRequest, opts ...grpc.CallOption) (*ListMerchantReply, error) {
	out := new(ListMerchantReply)
	err := c.cc.Invoke(ctx, "/pb.Merchant/ListMerchant", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *merchantClient) ListGroupMerchant(ctx context.Context, in *ListGroupMerchantRequest, opts ...grpc.CallOption) (*ListGroupMerchantReply, error) {
	out := new(ListGroupMerchantReply)
	err := c.cc.Invoke(ctx, "/pb.Merchant/ListGroupMerchant", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MerchantServer is the server API for Merchant service.
type MerchantServer interface {
	ListMerchant(context.Context, *ListMerchantRequest) (*ListMerchantReply, error)
	ListGroupMerchant(context.Context, *ListGroupMerchantRequest) (*ListGroupMerchantReply, error)
}

// UnimplementedMerchantServer can be embedded to have forward compatible implementations.
type UnimplementedMerchantServer struct {
}

func (*UnimplementedMerchantServer) ListMerchant(ctx context.Context, req *ListMerchantRequest) (*ListMerchantReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListMerchant not implemented")
}
func (*UnimplementedMerchantServer) ListGroupMerchant(ctx context.Context, req *ListGroupMerchantRequest) (*ListGroupMerchantReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListGroupMerchant not implemented")
}

func RegisterMerchantServer(s *grpc.Server, srv MerchantServer) {
	s.RegisterService(&_Merchant_serviceDesc, srv)
}

func _Merchant_ListMerchant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMerchantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MerchantServer).ListMerchant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Merchant/ListMerchant",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MerchantServer).ListMerchant(ctx, req.(*ListMerchantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Merchant_ListGroupMerchant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListGroupMerchantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MerchantServer).ListGroupMerchant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Merchant/ListGroupMerchant",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MerchantServer).ListGroupMerchant(ctx, req.(*ListGroupMerchantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Merchant_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Merchant",
	HandlerType: (*MerchantServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListMerchant",
			Handler:    _Merchant_ListMerchant_Handler,
		},
		{
			MethodName: "ListGroupMerchant",
			Handler:    _Merchant_ListGroupMerchant_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "merchant.proto",
}
