// Code generated by protoc-gen-go. DO NOT EDIT.
// source: static.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type InsProdBizFeeMapInfoField struct {
	ProdCd               string   `protobuf:"bytes,1,opt,name=ProdCd,proto3" json:"ProdCd,omitempty"`
	BizCd                string   `protobuf:"bytes,2,opt,name=BizCd,proto3" json:"BizCd,omitempty"`
	MccMTp               string   `protobuf:"bytes,3,opt,name=MccMTp,proto3" json:"MccMTp,omitempty"`
	MccSTp               string   `protobuf:"bytes,4,opt,name=MccSTp,proto3" json:"MccSTp,omitempty"`
	InsFeeBizCd          string   `protobuf:"bytes,5,opt,name=InsFeeBizCd,proto3" json:"InsFeeBizCd,omitempty"`
	InsFeeBizNm          string   `protobuf:"bytes,6,opt,name=InsFeeBizNm,proto3" json:"InsFeeBizNm,omitempty"`
	MsgResvFld1          string   `protobuf:"bytes,7,opt,name=MsgResvFld1,proto3" json:"MsgResvFld1,omitempty"`
	MsgResvFld2          string   `protobuf:"bytes,8,opt,name=MsgResvFld2,proto3" json:"MsgResvFld2,omitempty"`
	MsgResvFld3          string   `protobuf:"bytes,9,opt,name=MsgResvFld3,proto3" json:"MsgResvFld3,omitempty"`
	MsgResvFld4          string   `protobuf:"bytes,10,opt,name=MsgResvFld4,proto3" json:"MsgResvFld4,omitempty"`
	MsgResvFld5          string   `protobuf:"bytes,11,opt,name=MsgResvFld5,proto3" json:"MsgResvFld5,omitempty"`
	MsgResvFld6          string   `protobuf:"bytes,12,opt,name=MsgResvFld6,proto3" json:"MsgResvFld6,omitempty"`
	MsgResvFld7          string   `protobuf:"bytes,13,opt,name=MsgResvFld7,proto3" json:"MsgResvFld7,omitempty"`
	MsgResvFld8          string   `protobuf:"bytes,14,opt,name=MsgResvFld8,proto3" json:"MsgResvFld8,omitempty"`
	MsgResvFld9          string   `protobuf:"bytes,15,opt,name=MsgResvFld9,proto3" json:"MsgResvFld9,omitempty"`
	MsgResvFld10         string   `protobuf:"bytes,16,opt,name=MsgResvFld10,proto3" json:"MsgResvFld10,omitempty"`
	RecOprID             string   `protobuf:"bytes,17,opt,name=RecOprID,proto3" json:"RecOprID,omitempty"`
	RecUpdOpr            string   `protobuf:"bytes,18,opt,name=RecUpdOpr,proto3" json:"RecUpdOpr,omitempty"`
	CreateAt             string   `protobuf:"bytes,19,opt,name=CreateAt,proto3" json:"CreateAt,omitempty"`
	UpdatedAt            string   `protobuf:"bytes,20,opt,name=UpdatedAt,proto3" json:"UpdatedAt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InsProdBizFeeMapInfoField) Reset()         { *m = InsProdBizFeeMapInfoField{} }
func (m *InsProdBizFeeMapInfoField) String() string { return proto.CompactTextString(m) }
func (*InsProdBizFeeMapInfoField) ProtoMessage()    {}
func (*InsProdBizFeeMapInfoField) Descriptor() ([]byte, []int) {
	return fileDescriptor_800d8474b3bfe66d, []int{0}
}

func (m *InsProdBizFeeMapInfoField) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InsProdBizFeeMapInfoField.Unmarshal(m, b)
}
func (m *InsProdBizFeeMapInfoField) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InsProdBizFeeMapInfoField.Marshal(b, m, deterministic)
}
func (m *InsProdBizFeeMapInfoField) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InsProdBizFeeMapInfoField.Merge(m, src)
}
func (m *InsProdBizFeeMapInfoField) XXX_Size() int {
	return xxx_messageInfo_InsProdBizFeeMapInfoField.Size(m)
}
func (m *InsProdBizFeeMapInfoField) XXX_DiscardUnknown() {
	xxx_messageInfo_InsProdBizFeeMapInfoField.DiscardUnknown(m)
}

var xxx_messageInfo_InsProdBizFeeMapInfoField proto.InternalMessageInfo

func (m *InsProdBizFeeMapInfoField) GetProdCd() string {
	if m != nil {
		return m.ProdCd
	}
	return ""
}

func (m *InsProdBizFeeMapInfoField) GetBizCd() string {
	if m != nil {
		return m.BizCd
	}
	return ""
}

func (m *InsProdBizFeeMapInfoField) GetMccMTp() string {
	if m != nil {
		return m.MccMTp
	}
	return ""
}

func (m *InsProdBizFeeMapInfoField) GetMccSTp() string {
	if m != nil {
		return m.MccSTp
	}
	return ""
}

func (m *InsProdBizFeeMapInfoField) GetInsFeeBizCd() string {
	if m != nil {
		return m.InsFeeBizCd
	}
	return ""
}

func (m *InsProdBizFeeMapInfoField) GetInsFeeBizNm() string {
	if m != nil {
		return m.InsFeeBizNm
	}
	return ""
}

func (m *InsProdBizFeeMapInfoField) GetMsgResvFld1() string {
	if m != nil {
		return m.MsgResvFld1
	}
	return ""
}

func (m *InsProdBizFeeMapInfoField) GetMsgResvFld2() string {
	if m != nil {
		return m.MsgResvFld2
	}
	return ""
}

func (m *InsProdBizFeeMapInfoField) GetMsgResvFld3() string {
	if m != nil {
		return m.MsgResvFld3
	}
	return ""
}

func (m *InsProdBizFeeMapInfoField) GetMsgResvFld4() string {
	if m != nil {
		return m.MsgResvFld4
	}
	return ""
}

func (m *InsProdBizFeeMapInfoField) GetMsgResvFld5() string {
	if m != nil {
		return m.MsgResvFld5
	}
	return ""
}

func (m *InsProdBizFeeMapInfoField) GetMsgResvFld6() string {
	if m != nil {
		return m.MsgResvFld6
	}
	return ""
}

func (m *InsProdBizFeeMapInfoField) GetMsgResvFld7() string {
	if m != nil {
		return m.MsgResvFld7
	}
	return ""
}

func (m *InsProdBizFeeMapInfoField) GetMsgResvFld8() string {
	if m != nil {
		return m.MsgResvFld8
	}
	return ""
}

func (m *InsProdBizFeeMapInfoField) GetMsgResvFld9() string {
	if m != nil {
		return m.MsgResvFld9
	}
	return ""
}

func (m *InsProdBizFeeMapInfoField) GetMsgResvFld10() string {
	if m != nil {
		return m.MsgResvFld10
	}
	return ""
}

func (m *InsProdBizFeeMapInfoField) GetRecOprID() string {
	if m != nil {
		return m.RecOprID
	}
	return ""
}

func (m *InsProdBizFeeMapInfoField) GetRecUpdOpr() string {
	if m != nil {
		return m.RecUpdOpr
	}
	return ""
}

func (m *InsProdBizFeeMapInfoField) GetCreateAt() string {
	if m != nil {
		return m.CreateAt
	}
	return ""
}

func (m *InsProdBizFeeMapInfoField) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

type GetInsProdBizFeeMapInfoReply struct {
	Items                []*InsProdBizFeeMapInfoField `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Err                  *Error                       `protobuf:"bytes,2,opt,name=err,proto3" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *GetInsProdBizFeeMapInfoReply) Reset()         { *m = GetInsProdBizFeeMapInfoReply{} }
func (m *GetInsProdBizFeeMapInfoReply) String() string { return proto.CompactTextString(m) }
func (*GetInsProdBizFeeMapInfoReply) ProtoMessage()    {}
func (*GetInsProdBizFeeMapInfoReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_800d8474b3bfe66d, []int{1}
}

func (m *GetInsProdBizFeeMapInfoReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetInsProdBizFeeMapInfoReply.Unmarshal(m, b)
}
func (m *GetInsProdBizFeeMapInfoReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetInsProdBizFeeMapInfoReply.Marshal(b, m, deterministic)
}
func (m *GetInsProdBizFeeMapInfoReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetInsProdBizFeeMapInfoReply.Merge(m, src)
}
func (m *GetInsProdBizFeeMapInfoReply) XXX_Size() int {
	return xxx_messageInfo_GetInsProdBizFeeMapInfoReply.Size(m)
}
func (m *GetInsProdBizFeeMapInfoReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetInsProdBizFeeMapInfoReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetInsProdBizFeeMapInfoReply proto.InternalMessageInfo

func (m *GetInsProdBizFeeMapInfoReply) GetItems() []*InsProdBizFeeMapInfoField {
	if m != nil {
		return m.Items
	}
	return nil
}

func (m *GetInsProdBizFeeMapInfoReply) GetErr() *Error {
	if m != nil {
		return m.Err
	}
	return nil
}

type GetInsProdBizFeeMapInfoRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetInsProdBizFeeMapInfoRequest) Reset()         { *m = GetInsProdBizFeeMapInfoRequest{} }
func (m *GetInsProdBizFeeMapInfoRequest) String() string { return proto.CompactTextString(m) }
func (*GetInsProdBizFeeMapInfoRequest) ProtoMessage()    {}
func (*GetInsProdBizFeeMapInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_800d8474b3bfe66d, []int{2}
}

func (m *GetInsProdBizFeeMapInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetInsProdBizFeeMapInfoRequest.Unmarshal(m, b)
}
func (m *GetInsProdBizFeeMapInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetInsProdBizFeeMapInfoRequest.Marshal(b, m, deterministic)
}
func (m *GetInsProdBizFeeMapInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetInsProdBizFeeMapInfoRequest.Merge(m, src)
}
func (m *GetInsProdBizFeeMapInfoRequest) XXX_Size() int {
	return xxx_messageInfo_GetInsProdBizFeeMapInfoRequest.Size(m)
}
func (m *GetInsProdBizFeeMapInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetInsProdBizFeeMapInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetInsProdBizFeeMapInfoRequest proto.InternalMessageInfo

type StaticSyncDataReq struct {
	TableName            string   `protobuf:"bytes,1,opt,name=TableName,proto3" json:"TableName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StaticSyncDataReq) Reset()         { *m = StaticSyncDataReq{} }
func (m *StaticSyncDataReq) String() string { return proto.CompactTextString(m) }
func (*StaticSyncDataReq) ProtoMessage()    {}
func (*StaticSyncDataReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_800d8474b3bfe66d, []int{3}
}

func (m *StaticSyncDataReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StaticSyncDataReq.Unmarshal(m, b)
}
func (m *StaticSyncDataReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StaticSyncDataReq.Marshal(b, m, deterministic)
}
func (m *StaticSyncDataReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StaticSyncDataReq.Merge(m, src)
}
func (m *StaticSyncDataReq) XXX_Size() int {
	return xxx_messageInfo_StaticSyncDataReq.Size(m)
}
func (m *StaticSyncDataReq) XXX_DiscardUnknown() {
	xxx_messageInfo_StaticSyncDataReq.DiscardUnknown(m)
}

var xxx_messageInfo_StaticSyncDataReq proto.InternalMessageInfo

func (m *StaticSyncDataReq) GetTableName() string {
	if m != nil {
		return m.TableName
	}
	return ""
}

type StaticSyncDataResp struct {
	Result               bool     `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	Err                  *Error   `protobuf:"bytes,2,opt,name=err,proto3" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StaticSyncDataResp) Reset()         { *m = StaticSyncDataResp{} }
func (m *StaticSyncDataResp) String() string { return proto.CompactTextString(m) }
func (*StaticSyncDataResp) ProtoMessage()    {}
func (*StaticSyncDataResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_800d8474b3bfe66d, []int{4}
}

func (m *StaticSyncDataResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StaticSyncDataResp.Unmarshal(m, b)
}
func (m *StaticSyncDataResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StaticSyncDataResp.Marshal(b, m, deterministic)
}
func (m *StaticSyncDataResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StaticSyncDataResp.Merge(m, src)
}
func (m *StaticSyncDataResp) XXX_Size() int {
	return xxx_messageInfo_StaticSyncDataResp.Size(m)
}
func (m *StaticSyncDataResp) XXX_DiscardUnknown() {
	xxx_messageInfo_StaticSyncDataResp.DiscardUnknown(m)
}

var xxx_messageInfo_StaticSyncDataResp proto.InternalMessageInfo

func (m *StaticSyncDataResp) GetResult() bool {
	if m != nil {
		return m.Result
	}
	return false
}

func (m *StaticSyncDataResp) GetErr() *Error {
	if m != nil {
		return m.Err
	}
	return nil
}

type StaticGetDictionaryItemReq struct {
	DicType              string   `protobuf:"bytes,1,opt,name=dicType,proto3" json:"dicType,omitempty"`
	DicCode              string   `protobuf:"bytes,2,opt,name=dicCode,proto3" json:"dicCode,omitempty"`
	DicName              string   `protobuf:"bytes,3,opt,name=dicName,proto3" json:"dicName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StaticGetDictionaryItemReq) Reset()         { *m = StaticGetDictionaryItemReq{} }
func (m *StaticGetDictionaryItemReq) String() string { return proto.CompactTextString(m) }
func (*StaticGetDictionaryItemReq) ProtoMessage()    {}
func (*StaticGetDictionaryItemReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_800d8474b3bfe66d, []int{5}
}

func (m *StaticGetDictionaryItemReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StaticGetDictionaryItemReq.Unmarshal(m, b)
}
func (m *StaticGetDictionaryItemReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StaticGetDictionaryItemReq.Marshal(b, m, deterministic)
}
func (m *StaticGetDictionaryItemReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StaticGetDictionaryItemReq.Merge(m, src)
}
func (m *StaticGetDictionaryItemReq) XXX_Size() int {
	return xxx_messageInfo_StaticGetDictionaryItemReq.Size(m)
}
func (m *StaticGetDictionaryItemReq) XXX_DiscardUnknown() {
	xxx_messageInfo_StaticGetDictionaryItemReq.DiscardUnknown(m)
}

var xxx_messageInfo_StaticGetDictionaryItemReq proto.InternalMessageInfo

func (m *StaticGetDictionaryItemReq) GetDicType() string {
	if m != nil {
		return m.DicType
	}
	return ""
}

func (m *StaticGetDictionaryItemReq) GetDicCode() string {
	if m != nil {
		return m.DicCode
	}
	return ""
}

func (m *StaticGetDictionaryItemReq) GetDicName() string {
	if m != nil {
		return m.DicName
	}
	return ""
}

type StaticGetDictionaryItemResp struct {
	Items                []*StaticGetDictionaryItem `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Err                  *Error                     `protobuf:"bytes,2,opt,name=err,proto3" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *StaticGetDictionaryItemResp) Reset()         { *m = StaticGetDictionaryItemResp{} }
func (m *StaticGetDictionaryItemResp) String() string { return proto.CompactTextString(m) }
func (*StaticGetDictionaryItemResp) ProtoMessage()    {}
func (*StaticGetDictionaryItemResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_800d8474b3bfe66d, []int{6}
}

func (m *StaticGetDictionaryItemResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StaticGetDictionaryItemResp.Unmarshal(m, b)
}
func (m *StaticGetDictionaryItemResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StaticGetDictionaryItemResp.Marshal(b, m, deterministic)
}
func (m *StaticGetDictionaryItemResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StaticGetDictionaryItemResp.Merge(m, src)
}
func (m *StaticGetDictionaryItemResp) XXX_Size() int {
	return xxx_messageInfo_StaticGetDictionaryItemResp.Size(m)
}
func (m *StaticGetDictionaryItemResp) XXX_DiscardUnknown() {
	xxx_messageInfo_StaticGetDictionaryItemResp.DiscardUnknown(m)
}

var xxx_messageInfo_StaticGetDictionaryItemResp proto.InternalMessageInfo

func (m *StaticGetDictionaryItemResp) GetItems() []*StaticGetDictionaryItem {
	if m != nil {
		return m.Items
	}
	return nil
}

func (m *StaticGetDictionaryItemResp) GetErr() *Error {
	if m != nil {
		return m.Err
	}
	return nil
}

type StaticGetDictionaryItem struct {
	DicType              string   `protobuf:"bytes,1,opt,name=dicType,proto3" json:"dicType,omitempty"`
	DicCode              string   `protobuf:"bytes,2,opt,name=dicCode,proto3" json:"dicCode,omitempty"`
	DicName              string   `protobuf:"bytes,3,opt,name=dicName,proto3" json:"dicName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StaticGetDictionaryItem) Reset()         { *m = StaticGetDictionaryItem{} }
func (m *StaticGetDictionaryItem) String() string { return proto.CompactTextString(m) }
func (*StaticGetDictionaryItem) ProtoMessage()    {}
func (*StaticGetDictionaryItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_800d8474b3bfe66d, []int{7}
}

func (m *StaticGetDictionaryItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StaticGetDictionaryItem.Unmarshal(m, b)
}
func (m *StaticGetDictionaryItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StaticGetDictionaryItem.Marshal(b, m, deterministic)
}
func (m *StaticGetDictionaryItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StaticGetDictionaryItem.Merge(m, src)
}
func (m *StaticGetDictionaryItem) XXX_Size() int {
	return xxx_messageInfo_StaticGetDictionaryItem.Size(m)
}
func (m *StaticGetDictionaryItem) XXX_DiscardUnknown() {
	xxx_messageInfo_StaticGetDictionaryItem.DiscardUnknown(m)
}

var xxx_messageInfo_StaticGetDictionaryItem proto.InternalMessageInfo

func (m *StaticGetDictionaryItem) GetDicType() string {
	if m != nil {
		return m.DicType
	}
	return ""
}

func (m *StaticGetDictionaryItem) GetDicCode() string {
	if m != nil {
		return m.DicCode
	}
	return ""
}

func (m *StaticGetDictionaryItem) GetDicName() string {
	if m != nil {
		return m.DicName
	}
	return ""
}

type StaticGetDicByProdAndBizReq struct {
	ProdCd               string   `protobuf:"bytes,1,opt,name=prodCd,proto3" json:"prodCd,omitempty"`
	BizCd                string   `protobuf:"bytes,2,opt,name=bizCd,proto3" json:"bizCd,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StaticGetDicByProdAndBizReq) Reset()         { *m = StaticGetDicByProdAndBizReq{} }
func (m *StaticGetDicByProdAndBizReq) String() string { return proto.CompactTextString(m) }
func (*StaticGetDicByProdAndBizReq) ProtoMessage()    {}
func (*StaticGetDicByProdAndBizReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_800d8474b3bfe66d, []int{8}
}

func (m *StaticGetDicByProdAndBizReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StaticGetDicByProdAndBizReq.Unmarshal(m, b)
}
func (m *StaticGetDicByProdAndBizReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StaticGetDicByProdAndBizReq.Marshal(b, m, deterministic)
}
func (m *StaticGetDicByProdAndBizReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StaticGetDicByProdAndBizReq.Merge(m, src)
}
func (m *StaticGetDicByProdAndBizReq) XXX_Size() int {
	return xxx_messageInfo_StaticGetDicByProdAndBizReq.Size(m)
}
func (m *StaticGetDicByProdAndBizReq) XXX_DiscardUnknown() {
	xxx_messageInfo_StaticGetDicByProdAndBizReq.DiscardUnknown(m)
}

var xxx_messageInfo_StaticGetDicByProdAndBizReq proto.InternalMessageInfo

func (m *StaticGetDicByProdAndBizReq) GetProdCd() string {
	if m != nil {
		return m.ProdCd
	}
	return ""
}

func (m *StaticGetDicByProdAndBizReq) GetBizCd() string {
	if m != nil {
		return m.BizCd
	}
	return ""
}

type StaticGetDicByProdAndBizResp struct {
	Items                []*StaticGetDictionaryItem `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Err                  *Error                     `protobuf:"bytes,2,opt,name=err,proto3" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *StaticGetDicByProdAndBizResp) Reset()         { *m = StaticGetDicByProdAndBizResp{} }
func (m *StaticGetDicByProdAndBizResp) String() string { return proto.CompactTextString(m) }
func (*StaticGetDicByProdAndBizResp) ProtoMessage()    {}
func (*StaticGetDicByProdAndBizResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_800d8474b3bfe66d, []int{9}
}

func (m *StaticGetDicByProdAndBizResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StaticGetDicByProdAndBizResp.Unmarshal(m, b)
}
func (m *StaticGetDicByProdAndBizResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StaticGetDicByProdAndBizResp.Marshal(b, m, deterministic)
}
func (m *StaticGetDicByProdAndBizResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StaticGetDicByProdAndBizResp.Merge(m, src)
}
func (m *StaticGetDicByProdAndBizResp) XXX_Size() int {
	return xxx_messageInfo_StaticGetDicByProdAndBizResp.Size(m)
}
func (m *StaticGetDicByProdAndBizResp) XXX_DiscardUnknown() {
	xxx_messageInfo_StaticGetDicByProdAndBizResp.DiscardUnknown(m)
}

var xxx_messageInfo_StaticGetDicByProdAndBizResp proto.InternalMessageInfo

func (m *StaticGetDicByProdAndBizResp) GetItems() []*StaticGetDictionaryItem {
	if m != nil {
		return m.Items
	}
	return nil
}

func (m *StaticGetDicByProdAndBizResp) GetErr() *Error {
	if m != nil {
		return m.Err
	}
	return nil
}

type StaticGetDicByInsCmpCdReq struct {
	InsCompanyCd         string   `protobuf:"bytes,1,opt,name=InsCompanyCd,proto3" json:"InsCompanyCd,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StaticGetDicByInsCmpCdReq) Reset()         { *m = StaticGetDicByInsCmpCdReq{} }
func (m *StaticGetDicByInsCmpCdReq) String() string { return proto.CompactTextString(m) }
func (*StaticGetDicByInsCmpCdReq) ProtoMessage()    {}
func (*StaticGetDicByInsCmpCdReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_800d8474b3bfe66d, []int{10}
}

func (m *StaticGetDicByInsCmpCdReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StaticGetDicByInsCmpCdReq.Unmarshal(m, b)
}
func (m *StaticGetDicByInsCmpCdReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StaticGetDicByInsCmpCdReq.Marshal(b, m, deterministic)
}
func (m *StaticGetDicByInsCmpCdReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StaticGetDicByInsCmpCdReq.Merge(m, src)
}
func (m *StaticGetDicByInsCmpCdReq) XXX_Size() int {
	return xxx_messageInfo_StaticGetDicByInsCmpCdReq.Size(m)
}
func (m *StaticGetDicByInsCmpCdReq) XXX_DiscardUnknown() {
	xxx_messageInfo_StaticGetDicByInsCmpCdReq.DiscardUnknown(m)
}

var xxx_messageInfo_StaticGetDicByInsCmpCdReq proto.InternalMessageInfo

func (m *StaticGetDicByInsCmpCdReq) GetInsCompanyCd() string {
	if m != nil {
		return m.InsCompanyCd
	}
	return ""
}

type StaticGetDicByInsCmpCdResp struct {
	Items                []*StaticGetDictionaryItem `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Err                  *Error                     `protobuf:"bytes,2,opt,name=err,proto3" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *StaticGetDicByInsCmpCdResp) Reset()         { *m = StaticGetDicByInsCmpCdResp{} }
func (m *StaticGetDicByInsCmpCdResp) String() string { return proto.CompactTextString(m) }
func (*StaticGetDicByInsCmpCdResp) ProtoMessage()    {}
func (*StaticGetDicByInsCmpCdResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_800d8474b3bfe66d, []int{11}
}

func (m *StaticGetDicByInsCmpCdResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StaticGetDicByInsCmpCdResp.Unmarshal(m, b)
}
func (m *StaticGetDicByInsCmpCdResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StaticGetDicByInsCmpCdResp.Marshal(b, m, deterministic)
}
func (m *StaticGetDicByInsCmpCdResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StaticGetDicByInsCmpCdResp.Merge(m, src)
}
func (m *StaticGetDicByInsCmpCdResp) XXX_Size() int {
	return xxx_messageInfo_StaticGetDicByInsCmpCdResp.Size(m)
}
func (m *StaticGetDicByInsCmpCdResp) XXX_DiscardUnknown() {
	xxx_messageInfo_StaticGetDicByInsCmpCdResp.DiscardUnknown(m)
}

var xxx_messageInfo_StaticGetDicByInsCmpCdResp proto.InternalMessageInfo

func (m *StaticGetDicByInsCmpCdResp) GetItems() []*StaticGetDictionaryItem {
	if m != nil {
		return m.Items
	}
	return nil
}

func (m *StaticGetDicByInsCmpCdResp) GetErr() *Error {
	if m != nil {
		return m.Err
	}
	return nil
}

type StaticCheckValuesReq struct {
	ProdCd               string   `protobuf:"bytes,1,opt,name=prodCd,proto3" json:"prodCd,omitempty"`
	BizCd                string   `protobuf:"bytes,2,opt,name=bizCd,proto3" json:"bizCd,omitempty"`
	TransCd              string   `protobuf:"bytes,3,opt,name=transCd,proto3" json:"transCd,omitempty"`
	InsCompanyCd         string   `protobuf:"bytes,4,opt,name=insCompanyCd,proto3" json:"insCompanyCd,omitempty"`
	FwdInsIdCd           string   `protobuf:"bytes,5,opt,name=fwdInsIdCd,proto3" json:"fwdInsIdCd,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StaticCheckValuesReq) Reset()         { *m = StaticCheckValuesReq{} }
func (m *StaticCheckValuesReq) String() string { return proto.CompactTextString(m) }
func (*StaticCheckValuesReq) ProtoMessage()    {}
func (*StaticCheckValuesReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_800d8474b3bfe66d, []int{12}
}

func (m *StaticCheckValuesReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StaticCheckValuesReq.Unmarshal(m, b)
}
func (m *StaticCheckValuesReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StaticCheckValuesReq.Marshal(b, m, deterministic)
}
func (m *StaticCheckValuesReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StaticCheckValuesReq.Merge(m, src)
}
func (m *StaticCheckValuesReq) XXX_Size() int {
	return xxx_messageInfo_StaticCheckValuesReq.Size(m)
}
func (m *StaticCheckValuesReq) XXX_DiscardUnknown() {
	xxx_messageInfo_StaticCheckValuesReq.DiscardUnknown(m)
}

var xxx_messageInfo_StaticCheckValuesReq proto.InternalMessageInfo

func (m *StaticCheckValuesReq) GetProdCd() string {
	if m != nil {
		return m.ProdCd
	}
	return ""
}

func (m *StaticCheckValuesReq) GetBizCd() string {
	if m != nil {
		return m.BizCd
	}
	return ""
}

func (m *StaticCheckValuesReq) GetTransCd() string {
	if m != nil {
		return m.TransCd
	}
	return ""
}

func (m *StaticCheckValuesReq) GetInsCompanyCd() string {
	if m != nil {
		return m.InsCompanyCd
	}
	return ""
}

func (m *StaticCheckValuesReq) GetFwdInsIdCd() string {
	if m != nil {
		return m.FwdInsIdCd
	}
	return ""
}

type StaticCheckValuesResp struct {
	Result               bool     `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	Err                  *Error   `protobuf:"bytes,2,opt,name=err,proto3" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StaticCheckValuesResp) Reset()         { *m = StaticCheckValuesResp{} }
func (m *StaticCheckValuesResp) String() string { return proto.CompactTextString(m) }
func (*StaticCheckValuesResp) ProtoMessage()    {}
func (*StaticCheckValuesResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_800d8474b3bfe66d, []int{13}
}

func (m *StaticCheckValuesResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StaticCheckValuesResp.Unmarshal(m, b)
}
func (m *StaticCheckValuesResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StaticCheckValuesResp.Marshal(b, m, deterministic)
}
func (m *StaticCheckValuesResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StaticCheckValuesResp.Merge(m, src)
}
func (m *StaticCheckValuesResp) XXX_Size() int {
	return xxx_messageInfo_StaticCheckValuesResp.Size(m)
}
func (m *StaticCheckValuesResp) XXX_DiscardUnknown() {
	xxx_messageInfo_StaticCheckValuesResp.DiscardUnknown(m)
}

var xxx_messageInfo_StaticCheckValuesResp proto.InternalMessageInfo

func (m *StaticCheckValuesResp) GetResult() bool {
	if m != nil {
		return m.Result
	}
	return false
}

func (m *StaticCheckValuesResp) GetErr() *Error {
	if m != nil {
		return m.Err
	}
	return nil
}

type GetDictionaryLayerItemReq struct {
	DicType              string   `protobuf:"bytes,1,opt,name=dicType,proto3" json:"dicType,omitempty"`
	DicCode              string   `protobuf:"bytes,2,opt,name=dicCode,proto3" json:"dicCode,omitempty"`
	DicPCode             string   `protobuf:"bytes,3,opt,name=dicPCode,proto3" json:"dicPCode,omitempty"`
	DicLevel             string   `protobuf:"bytes,4,opt,name=dicLevel,proto3" json:"dicLevel,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetDictionaryLayerItemReq) Reset()         { *m = GetDictionaryLayerItemReq{} }
func (m *GetDictionaryLayerItemReq) String() string { return proto.CompactTextString(m) }
func (*GetDictionaryLayerItemReq) ProtoMessage()    {}
func (*GetDictionaryLayerItemReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_800d8474b3bfe66d, []int{14}
}

func (m *GetDictionaryLayerItemReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDictionaryLayerItemReq.Unmarshal(m, b)
}
func (m *GetDictionaryLayerItemReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDictionaryLayerItemReq.Marshal(b, m, deterministic)
}
func (m *GetDictionaryLayerItemReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDictionaryLayerItemReq.Merge(m, src)
}
func (m *GetDictionaryLayerItemReq) XXX_Size() int {
	return xxx_messageInfo_GetDictionaryLayerItemReq.Size(m)
}
func (m *GetDictionaryLayerItemReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDictionaryLayerItemReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetDictionaryLayerItemReq proto.InternalMessageInfo

func (m *GetDictionaryLayerItemReq) GetDicType() string {
	if m != nil {
		return m.DicType
	}
	return ""
}

func (m *GetDictionaryLayerItemReq) GetDicCode() string {
	if m != nil {
		return m.DicCode
	}
	return ""
}

func (m *GetDictionaryLayerItemReq) GetDicPCode() string {
	if m != nil {
		return m.DicPCode
	}
	return ""
}

func (m *GetDictionaryLayerItemReq) GetDicLevel() string {
	if m != nil {
		return m.DicLevel
	}
	return ""
}

type DictionaryLayerItem struct {
	DicType              string   `protobuf:"bytes,1,opt,name=dicType,proto3" json:"dicType,omitempty"`
	DicCode              string   `protobuf:"bytes,2,opt,name=dicCode,proto3" json:"dicCode,omitempty"`
	DicPCode             string   `protobuf:"bytes,3,opt,name=dicPCode,proto3" json:"dicPCode,omitempty"`
	DicLevel             string   `protobuf:"bytes,4,opt,name=dicLevel,proto3" json:"dicLevel,omitempty"`
	DisPOrder            string   `protobuf:"bytes,5,opt,name=disPOrder,proto3" json:"disPOrder,omitempty"`
	Name                 string   `protobuf:"bytes,6,opt,name=name,proto3" json:"name,omitempty"`
	Memo                 string   `protobuf:"bytes,7,opt,name=memo,proto3" json:"memo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DictionaryLayerItem) Reset()         { *m = DictionaryLayerItem{} }
func (m *DictionaryLayerItem) String() string { return proto.CompactTextString(m) }
func (*DictionaryLayerItem) ProtoMessage()    {}
func (*DictionaryLayerItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_800d8474b3bfe66d, []int{15}
}

func (m *DictionaryLayerItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DictionaryLayerItem.Unmarshal(m, b)
}
func (m *DictionaryLayerItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DictionaryLayerItem.Marshal(b, m, deterministic)
}
func (m *DictionaryLayerItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DictionaryLayerItem.Merge(m, src)
}
func (m *DictionaryLayerItem) XXX_Size() int {
	return xxx_messageInfo_DictionaryLayerItem.Size(m)
}
func (m *DictionaryLayerItem) XXX_DiscardUnknown() {
	xxx_messageInfo_DictionaryLayerItem.DiscardUnknown(m)
}

var xxx_messageInfo_DictionaryLayerItem proto.InternalMessageInfo

func (m *DictionaryLayerItem) GetDicType() string {
	if m != nil {
		return m.DicType
	}
	return ""
}

func (m *DictionaryLayerItem) GetDicCode() string {
	if m != nil {
		return m.DicCode
	}
	return ""
}

func (m *DictionaryLayerItem) GetDicPCode() string {
	if m != nil {
		return m.DicPCode
	}
	return ""
}

func (m *DictionaryLayerItem) GetDicLevel() string {
	if m != nil {
		return m.DicLevel
	}
	return ""
}

func (m *DictionaryLayerItem) GetDisPOrder() string {
	if m != nil {
		return m.DisPOrder
	}
	return ""
}

func (m *DictionaryLayerItem) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *DictionaryLayerItem) GetMemo() string {
	if m != nil {
		return m.Memo
	}
	return ""
}

type GetDictionaryLayerItemResp struct {
	Items                []*DictionaryLayerItem `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Err                  *Error                 `protobuf:"bytes,2,opt,name=err,proto3" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *GetDictionaryLayerItemResp) Reset()         { *m = GetDictionaryLayerItemResp{} }
func (m *GetDictionaryLayerItemResp) String() string { return proto.CompactTextString(m) }
func (*GetDictionaryLayerItemResp) ProtoMessage()    {}
func (*GetDictionaryLayerItemResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_800d8474b3bfe66d, []int{16}
}

func (m *GetDictionaryLayerItemResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDictionaryLayerItemResp.Unmarshal(m, b)
}
func (m *GetDictionaryLayerItemResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDictionaryLayerItemResp.Marshal(b, m, deterministic)
}
func (m *GetDictionaryLayerItemResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDictionaryLayerItemResp.Merge(m, src)
}
func (m *GetDictionaryLayerItemResp) XXX_Size() int {
	return xxx_messageInfo_GetDictionaryLayerItemResp.Size(m)
}
func (m *GetDictionaryLayerItemResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDictionaryLayerItemResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetDictionaryLayerItemResp proto.InternalMessageInfo

func (m *GetDictionaryLayerItemResp) GetItems() []*DictionaryLayerItem {
	if m != nil {
		return m.Items
	}
	return nil
}

func (m *GetDictionaryLayerItemResp) GetErr() *Error {
	if m != nil {
		return m.Err
	}
	return nil
}

type GetDictionaryItemByPkReq struct {
	DicType              string   `protobuf:"bytes,1,opt,name=dicType,proto3" json:"dicType,omitempty"`
	DicCode              string   `protobuf:"bytes,2,opt,name=dicCode,proto3" json:"dicCode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetDictionaryItemByPkReq) Reset()         { *m = GetDictionaryItemByPkReq{} }
func (m *GetDictionaryItemByPkReq) String() string { return proto.CompactTextString(m) }
func (*GetDictionaryItemByPkReq) ProtoMessage()    {}
func (*GetDictionaryItemByPkReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_800d8474b3bfe66d, []int{17}
}

func (m *GetDictionaryItemByPkReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDictionaryItemByPkReq.Unmarshal(m, b)
}
func (m *GetDictionaryItemByPkReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDictionaryItemByPkReq.Marshal(b, m, deterministic)
}
func (m *GetDictionaryItemByPkReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDictionaryItemByPkReq.Merge(m, src)
}
func (m *GetDictionaryItemByPkReq) XXX_Size() int {
	return xxx_messageInfo_GetDictionaryItemByPkReq.Size(m)
}
func (m *GetDictionaryItemByPkReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDictionaryItemByPkReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetDictionaryItemByPkReq proto.InternalMessageInfo

func (m *GetDictionaryItemByPkReq) GetDicType() string {
	if m != nil {
		return m.DicType
	}
	return ""
}

func (m *GetDictionaryItemByPkReq) GetDicCode() string {
	if m != nil {
		return m.DicCode
	}
	return ""
}

type GetDictionaryItemByPkResp struct {
	Item                 *StaticGetDictionaryItem `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	Err                  *Error                   `protobuf:"bytes,2,opt,name=err,proto3" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *GetDictionaryItemByPkResp) Reset()         { *m = GetDictionaryItemByPkResp{} }
func (m *GetDictionaryItemByPkResp) String() string { return proto.CompactTextString(m) }
func (*GetDictionaryItemByPkResp) ProtoMessage()    {}
func (*GetDictionaryItemByPkResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_800d8474b3bfe66d, []int{18}
}

func (m *GetDictionaryItemByPkResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDictionaryItemByPkResp.Unmarshal(m, b)
}
func (m *GetDictionaryItemByPkResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDictionaryItemByPkResp.Marshal(b, m, deterministic)
}
func (m *GetDictionaryItemByPkResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDictionaryItemByPkResp.Merge(m, src)
}
func (m *GetDictionaryItemByPkResp) XXX_Size() int {
	return xxx_messageInfo_GetDictionaryItemByPkResp.Size(m)
}
func (m *GetDictionaryItemByPkResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDictionaryItemByPkResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetDictionaryItemByPkResp proto.InternalMessageInfo

func (m *GetDictionaryItemByPkResp) GetItem() *StaticGetDictionaryItem {
	if m != nil {
		return m.Item
	}
	return nil
}

func (m *GetDictionaryItemByPkResp) GetErr() *Error {
	if m != nil {
		return m.Err
	}
	return nil
}

type UnionPayBankListField struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Code                 string   `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	UpdatedAt            string   `protobuf:"bytes,4,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnionPayBankListField) Reset()         { *m = UnionPayBankListField{} }
func (m *UnionPayBankListField) String() string { return proto.CompactTextString(m) }
func (*UnionPayBankListField) ProtoMessage()    {}
func (*UnionPayBankListField) Descriptor() ([]byte, []int) {
	return fileDescriptor_800d8474b3bfe66d, []int{19}
}

func (m *UnionPayBankListField) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnionPayBankListField.Unmarshal(m, b)
}
func (m *UnionPayBankListField) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnionPayBankListField.Marshal(b, m, deterministic)
}
func (m *UnionPayBankListField) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnionPayBankListField.Merge(m, src)
}
func (m *UnionPayBankListField) XXX_Size() int {
	return xxx_messageInfo_UnionPayBankListField.Size(m)
}
func (m *UnionPayBankListField) XXX_DiscardUnknown() {
	xxx_messageInfo_UnionPayBankListField.DiscardUnknown(m)
}

var xxx_messageInfo_UnionPayBankListField proto.InternalMessageInfo

func (m *UnionPayBankListField) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UnionPayBankListField) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *UnionPayBankListField) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UnionPayBankListField) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

type GetUnionPayBankListRequest struct {
	Item                 *UnionPayBankListField `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	Page                 int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Size                 int32                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *GetUnionPayBankListRequest) Reset()         { *m = GetUnionPayBankListRequest{} }
func (m *GetUnionPayBankListRequest) String() string { return proto.CompactTextString(m) }
func (*GetUnionPayBankListRequest) ProtoMessage()    {}
func (*GetUnionPayBankListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_800d8474b3bfe66d, []int{20}
}

func (m *GetUnionPayBankListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUnionPayBankListRequest.Unmarshal(m, b)
}
func (m *GetUnionPayBankListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUnionPayBankListRequest.Marshal(b, m, deterministic)
}
func (m *GetUnionPayBankListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUnionPayBankListRequest.Merge(m, src)
}
func (m *GetUnionPayBankListRequest) XXX_Size() int {
	return xxx_messageInfo_GetUnionPayBankListRequest.Size(m)
}
func (m *GetUnionPayBankListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUnionPayBankListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetUnionPayBankListRequest proto.InternalMessageInfo

func (m *GetUnionPayBankListRequest) GetItem() *UnionPayBankListField {
	if m != nil {
		return m.Item
	}
	return nil
}

func (m *GetUnionPayBankListRequest) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *GetUnionPayBankListRequest) GetSize() int32 {
	if m != nil {
		return m.Size
	}
	return 0
}

type GetUnionPayBankListReply struct {
	Items                []*UnionPayBankListField `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Page                 int32                    `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Size                 int32                    `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	Count                int32                    `protobuf:"varint,4,opt,name=count,proto3" json:"count,omitempty"`
	Err                  *Error                   `protobuf:"bytes,5,opt,name=err,proto3" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *GetUnionPayBankListReply) Reset()         { *m = GetUnionPayBankListReply{} }
func (m *GetUnionPayBankListReply) String() string { return proto.CompactTextString(m) }
func (*GetUnionPayBankListReply) ProtoMessage()    {}
func (*GetUnionPayBankListReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_800d8474b3bfe66d, []int{21}
}

func (m *GetUnionPayBankListReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUnionPayBankListReply.Unmarshal(m, b)
}
func (m *GetUnionPayBankListReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUnionPayBankListReply.Marshal(b, m, deterministic)
}
func (m *GetUnionPayBankListReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUnionPayBankListReply.Merge(m, src)
}
func (m *GetUnionPayBankListReply) XXX_Size() int {
	return xxx_messageInfo_GetUnionPayBankListReply.Size(m)
}
func (m *GetUnionPayBankListReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUnionPayBankListReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetUnionPayBankListReply proto.InternalMessageInfo

func (m *GetUnionPayBankListReply) GetItems() []*UnionPayBankListField {
	if m != nil {
		return m.Items
	}
	return nil
}

func (m *GetUnionPayBankListReply) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *GetUnionPayBankListReply) GetSize() int32 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *GetUnionPayBankListReply) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *GetUnionPayBankListReply) GetErr() *Error {
	if m != nil {
		return m.Err
	}
	return nil
}

type UnionPayMccField struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Code                 string   `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Category             string   `protobuf:"bytes,4,opt,name=category,proto3" json:"category,omitempty"`
	CategoryType         string   `protobuf:"bytes,5,opt,name=categoryType,proto3" json:"categoryType,omitempty"`
	Industry             string   `protobuf:"bytes,6,opt,name=industry,proto3" json:"industry,omitempty"`
	Status               string   `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	UpdatedAt            string   `protobuf:"bytes,8,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnionPayMccField) Reset()         { *m = UnionPayMccField{} }
func (m *UnionPayMccField) String() string { return proto.CompactTextString(m) }
func (*UnionPayMccField) ProtoMessage()    {}
func (*UnionPayMccField) Descriptor() ([]byte, []int) {
	return fileDescriptor_800d8474b3bfe66d, []int{22}
}

func (m *UnionPayMccField) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnionPayMccField.Unmarshal(m, b)
}
func (m *UnionPayMccField) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnionPayMccField.Marshal(b, m, deterministic)
}
func (m *UnionPayMccField) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnionPayMccField.Merge(m, src)
}
func (m *UnionPayMccField) XXX_Size() int {
	return xxx_messageInfo_UnionPayMccField.Size(m)
}
func (m *UnionPayMccField) XXX_DiscardUnknown() {
	xxx_messageInfo_UnionPayMccField.DiscardUnknown(m)
}

var xxx_messageInfo_UnionPayMccField proto.InternalMessageInfo

func (m *UnionPayMccField) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UnionPayMccField) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *UnionPayMccField) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UnionPayMccField) GetCategory() string {
	if m != nil {
		return m.Category
	}
	return ""
}

func (m *UnionPayMccField) GetCategoryType() string {
	if m != nil {
		return m.CategoryType
	}
	return ""
}

func (m *UnionPayMccField) GetIndustry() string {
	if m != nil {
		return m.Industry
	}
	return ""
}

func (m *UnionPayMccField) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *UnionPayMccField) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

type FindUnionPayMccListRequest struct {
	Item                 *UnionPayMccField `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	Page                 int32             `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Size                 int32             `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *FindUnionPayMccListRequest) Reset()         { *m = FindUnionPayMccListRequest{} }
func (m *FindUnionPayMccListRequest) String() string { return proto.CompactTextString(m) }
func (*FindUnionPayMccListRequest) ProtoMessage()    {}
func (*FindUnionPayMccListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_800d8474b3bfe66d, []int{23}
}

func (m *FindUnionPayMccListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindUnionPayMccListRequest.Unmarshal(m, b)
}
func (m *FindUnionPayMccListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindUnionPayMccListRequest.Marshal(b, m, deterministic)
}
func (m *FindUnionPayMccListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindUnionPayMccListRequest.Merge(m, src)
}
func (m *FindUnionPayMccListRequest) XXX_Size() int {
	return xxx_messageInfo_FindUnionPayMccListRequest.Size(m)
}
func (m *FindUnionPayMccListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FindUnionPayMccListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FindUnionPayMccListRequest proto.InternalMessageInfo

func (m *FindUnionPayMccListRequest) GetItem() *UnionPayMccField {
	if m != nil {
		return m.Item
	}
	return nil
}

func (m *FindUnionPayMccListRequest) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *FindUnionPayMccListRequest) GetSize() int32 {
	if m != nil {
		return m.Size
	}
	return 0
}

type FindUnionPayMccListReply struct {
	Items                []*UnionPayMccField `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Page                 int32               `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Size                 int32               `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	Count                int32               `protobuf:"varint,4,opt,name=count,proto3" json:"count,omitempty"`
	Err                  *Error              `protobuf:"bytes,5,opt,name=err,proto3" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *FindUnionPayMccListReply) Reset()         { *m = FindUnionPayMccListReply{} }
func (m *FindUnionPayMccListReply) String() string { return proto.CompactTextString(m) }
func (*FindUnionPayMccListReply) ProtoMessage()    {}
func (*FindUnionPayMccListReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_800d8474b3bfe66d, []int{24}
}

func (m *FindUnionPayMccListReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindUnionPayMccListReply.Unmarshal(m, b)
}
func (m *FindUnionPayMccListReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindUnionPayMccListReply.Marshal(b, m, deterministic)
}
func (m *FindUnionPayMccListReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindUnionPayMccListReply.Merge(m, src)
}
func (m *FindUnionPayMccListReply) XXX_Size() int {
	return xxx_messageInfo_FindUnionPayMccListReply.Size(m)
}
func (m *FindUnionPayMccListReply) XXX_DiscardUnknown() {
	xxx_messageInfo_FindUnionPayMccListReply.DiscardUnknown(m)
}

var xxx_messageInfo_FindUnionPayMccListReply proto.InternalMessageInfo

func (m *FindUnionPayMccListReply) GetItems() []*UnionPayMccField {
	if m != nil {
		return m.Items
	}
	return nil
}

func (m *FindUnionPayMccListReply) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *FindUnionPayMccListReply) GetSize() int32 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *FindUnionPayMccListReply) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *FindUnionPayMccListReply) GetErr() *Error {
	if m != nil {
		return m.Err
	}
	return nil
}

func init() {
	proto.RegisterType((*InsProdBizFeeMapInfoField)(nil), "pb.InsProdBizFeeMapInfoField")
	proto.RegisterType((*GetInsProdBizFeeMapInfoReply)(nil), "pb.GetInsProdBizFeeMapInfoReply")
	proto.RegisterType((*GetInsProdBizFeeMapInfoRequest)(nil), "pb.GetInsProdBizFeeMapInfoRequest")
	proto.RegisterType((*StaticSyncDataReq)(nil), "pb.StaticSyncDataReq")
	proto.RegisterType((*StaticSyncDataResp)(nil), "pb.StaticSyncDataResp")
	proto.RegisterType((*StaticGetDictionaryItemReq)(nil), "pb.StaticGetDictionaryItemReq")
	proto.RegisterType((*StaticGetDictionaryItemResp)(nil), "pb.StaticGetDictionaryItemResp")
	proto.RegisterType((*StaticGetDictionaryItem)(nil), "pb.StaticGetDictionaryItem")
	proto.RegisterType((*StaticGetDicByProdAndBizReq)(nil), "pb.StaticGetDicByProdAndBizReq")
	proto.RegisterType((*StaticGetDicByProdAndBizResp)(nil), "pb.StaticGetDicByProdAndBizResp")
	proto.RegisterType((*StaticGetDicByInsCmpCdReq)(nil), "pb.StaticGetDicByInsCmpCdReq")
	proto.RegisterType((*StaticGetDicByInsCmpCdResp)(nil), "pb.StaticGetDicByInsCmpCdResp")
	proto.RegisterType((*StaticCheckValuesReq)(nil), "pb.StaticCheckValuesReq")
	proto.RegisterType((*StaticCheckValuesResp)(nil), "pb.StaticCheckValuesResp")
	proto.RegisterType((*GetDictionaryLayerItemReq)(nil), "pb.GetDictionaryLayerItemReq")
	proto.RegisterType((*DictionaryLayerItem)(nil), "pb.DictionaryLayerItem")
	proto.RegisterType((*GetDictionaryLayerItemResp)(nil), "pb.GetDictionaryLayerItemResp")
	proto.RegisterType((*GetDictionaryItemByPkReq)(nil), "pb.GetDictionaryItemByPkReq")
	proto.RegisterType((*GetDictionaryItemByPkResp)(nil), "pb.GetDictionaryItemByPkResp")
	proto.RegisterType((*UnionPayBankListField)(nil), "pb.UnionPayBankListField")
	proto.RegisterType((*GetUnionPayBankListRequest)(nil), "pb.GetUnionPayBankListRequest")
	proto.RegisterType((*GetUnionPayBankListReply)(nil), "pb.GetUnionPayBankListReply")
	proto.RegisterType((*UnionPayMccField)(nil), "pb.UnionPayMccField")
	proto.RegisterType((*FindUnionPayMccListRequest)(nil), "pb.FindUnionPayMccListRequest")
	proto.RegisterType((*FindUnionPayMccListReply)(nil), "pb.FindUnionPayMccListReply")
}

func init() { proto.RegisterFile("static.proto", fileDescriptor_800d8474b3bfe66d) }

var fileDescriptor_800d8474b3bfe66d = []byte{
	// 1179 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x58, 0xcd, 0x52, 0xe3, 0x46,
	0x10, 0xc6, 0x18, 0x7b, 0x4d, 0x9b, 0x6c, 0x60, 0xf8, 0x1b, 0x84, 0x21, 0x94, 0x4e, 0x54, 0xaa,
	0x96, 0x0d, 0xb0, 0xbf, 0x95, 0x43, 0x0a, 0x4c, 0xb1, 0xe5, 0x0a, 0x7f, 0x25, 0x60, 0xab, 0x72,
	0x14, 0xd2, 0x2c, 0xab, 0x60, 0x49, 0x83, 0x46, 0xde, 0x94, 0x78, 0x81, 0x7d, 0x8e, 0xe4, 0x90,
	0x57, 0xc9, 0x23, 0xe4, 0x92, 0x87, 0x49, 0xcd, 0x8f, 0x64, 0x8d, 0x2c, 0x39, 0xec, 0x6e, 0xd8,
	0x9b, 0xba, 0xfb, 0xeb, 0x9e, 0x9e, 0xfe, 0xba, 0x67, 0xc6, 0x86, 0x19, 0x16, 0xdb, 0xb1, 0xe7,
	0x6c, 0xd1, 0x28, 0x8c, 0x43, 0x34, 0x49, 0xaf, 0x8c, 0x36, 0x89, 0xa2, 0x30, 0x92, 0x0a, 0xf3,
	0x63, 0x03, 0x56, 0x7a, 0x01, 0x3b, 0x8b, 0x42, 0x77, 0xdf, 0xbb, 0x3b, 0x24, 0xe4, 0xd8, 0xa6,
	0xbd, 0xe0, 0x5d, 0x78, 0xe8, 0x91, 0xbe, 0x8b, 0x96, 0xa0, 0xc9, 0x2d, 0x5d, 0x17, 0xd7, 0x36,
	0x6a, 0x9b, 0xd3, 0x96, 0x92, 0xd0, 0x02, 0x34, 0xf6, 0xbd, 0xbb, 0xae, 0x8b, 0x27, 0x85, 0x5a,
	0x0a, 0x1c, 0x7d, 0xec, 0x38, 0xc7, 0x17, 0x14, 0xd7, 0x25, 0x5a, 0x4a, 0x4a, 0x7f, 0x7e, 0x41,
	0xf1, 0x54, 0xa6, 0x3f, 0xbf, 0xa0, 0x68, 0x03, 0xda, 0xbd, 0x80, 0x1d, 0x12, 0x22, 0x63, 0x35,
	0x84, 0x31, 0xaf, 0xd2, 0x10, 0x27, 0x3e, 0x6e, 0x16, 0x10, 0x27, 0x3e, 0x47, 0x1c, 0xb3, 0x6b,
	0x8b, 0xb0, 0x0f, 0x87, 0x7d, 0x77, 0x1b, 0x3f, 0x92, 0x88, 0x9c, 0x4a, 0x47, 0xec, 0xe0, 0x56,
	0x11, 0xb1, 0xa3, 0x23, 0x76, 0xf1, 0x74, 0x11, 0xb1, 0xab, 0x23, 0x9e, 0x61, 0x28, 0x22, 0x9e,
	0xe9, 0x88, 0xe7, 0xb8, 0x5d, 0x44, 0x3c, 0xd7, 0x11, 0x2f, 0xf0, 0x4c, 0x11, 0xf1, 0x42, 0x47,
	0xbc, 0xc4, 0xdf, 0x14, 0x11, 0x2f, 0x75, 0xc4, 0x2b, 0xfc, 0xb8, 0x88, 0x78, 0xa5, 0x23, 0x5e,
	0xe3, 0x6f, 0x8b, 0x88, 0xd7, 0xc8, 0x84, 0x99, 0x5c, 0x79, 0x7e, 0xc0, 0xb3, 0x02, 0xa2, 0xe9,
	0x90, 0x01, 0x2d, 0x8b, 0x38, 0xa7, 0x34, 0xea, 0x1d, 0xe0, 0x39, 0x61, 0xcf, 0x64, 0xd4, 0x81,
	0x69, 0x8b, 0x38, 0x97, 0xd4, 0x3d, 0xa5, 0x11, 0x46, 0xc2, 0x38, 0x54, 0x70, 0xcf, 0x6e, 0x44,
	0xec, 0x98, 0xec, 0xc5, 0x78, 0x5e, 0x7a, 0xa6, 0x32, 0xf7, 0xbc, 0xa4, 0xae, 0x1d, 0x13, 0x77,
	0x2f, 0xc6, 0x0b, 0xd2, 0x33, 0x53, 0x98, 0x14, 0x3a, 0x6f, 0x48, 0x5c, 0xd6, 0x8b, 0x16, 0xa1,
	0xfd, 0x04, 0xed, 0x42, 0xc3, 0x8b, 0x89, 0xcf, 0x70, 0x6d, 0xa3, 0xbe, 0xd9, 0xde, 0x59, 0xdb,
	0xa2, 0x57, 0x5b, 0x95, 0x9d, 0x6b, 0x49, 0x2c, 0x5a, 0x85, 0x3a, 0x89, 0x22, 0xd1, 0xa6, 0xed,
	0x9d, 0x69, 0xee, 0x22, 0x9a, 0xdf, 0xe2, 0x5a, 0x73, 0x03, 0xd6, 0x2b, 0x57, 0xbc, 0x1d, 0x10,
	0x16, 0x9b, 0xdb, 0x30, 0x77, 0x2e, 0xc6, 0xe7, 0x3c, 0x09, 0x9c, 0x03, 0x3b, 0xb6, 0x2d, 0x72,
	0xcb, 0xb7, 0x71, 0x61, 0x5f, 0xf5, 0xc9, 0x89, 0xed, 0x13, 0x35, 0x17, 0x43, 0x85, 0xd9, 0x03,
	0x54, 0x74, 0x61, 0x62, 0x04, 0x22, 0xc2, 0x06, 0xfd, 0x58, 0x38, 0xb4, 0x2c, 0x25, 0x8d, 0xcf,
	0xef, 0x57, 0x30, 0x64, 0xa8, 0x37, 0x24, 0x3e, 0xf0, 0x9c, 0xd8, 0x0b, 0x03, 0x3b, 0x4a, 0x7a,
	0x31, 0xf1, 0x79, 0x1a, 0x18, 0x1e, 0xb9, 0x9e, 0x73, 0x91, 0xd0, 0x34, 0x89, 0x54, 0x54, 0x96,
	0x6e, 0xe8, 0x12, 0x35, 0x9f, 0xa9, 0xa8, 0x2c, 0x22, 0xf1, 0x7a, 0x66, 0x11, 0x69, 0xfb, 0xb0,
	0x5a, 0xb9, 0x16, 0xa3, 0x68, 0x5b, 0x2f, 0xfe, 0x2a, 0xcf, 0xb4, 0x0a, 0x7f, 0x9f, 0xd2, 0x5f,
	0xc3, 0x72, 0x85, 0xfb, 0xff, 0xbc, 0xaf, 0x9f, 0xf5, 0x7d, 0xed, 0x27, 0x9c, 0xeb, 0xbd, 0x80,
	0xd3, 0xcd, 0x8b, 0xb8, 0x04, 0x4d, 0xaa, 0x1d, 0x70, 0x34, 0x3b, 0xe0, 0xae, 0xf2, 0x07, 0x9c,
	0x10, 0xcc, 0x00, 0x3a, 0xd5, 0xc1, 0x1e, 0xa0, 0x4a, 0x3f, 0xc1, 0x8a, 0xbe, 0x5e, 0x2f, 0x60,
	0x5d, 0x9f, 0x76, 0x5d, 0x9e, 0xba, 0x09, 0x33, 0x5c, 0x0c, 0x7d, 0x6a, 0x07, 0x49, 0xb6, 0x01,
	0x4d, 0x67, 0xf6, 0xf5, 0x0e, 0xca, 0x07, 0x78, 0x80, 0x74, 0xff, 0xa8, 0xc1, 0x82, 0xf4, 0xef,
	0xbe, 0x27, 0xce, 0xcd, 0x5b, 0xbb, 0x3f, 0x20, 0xec, 0x93, 0xab, 0xcc, 0xc9, 0x8c, 0x23, 0x3b,
	0x60, 0x5d, 0x37, 0x25, 0x53, 0x89, 0x7c, 0xcb, 0x5e, 0x7e, 0xcb, 0xf2, 0x3a, 0xd1, 0x74, 0x68,
	0x1d, 0xe0, 0xdd, 0x6f, 0x6e, 0x2f, 0x60, 0x3d, 0x37, 0xbb, 0x53, 0x72, 0x1a, 0xf3, 0x08, 0x16,
	0x4b, 0x72, 0xfc, 0xdc, 0x11, 0xfd, 0x58, 0x83, 0x15, 0xad, 0x58, 0x47, 0x76, 0x42, 0xa2, 0x2f,
	0x19, 0x51, 0x03, 0x5a, 0xae, 0xe7, 0x9c, 0x09, 0x93, 0xdc, 0x7e, 0x26, 0x2b, 0xdb, 0x11, 0xf9,
	0x40, 0xfa, 0x6a, 0xef, 0x99, 0x6c, 0xfe, 0x55, 0x83, 0xf9, 0x92, 0x34, 0xbe, 0x66, 0x0e, 0xfc,
	0x64, 0x74, 0x3d, 0x76, 0x76, 0x1a, 0xb9, 0x24, 0x52, 0xa5, 0x1f, 0x2a, 0x10, 0x82, 0xa9, 0x80,
	0x4f, 0xa8, 0xbc, 0xc5, 0xc5, 0x37, 0xd7, 0xf9, 0xc4, 0x0f, 0xd5, 0xbd, 0x2d, 0xbe, 0xcd, 0xf7,
	0x60, 0x54, 0x95, 0x94, 0x51, 0xf4, 0x44, 0x6f, 0xda, 0x65, 0x4e, 0x48, 0x19, 0xf6, 0x3e, 0x0d,
	0x7b, 0x02, 0x78, 0xa4, 0xd3, 0xf7, 0x93, 0xb3, 0x9b, 0xcf, 0xe4, 0xce, 0xf4, 0x0a, 0xcd, 0x30,
	0x8c, 0xc7, 0x28, 0x7a, 0x0a, 0x53, 0x3c, 0x25, 0x11, 0xed, 0x3f, 0x86, 0x4d, 0x00, 0xc7, 0xa7,
	0xee, 0xc3, 0xe2, 0x65, 0xe0, 0x85, 0xc1, 0x99, 0x9d, 0xec, 0xdb, 0xc1, 0xcd, 0x91, 0xc7, 0x62,
	0xf9, 0x64, 0x7b, 0x0c, 0x93, 0x9e, 0x9c, 0xb3, 0xba, 0x35, 0xe9, 0xb9, 0xbc, 0xc2, 0xce, 0x30,
	0x55, 0xf1, 0x9d, 0x31, 0x51, 0xcf, 0x31, 0xd1, 0x81, 0xe9, 0x41, 0x76, 0x39, 0x4b, 0x62, 0x87,
	0x0a, 0x93, 0x09, 0x4e, 0x8a, 0x2b, 0xaa, 0x6b, 0x12, 0x3d, 0xd1, 0xb6, 0xb6, 0xc2, 0x53, 0x2d,
	0x4d, 0x4e, 0x6d, 0x0c, 0xc1, 0x14, 0xb5, 0xaf, 0x65, 0x4a, 0x0d, 0x4b, 0x7c, 0x73, 0x1d, 0xf3,
	0xee, 0x64, 0x4a, 0x0d, 0x4b, 0x7c, 0x9b, 0x7f, 0xd6, 0x04, 0x3f, 0xa3, 0xab, 0xf2, 0xe7, 0xc0,
	0x53, 0xbd, 0x0f, 0xc6, 0x2c, 0xaa, 0x3a, 0xe1, 0x9e, 0xab, 0xf2, 0x43, 0xc9, 0x09, 0x07, 0x81,
	0x2c, 0x42, 0xc3, 0x92, 0x42, 0x4a, 0x46, 0xa3, 0x94, 0x8c, 0x7f, 0x6a, 0x30, 0x9b, 0xae, 0x7d,
	0xec, 0x38, 0x5f, 0x46, 0x84, 0x01, 0x2d, 0xc7, 0x8e, 0xc9, 0x75, 0x18, 0x25, 0xe9, 0x80, 0xa5,
	0x32, 0x3f, 0x00, 0xd3, 0x6f, 0xd1, 0x99, 0x72, 0xc6, 0x34, 0x1d, 0xf7, 0xf7, 0x02, 0x77, 0xc0,
	0xe2, 0x28, 0x51, 0xa3, 0x96, 0xc9, 0xfc, 0x8c, 0xe3, 0x3f, 0x07, 0x06, 0x4c, 0x0d, 0x9c, 0x92,
	0x74, 0xf2, 0x5b, 0x45, 0xf2, 0x03, 0x30, 0x0e, 0xbd, 0xc0, 0xcd, 0xed, 0x30, 0x4f, 0xfe, 0xa6,
	0x46, 0xfe, 0x42, 0x9e, 0x87, 0xb4, 0x16, 0x9f, 0xc8, 0xfb, 0xef, 0x35, 0xc0, 0xa5, 0x0b, 0x72,
	0xde, 0xbf, 0xd7, 0x79, 0x2f, 0x5f, 0xef, 0xc1, 0x29, 0xdf, 0xf9, 0xbb, 0x09, 0x4d, 0x39, 0xbe,
	0xe8, 0x47, 0x68, 0xa5, 0x6f, 0x3d, 0xb4, 0x38, 0x1c, 0xeb, 0xdc, 0x93, 0xd1, 0x58, 0x2a, 0x53,
	0x33, 0x6a, 0x4e, 0xa0, 0xb7, 0x30, 0x37, 0xfa, 0x04, 0x5a, 0x1f, 0x77, 0x38, 0x90, 0x5b, 0xe3,
	0xbb, 0xb1, 0x76, 0x11, 0xf7, 0x17, 0x40, 0xa3, 0x8f, 0x14, 0x34, 0xe2, 0x58, 0x78, 0x0f, 0x19,
	0x1b, 0xe3, 0x01, 0x22, 0xf4, 0x39, 0xcc, 0x16, 0x9f, 0x13, 0x68, 0x6d, 0xd4, 0x2f, 0xf7, 0x56,
	0x31, 0xd6, 0xc7, 0x99, 0x45, 0xd0, 0x03, 0x68, 0xe7, 0x2e, 0x64, 0x84, 0x87, 0x0e, 0xfa, 0x5b,
	0xc2, 0x58, 0xa9, 0xb0, 0xa8, 0x5d, 0x2f, 0x95, 0x5f, 0x1d, 0x32, 0xc1, 0xca, 0x9b, 0x5a, 0x26,
	0x58, 0x7d, 0xeb, 0x08, 0xa2, 0x16, 0x4b, 0xcf, 0x76, 0xd4, 0x19, 0x71, 0xcd, 0x5d, 0x23, 0xc6,
	0xda, 0x18, 0xab, 0x88, 0x7b, 0x09, 0xf3, 0x25, 0x67, 0x1c, 0x4a, 0x13, 0xaa, 0x38, 0x72, 0x8d,
	0x4e, 0xa5, 0x9d, 0xf6, 0x13, 0x19, 0xb6, 0x64, 0x84, 0x64, 0xd8, 0xea, 0x61, 0x96, 0x61, 0xab,
	0x66, 0xcf, 0x9c, 0x40, 0x36, 0x2c, 0x57, 0xfc, 0x64, 0x42, 0xa6, 0xca, 0x68, 0xcc, 0xef, 0x29,
	0xd9, 0x5e, 0xe3, 0x7e, 0xe5, 0x99, 0x13, 0x57, 0x4d, 0xf1, 0xc7, 0xc4, 0xee, 0xbf, 0x01, 0x00,
	0x00, 0xff, 0xff, 0xd8, 0x04, 0x50, 0x7c, 0xb9, 0x10, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// StaticClient is the client API for Static service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type StaticClient interface {
	SyncData(ctx context.Context, in *StaticSyncDataReq, opts ...grpc.CallOption) (*StaticSyncDataResp, error)
	GetDictionaryItem(ctx context.Context, in *StaticGetDictionaryItemReq, opts ...grpc.CallOption) (*StaticGetDictionaryItemResp, error)
	GetDicByProdAndBiz(ctx context.Context, in *StaticGetDicByProdAndBizReq, opts ...grpc.CallOption) (*StaticGetDicByProdAndBizResp, error)
	GetDicByInsCmpCd(ctx context.Context, in *StaticGetDicByInsCmpCdReq, opts ...grpc.CallOption) (*StaticGetDicByInsCmpCdResp, error)
	CheckValues(ctx context.Context, in *StaticCheckValuesReq, opts ...grpc.CallOption) (*StaticCheckValuesResp, error)
	GetDictionaryLayerItem(ctx context.Context, in *GetDictionaryLayerItemReq, opts ...grpc.CallOption) (*GetDictionaryLayerItemResp, error)
	GetDictionaryItemByPk(ctx context.Context, in *GetDictionaryItemByPkReq, opts ...grpc.CallOption) (*GetDictionaryItemByPkResp, error)
	GetUnionPayBankList(ctx context.Context, in *GetUnionPayBankListRequest, opts ...grpc.CallOption) (*GetUnionPayBankListReply, error)
	FindUnionPayMccList(ctx context.Context, in *FindUnionPayMccListRequest, opts ...grpc.CallOption) (*FindUnionPayMccListReply, error)
	GetInsProdBizFeeMapInfo(ctx context.Context, in *GetInsProdBizFeeMapInfoRequest, opts ...grpc.CallOption) (*GetInsProdBizFeeMapInfoReply, error)
}

type staticClient struct {
	cc *grpc.ClientConn
}

func NewStaticClient(cc *grpc.ClientConn) StaticClient {
	return &staticClient{cc}
}

func (c *staticClient) SyncData(ctx context.Context, in *StaticSyncDataReq, opts ...grpc.CallOption) (*StaticSyncDataResp, error) {
	out := new(StaticSyncDataResp)
	err := c.cc.Invoke(ctx, "/pb.Static/SyncData", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *staticClient) GetDictionaryItem(ctx context.Context, in *StaticGetDictionaryItemReq, opts ...grpc.CallOption) (*StaticGetDictionaryItemResp, error) {
	out := new(StaticGetDictionaryItemResp)
	err := c.cc.Invoke(ctx, "/pb.Static/GetDictionaryItem", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *staticClient) GetDicByProdAndBiz(ctx context.Context, in *StaticGetDicByProdAndBizReq, opts ...grpc.CallOption) (*StaticGetDicByProdAndBizResp, error) {
	out := new(StaticGetDicByProdAndBizResp)
	err := c.cc.Invoke(ctx, "/pb.Static/GetDicByProdAndBiz", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *staticClient) GetDicByInsCmpCd(ctx context.Context, in *StaticGetDicByInsCmpCdReq, opts ...grpc.CallOption) (*StaticGetDicByInsCmpCdResp, error) {
	out := new(StaticGetDicByInsCmpCdResp)
	err := c.cc.Invoke(ctx, "/pb.Static/GetDicByInsCmpCd", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *staticClient) CheckValues(ctx context.Context, in *StaticCheckValuesReq, opts ...grpc.CallOption) (*StaticCheckValuesResp, error) {
	out := new(StaticCheckValuesResp)
	err := c.cc.Invoke(ctx, "/pb.Static/CheckValues", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *staticClient) GetDictionaryLayerItem(ctx context.Context, in *GetDictionaryLayerItemReq, opts ...grpc.CallOption) (*GetDictionaryLayerItemResp, error) {
	out := new(GetDictionaryLayerItemResp)
	err := c.cc.Invoke(ctx, "/pb.Static/GetDictionaryLayerItem", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *staticClient) GetDictionaryItemByPk(ctx context.Context, in *GetDictionaryItemByPkReq, opts ...grpc.CallOption) (*GetDictionaryItemByPkResp, error) {
	out := new(GetDictionaryItemByPkResp)
	err := c.cc.Invoke(ctx, "/pb.Static/GetDictionaryItemByPk", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *staticClient) GetUnionPayBankList(ctx context.Context, in *GetUnionPayBankListRequest, opts ...grpc.CallOption) (*GetUnionPayBankListReply, error) {
	out := new(GetUnionPayBankListReply)
	err := c.cc.Invoke(ctx, "/pb.Static/GetUnionPayBankList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *staticClient) FindUnionPayMccList(ctx context.Context, in *FindUnionPayMccListRequest, opts ...grpc.CallOption) (*FindUnionPayMccListReply, error) {
	out := new(FindUnionPayMccListReply)
	err := c.cc.Invoke(ctx, "/pb.Static/FindUnionPayMccList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *staticClient) GetInsProdBizFeeMapInfo(ctx context.Context, in *GetInsProdBizFeeMapInfoRequest, opts ...grpc.CallOption) (*GetInsProdBizFeeMapInfoReply, error) {
	out := new(GetInsProdBizFeeMapInfoReply)
	err := c.cc.Invoke(ctx, "/pb.Static/GetInsProdBizFeeMapInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StaticServer is the server API for Static service.
type StaticServer interface {
	SyncData(context.Context, *StaticSyncDataReq) (*StaticSyncDataResp, error)
	GetDictionaryItem(context.Context, *StaticGetDictionaryItemReq) (*StaticGetDictionaryItemResp, error)
	GetDicByProdAndBiz(context.Context, *StaticGetDicByProdAndBizReq) (*StaticGetDicByProdAndBizResp, error)
	GetDicByInsCmpCd(context.Context, *StaticGetDicByInsCmpCdReq) (*StaticGetDicByInsCmpCdResp, error)
	CheckValues(context.Context, *StaticCheckValuesReq) (*StaticCheckValuesResp, error)
	GetDictionaryLayerItem(context.Context, *GetDictionaryLayerItemReq) (*GetDictionaryLayerItemResp, error)
	GetDictionaryItemByPk(context.Context, *GetDictionaryItemByPkReq) (*GetDictionaryItemByPkResp, error)
	GetUnionPayBankList(context.Context, *GetUnionPayBankListRequest) (*GetUnionPayBankListReply, error)
	FindUnionPayMccList(context.Context, *FindUnionPayMccListRequest) (*FindUnionPayMccListReply, error)
	GetInsProdBizFeeMapInfo(context.Context, *GetInsProdBizFeeMapInfoRequest) (*GetInsProdBizFeeMapInfoReply, error)
}

// UnimplementedStaticServer can be embedded to have forward compatible implementations.
type UnimplementedStaticServer struct {
}

func (*UnimplementedStaticServer) SyncData(ctx context.Context, req *StaticSyncDataReq) (*StaticSyncDataResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SyncData not implemented")
}
func (*UnimplementedStaticServer) GetDictionaryItem(ctx context.Context, req *StaticGetDictionaryItemReq) (*StaticGetDictionaryItemResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDictionaryItem not implemented")
}
func (*UnimplementedStaticServer) GetDicByProdAndBiz(ctx context.Context, req *StaticGetDicByProdAndBizReq) (*StaticGetDicByProdAndBizResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDicByProdAndBiz not implemented")
}
func (*UnimplementedStaticServer) GetDicByInsCmpCd(ctx context.Context, req *StaticGetDicByInsCmpCdReq) (*StaticGetDicByInsCmpCdResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDicByInsCmpCd not implemented")
}
func (*UnimplementedStaticServer) CheckValues(ctx context.Context, req *StaticCheckValuesReq) (*StaticCheckValuesResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckValues not implemented")
}
func (*UnimplementedStaticServer) GetDictionaryLayerItem(ctx context.Context, req *GetDictionaryLayerItemReq) (*GetDictionaryLayerItemResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDictionaryLayerItem not implemented")
}
func (*UnimplementedStaticServer) GetDictionaryItemByPk(ctx context.Context, req *GetDictionaryItemByPkReq) (*GetDictionaryItemByPkResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDictionaryItemByPk not implemented")
}
func (*UnimplementedStaticServer) GetUnionPayBankList(ctx context.Context, req *GetUnionPayBankListRequest) (*GetUnionPayBankListReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUnionPayBankList not implemented")
}
func (*UnimplementedStaticServer) FindUnionPayMccList(ctx context.Context, req *FindUnionPayMccListRequest) (*FindUnionPayMccListReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindUnionPayMccList not implemented")
}
func (*UnimplementedStaticServer) GetInsProdBizFeeMapInfo(ctx context.Context, req *GetInsProdBizFeeMapInfoRequest) (*GetInsProdBizFeeMapInfoReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetInsProdBizFeeMapInfo not implemented")
}

func RegisterStaticServer(s *grpc.Server, srv StaticServer) {
	s.RegisterService(&_Static_serviceDesc, srv)
}

func _Static_SyncData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StaticSyncDataReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StaticServer).SyncData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Static/SyncData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StaticServer).SyncData(ctx, req.(*StaticSyncDataReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Static_GetDictionaryItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StaticGetDictionaryItemReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StaticServer).GetDictionaryItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Static/GetDictionaryItem",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StaticServer).GetDictionaryItem(ctx, req.(*StaticGetDictionaryItemReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Static_GetDicByProdAndBiz_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StaticGetDicByProdAndBizReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StaticServer).GetDicByProdAndBiz(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Static/GetDicByProdAndBiz",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StaticServer).GetDicByProdAndBiz(ctx, req.(*StaticGetDicByProdAndBizReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Static_GetDicByInsCmpCd_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StaticGetDicByInsCmpCdReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StaticServer).GetDicByInsCmpCd(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Static/GetDicByInsCmpCd",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StaticServer).GetDicByInsCmpCd(ctx, req.(*StaticGetDicByInsCmpCdReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Static_CheckValues_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StaticCheckValuesReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StaticServer).CheckValues(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Static/CheckValues",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StaticServer).CheckValues(ctx, req.(*StaticCheckValuesReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Static_GetDictionaryLayerItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDictionaryLayerItemReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StaticServer).GetDictionaryLayerItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Static/GetDictionaryLayerItem",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StaticServer).GetDictionaryLayerItem(ctx, req.(*GetDictionaryLayerItemReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Static_GetDictionaryItemByPk_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDictionaryItemByPkReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StaticServer).GetDictionaryItemByPk(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Static/GetDictionaryItemByPk",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StaticServer).GetDictionaryItemByPk(ctx, req.(*GetDictionaryItemByPkReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Static_GetUnionPayBankList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUnionPayBankListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StaticServer).GetUnionPayBankList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Static/GetUnionPayBankList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StaticServer).GetUnionPayBankList(ctx, req.(*GetUnionPayBankListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Static_FindUnionPayMccList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindUnionPayMccListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StaticServer).FindUnionPayMccList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Static/FindUnionPayMccList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StaticServer).FindUnionPayMccList(ctx, req.(*FindUnionPayMccListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Static_GetInsProdBizFeeMapInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInsProdBizFeeMapInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StaticServer).GetInsProdBizFeeMapInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Static/GetInsProdBizFeeMapInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StaticServer).GetInsProdBizFeeMapInfo(ctx, req.(*GetInsProdBizFeeMapInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Static_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Static",
	HandlerType: (*StaticServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SyncData",
			Handler:    _Static_SyncData_Handler,
		},
		{
			MethodName: "GetDictionaryItem",
			Handler:    _Static_GetDictionaryItem_Handler,
		},
		{
			MethodName: "GetDicByProdAndBiz",
			Handler:    _Static_GetDicByProdAndBiz_Handler,
		},
		{
			MethodName: "GetDicByInsCmpCd",
			Handler:    _Static_GetDicByInsCmpCd_Handler,
		},
		{
			MethodName: "CheckValues",
			Handler:    _Static_CheckValues_Handler,
		},
		{
			MethodName: "GetDictionaryLayerItem",
			Handler:    _Static_GetDictionaryLayerItem_Handler,
		},
		{
			MethodName: "GetDictionaryItemByPk",
			Handler:    _Static_GetDictionaryItemByPk_Handler,
		},
		{
			MethodName: "GetUnionPayBankList",
			Handler:    _Static_GetUnionPayBankList_Handler,
		},
		{
			MethodName: "FindUnionPayMccList",
			Handler:    _Static_FindUnionPayMccList_Handler,
		},
		{
			MethodName: "GetInsProdBizFeeMapInfo",
			Handler:    _Static_GetInsProdBizFeeMapInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "static.proto",
}
