// Code generated by protoc-gen-go. DO NOT EDIT.
// source: static.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type StaticSyncDataReq struct {
	TableName            string   `protobuf:"bytes,1,opt,name=TableName,proto3" json:"TableName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StaticSyncDataReq) Reset()         { *m = StaticSyncDataReq{} }
func (m *StaticSyncDataReq) String() string { return proto.CompactTextString(m) }
func (*StaticSyncDataReq) ProtoMessage()    {}
func (*StaticSyncDataReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_800d8474b3bfe66d, []int{0}
}

func (m *StaticSyncDataReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StaticSyncDataReq.Unmarshal(m, b)
}
func (m *StaticSyncDataReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StaticSyncDataReq.Marshal(b, m, deterministic)
}
func (m *StaticSyncDataReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StaticSyncDataReq.Merge(m, src)
}
func (m *StaticSyncDataReq) XXX_Size() int {
	return xxx_messageInfo_StaticSyncDataReq.Size(m)
}
func (m *StaticSyncDataReq) XXX_DiscardUnknown() {
	xxx_messageInfo_StaticSyncDataReq.DiscardUnknown(m)
}

var xxx_messageInfo_StaticSyncDataReq proto.InternalMessageInfo

func (m *StaticSyncDataReq) GetTableName() string {
	if m != nil {
		return m.TableName
	}
	return ""
}

type StaticSyncDataResp struct {
	Result               bool     `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	Err                  *Error   `protobuf:"bytes,2,opt,name=err,proto3" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StaticSyncDataResp) Reset()         { *m = StaticSyncDataResp{} }
func (m *StaticSyncDataResp) String() string { return proto.CompactTextString(m) }
func (*StaticSyncDataResp) ProtoMessage()    {}
func (*StaticSyncDataResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_800d8474b3bfe66d, []int{1}
}

func (m *StaticSyncDataResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StaticSyncDataResp.Unmarshal(m, b)
}
func (m *StaticSyncDataResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StaticSyncDataResp.Marshal(b, m, deterministic)
}
func (m *StaticSyncDataResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StaticSyncDataResp.Merge(m, src)
}
func (m *StaticSyncDataResp) XXX_Size() int {
	return xxx_messageInfo_StaticSyncDataResp.Size(m)
}
func (m *StaticSyncDataResp) XXX_DiscardUnknown() {
	xxx_messageInfo_StaticSyncDataResp.DiscardUnknown(m)
}

var xxx_messageInfo_StaticSyncDataResp proto.InternalMessageInfo

func (m *StaticSyncDataResp) GetResult() bool {
	if m != nil {
		return m.Result
	}
	return false
}

func (m *StaticSyncDataResp) GetErr() *Error {
	if m != nil {
		return m.Err
	}
	return nil
}

type StaticGetDictionaryItemReq struct {
	DicType              string   `protobuf:"bytes,1,opt,name=dicType,proto3" json:"dicType,omitempty"`
	DicCode              string   `protobuf:"bytes,2,opt,name=dicCode,proto3" json:"dicCode,omitempty"`
	DicName              string   `protobuf:"bytes,3,opt,name=dicName,proto3" json:"dicName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StaticGetDictionaryItemReq) Reset()         { *m = StaticGetDictionaryItemReq{} }
func (m *StaticGetDictionaryItemReq) String() string { return proto.CompactTextString(m) }
func (*StaticGetDictionaryItemReq) ProtoMessage()    {}
func (*StaticGetDictionaryItemReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_800d8474b3bfe66d, []int{2}
}

func (m *StaticGetDictionaryItemReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StaticGetDictionaryItemReq.Unmarshal(m, b)
}
func (m *StaticGetDictionaryItemReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StaticGetDictionaryItemReq.Marshal(b, m, deterministic)
}
func (m *StaticGetDictionaryItemReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StaticGetDictionaryItemReq.Merge(m, src)
}
func (m *StaticGetDictionaryItemReq) XXX_Size() int {
	return xxx_messageInfo_StaticGetDictionaryItemReq.Size(m)
}
func (m *StaticGetDictionaryItemReq) XXX_DiscardUnknown() {
	xxx_messageInfo_StaticGetDictionaryItemReq.DiscardUnknown(m)
}

var xxx_messageInfo_StaticGetDictionaryItemReq proto.InternalMessageInfo

func (m *StaticGetDictionaryItemReq) GetDicType() string {
	if m != nil {
		return m.DicType
	}
	return ""
}

func (m *StaticGetDictionaryItemReq) GetDicCode() string {
	if m != nil {
		return m.DicCode
	}
	return ""
}

func (m *StaticGetDictionaryItemReq) GetDicName() string {
	if m != nil {
		return m.DicName
	}
	return ""
}

type StaticGetDictionaryItemResp struct {
	Items                []*StaticGetDictionaryItem `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Err                  *Error                     `protobuf:"bytes,2,opt,name=err,proto3" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *StaticGetDictionaryItemResp) Reset()         { *m = StaticGetDictionaryItemResp{} }
func (m *StaticGetDictionaryItemResp) String() string { return proto.CompactTextString(m) }
func (*StaticGetDictionaryItemResp) ProtoMessage()    {}
func (*StaticGetDictionaryItemResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_800d8474b3bfe66d, []int{3}
}

func (m *StaticGetDictionaryItemResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StaticGetDictionaryItemResp.Unmarshal(m, b)
}
func (m *StaticGetDictionaryItemResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StaticGetDictionaryItemResp.Marshal(b, m, deterministic)
}
func (m *StaticGetDictionaryItemResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StaticGetDictionaryItemResp.Merge(m, src)
}
func (m *StaticGetDictionaryItemResp) XXX_Size() int {
	return xxx_messageInfo_StaticGetDictionaryItemResp.Size(m)
}
func (m *StaticGetDictionaryItemResp) XXX_DiscardUnknown() {
	xxx_messageInfo_StaticGetDictionaryItemResp.DiscardUnknown(m)
}

var xxx_messageInfo_StaticGetDictionaryItemResp proto.InternalMessageInfo

func (m *StaticGetDictionaryItemResp) GetItems() []*StaticGetDictionaryItem {
	if m != nil {
		return m.Items
	}
	return nil
}

func (m *StaticGetDictionaryItemResp) GetErr() *Error {
	if m != nil {
		return m.Err
	}
	return nil
}

type StaticGetDictionaryItem struct {
	DicType              string   `protobuf:"bytes,1,opt,name=dicType,proto3" json:"dicType,omitempty"`
	DicCode              string   `protobuf:"bytes,2,opt,name=dicCode,proto3" json:"dicCode,omitempty"`
	DicName              string   `protobuf:"bytes,3,opt,name=dicName,proto3" json:"dicName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StaticGetDictionaryItem) Reset()         { *m = StaticGetDictionaryItem{} }
func (m *StaticGetDictionaryItem) String() string { return proto.CompactTextString(m) }
func (*StaticGetDictionaryItem) ProtoMessage()    {}
func (*StaticGetDictionaryItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_800d8474b3bfe66d, []int{4}
}

func (m *StaticGetDictionaryItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StaticGetDictionaryItem.Unmarshal(m, b)
}
func (m *StaticGetDictionaryItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StaticGetDictionaryItem.Marshal(b, m, deterministic)
}
func (m *StaticGetDictionaryItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StaticGetDictionaryItem.Merge(m, src)
}
func (m *StaticGetDictionaryItem) XXX_Size() int {
	return xxx_messageInfo_StaticGetDictionaryItem.Size(m)
}
func (m *StaticGetDictionaryItem) XXX_DiscardUnknown() {
	xxx_messageInfo_StaticGetDictionaryItem.DiscardUnknown(m)
}

var xxx_messageInfo_StaticGetDictionaryItem proto.InternalMessageInfo

func (m *StaticGetDictionaryItem) GetDicType() string {
	if m != nil {
		return m.DicType
	}
	return ""
}

func (m *StaticGetDictionaryItem) GetDicCode() string {
	if m != nil {
		return m.DicCode
	}
	return ""
}

func (m *StaticGetDictionaryItem) GetDicName() string {
	if m != nil {
		return m.DicName
	}
	return ""
}

type StaticGetDicByProdAndBizReq struct {
	ProdCd               string   `protobuf:"bytes,1,opt,name=prodCd,proto3" json:"prodCd,omitempty"`
	BizCd                string   `protobuf:"bytes,2,opt,name=bizCd,proto3" json:"bizCd,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StaticGetDicByProdAndBizReq) Reset()         { *m = StaticGetDicByProdAndBizReq{} }
func (m *StaticGetDicByProdAndBizReq) String() string { return proto.CompactTextString(m) }
func (*StaticGetDicByProdAndBizReq) ProtoMessage()    {}
func (*StaticGetDicByProdAndBizReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_800d8474b3bfe66d, []int{5}
}

func (m *StaticGetDicByProdAndBizReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StaticGetDicByProdAndBizReq.Unmarshal(m, b)
}
func (m *StaticGetDicByProdAndBizReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StaticGetDicByProdAndBizReq.Marshal(b, m, deterministic)
}
func (m *StaticGetDicByProdAndBizReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StaticGetDicByProdAndBizReq.Merge(m, src)
}
func (m *StaticGetDicByProdAndBizReq) XXX_Size() int {
	return xxx_messageInfo_StaticGetDicByProdAndBizReq.Size(m)
}
func (m *StaticGetDicByProdAndBizReq) XXX_DiscardUnknown() {
	xxx_messageInfo_StaticGetDicByProdAndBizReq.DiscardUnknown(m)
}

var xxx_messageInfo_StaticGetDicByProdAndBizReq proto.InternalMessageInfo

func (m *StaticGetDicByProdAndBizReq) GetProdCd() string {
	if m != nil {
		return m.ProdCd
	}
	return ""
}

func (m *StaticGetDicByProdAndBizReq) GetBizCd() string {
	if m != nil {
		return m.BizCd
	}
	return ""
}

type StaticGetDicByProdAndBizResp struct {
	Items                []*StaticGetDictionaryItem `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Err                  *Error                     `protobuf:"bytes,2,opt,name=err,proto3" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *StaticGetDicByProdAndBizResp) Reset()         { *m = StaticGetDicByProdAndBizResp{} }
func (m *StaticGetDicByProdAndBizResp) String() string { return proto.CompactTextString(m) }
func (*StaticGetDicByProdAndBizResp) ProtoMessage()    {}
func (*StaticGetDicByProdAndBizResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_800d8474b3bfe66d, []int{6}
}

func (m *StaticGetDicByProdAndBizResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StaticGetDicByProdAndBizResp.Unmarshal(m, b)
}
func (m *StaticGetDicByProdAndBizResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StaticGetDicByProdAndBizResp.Marshal(b, m, deterministic)
}
func (m *StaticGetDicByProdAndBizResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StaticGetDicByProdAndBizResp.Merge(m, src)
}
func (m *StaticGetDicByProdAndBizResp) XXX_Size() int {
	return xxx_messageInfo_StaticGetDicByProdAndBizResp.Size(m)
}
func (m *StaticGetDicByProdAndBizResp) XXX_DiscardUnknown() {
	xxx_messageInfo_StaticGetDicByProdAndBizResp.DiscardUnknown(m)
}

var xxx_messageInfo_StaticGetDicByProdAndBizResp proto.InternalMessageInfo

func (m *StaticGetDicByProdAndBizResp) GetItems() []*StaticGetDictionaryItem {
	if m != nil {
		return m.Items
	}
	return nil
}

func (m *StaticGetDicByProdAndBizResp) GetErr() *Error {
	if m != nil {
		return m.Err
	}
	return nil
}

type StaticGetDicByInsCmpCdReq struct {
	InsCompanyCd         string   `protobuf:"bytes,1,opt,name=InsCompanyCd,proto3" json:"InsCompanyCd,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StaticGetDicByInsCmpCdReq) Reset()         { *m = StaticGetDicByInsCmpCdReq{} }
func (m *StaticGetDicByInsCmpCdReq) String() string { return proto.CompactTextString(m) }
func (*StaticGetDicByInsCmpCdReq) ProtoMessage()    {}
func (*StaticGetDicByInsCmpCdReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_800d8474b3bfe66d, []int{7}
}

func (m *StaticGetDicByInsCmpCdReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StaticGetDicByInsCmpCdReq.Unmarshal(m, b)
}
func (m *StaticGetDicByInsCmpCdReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StaticGetDicByInsCmpCdReq.Marshal(b, m, deterministic)
}
func (m *StaticGetDicByInsCmpCdReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StaticGetDicByInsCmpCdReq.Merge(m, src)
}
func (m *StaticGetDicByInsCmpCdReq) XXX_Size() int {
	return xxx_messageInfo_StaticGetDicByInsCmpCdReq.Size(m)
}
func (m *StaticGetDicByInsCmpCdReq) XXX_DiscardUnknown() {
	xxx_messageInfo_StaticGetDicByInsCmpCdReq.DiscardUnknown(m)
}

var xxx_messageInfo_StaticGetDicByInsCmpCdReq proto.InternalMessageInfo

func (m *StaticGetDicByInsCmpCdReq) GetInsCompanyCd() string {
	if m != nil {
		return m.InsCompanyCd
	}
	return ""
}

type StaticGetDicByInsCmpCdResp struct {
	Items                []*StaticGetDictionaryItem `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Err                  *Error                     `protobuf:"bytes,2,opt,name=err,proto3" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *StaticGetDicByInsCmpCdResp) Reset()         { *m = StaticGetDicByInsCmpCdResp{} }
func (m *StaticGetDicByInsCmpCdResp) String() string { return proto.CompactTextString(m) }
func (*StaticGetDicByInsCmpCdResp) ProtoMessage()    {}
func (*StaticGetDicByInsCmpCdResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_800d8474b3bfe66d, []int{8}
}

func (m *StaticGetDicByInsCmpCdResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StaticGetDicByInsCmpCdResp.Unmarshal(m, b)
}
func (m *StaticGetDicByInsCmpCdResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StaticGetDicByInsCmpCdResp.Marshal(b, m, deterministic)
}
func (m *StaticGetDicByInsCmpCdResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StaticGetDicByInsCmpCdResp.Merge(m, src)
}
func (m *StaticGetDicByInsCmpCdResp) XXX_Size() int {
	return xxx_messageInfo_StaticGetDicByInsCmpCdResp.Size(m)
}
func (m *StaticGetDicByInsCmpCdResp) XXX_DiscardUnknown() {
	xxx_messageInfo_StaticGetDicByInsCmpCdResp.DiscardUnknown(m)
}

var xxx_messageInfo_StaticGetDicByInsCmpCdResp proto.InternalMessageInfo

func (m *StaticGetDicByInsCmpCdResp) GetItems() []*StaticGetDictionaryItem {
	if m != nil {
		return m.Items
	}
	return nil
}

func (m *StaticGetDicByInsCmpCdResp) GetErr() *Error {
	if m != nil {
		return m.Err
	}
	return nil
}

type StaticCheckValuesReq struct {
	ProdCd               string   `protobuf:"bytes,1,opt,name=prodCd,proto3" json:"prodCd,omitempty"`
	BizCd                string   `protobuf:"bytes,2,opt,name=bizCd,proto3" json:"bizCd,omitempty"`
	TransCd              string   `protobuf:"bytes,3,opt,name=transCd,proto3" json:"transCd,omitempty"`
	InsCompanyCd         string   `protobuf:"bytes,4,opt,name=insCompanyCd,proto3" json:"insCompanyCd,omitempty"`
	FwdInsIdCd           string   `protobuf:"bytes,5,opt,name=fwdInsIdCd,proto3" json:"fwdInsIdCd,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StaticCheckValuesReq) Reset()         { *m = StaticCheckValuesReq{} }
func (m *StaticCheckValuesReq) String() string { return proto.CompactTextString(m) }
func (*StaticCheckValuesReq) ProtoMessage()    {}
func (*StaticCheckValuesReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_800d8474b3bfe66d, []int{9}
}

func (m *StaticCheckValuesReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StaticCheckValuesReq.Unmarshal(m, b)
}
func (m *StaticCheckValuesReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StaticCheckValuesReq.Marshal(b, m, deterministic)
}
func (m *StaticCheckValuesReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StaticCheckValuesReq.Merge(m, src)
}
func (m *StaticCheckValuesReq) XXX_Size() int {
	return xxx_messageInfo_StaticCheckValuesReq.Size(m)
}
func (m *StaticCheckValuesReq) XXX_DiscardUnknown() {
	xxx_messageInfo_StaticCheckValuesReq.DiscardUnknown(m)
}

var xxx_messageInfo_StaticCheckValuesReq proto.InternalMessageInfo

func (m *StaticCheckValuesReq) GetProdCd() string {
	if m != nil {
		return m.ProdCd
	}
	return ""
}

func (m *StaticCheckValuesReq) GetBizCd() string {
	if m != nil {
		return m.BizCd
	}
	return ""
}

func (m *StaticCheckValuesReq) GetTransCd() string {
	if m != nil {
		return m.TransCd
	}
	return ""
}

func (m *StaticCheckValuesReq) GetInsCompanyCd() string {
	if m != nil {
		return m.InsCompanyCd
	}
	return ""
}

func (m *StaticCheckValuesReq) GetFwdInsIdCd() string {
	if m != nil {
		return m.FwdInsIdCd
	}
	return ""
}

type StaticCheckValuesResp struct {
	Result               bool     `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	Err                  *Error   `protobuf:"bytes,2,opt,name=err,proto3" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StaticCheckValuesResp) Reset()         { *m = StaticCheckValuesResp{} }
func (m *StaticCheckValuesResp) String() string { return proto.CompactTextString(m) }
func (*StaticCheckValuesResp) ProtoMessage()    {}
func (*StaticCheckValuesResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_800d8474b3bfe66d, []int{10}
}

func (m *StaticCheckValuesResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StaticCheckValuesResp.Unmarshal(m, b)
}
func (m *StaticCheckValuesResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StaticCheckValuesResp.Marshal(b, m, deterministic)
}
func (m *StaticCheckValuesResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StaticCheckValuesResp.Merge(m, src)
}
func (m *StaticCheckValuesResp) XXX_Size() int {
	return xxx_messageInfo_StaticCheckValuesResp.Size(m)
}
func (m *StaticCheckValuesResp) XXX_DiscardUnknown() {
	xxx_messageInfo_StaticCheckValuesResp.DiscardUnknown(m)
}

var xxx_messageInfo_StaticCheckValuesResp proto.InternalMessageInfo

func (m *StaticCheckValuesResp) GetResult() bool {
	if m != nil {
		return m.Result
	}
	return false
}

func (m *StaticCheckValuesResp) GetErr() *Error {
	if m != nil {
		return m.Err
	}
	return nil
}

type GetDictionaryLayerItemReq struct {
	DicType              string   `protobuf:"bytes,1,opt,name=dicType,proto3" json:"dicType,omitempty"`
	DicCode              string   `protobuf:"bytes,2,opt,name=dicCode,proto3" json:"dicCode,omitempty"`
	DicPCode             string   `protobuf:"bytes,3,opt,name=dicPCode,proto3" json:"dicPCode,omitempty"`
	DicLevel             string   `protobuf:"bytes,4,opt,name=dicLevel,proto3" json:"dicLevel,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetDictionaryLayerItemReq) Reset()         { *m = GetDictionaryLayerItemReq{} }
func (m *GetDictionaryLayerItemReq) String() string { return proto.CompactTextString(m) }
func (*GetDictionaryLayerItemReq) ProtoMessage()    {}
func (*GetDictionaryLayerItemReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_800d8474b3bfe66d, []int{11}
}

func (m *GetDictionaryLayerItemReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDictionaryLayerItemReq.Unmarshal(m, b)
}
func (m *GetDictionaryLayerItemReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDictionaryLayerItemReq.Marshal(b, m, deterministic)
}
func (m *GetDictionaryLayerItemReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDictionaryLayerItemReq.Merge(m, src)
}
func (m *GetDictionaryLayerItemReq) XXX_Size() int {
	return xxx_messageInfo_GetDictionaryLayerItemReq.Size(m)
}
func (m *GetDictionaryLayerItemReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDictionaryLayerItemReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetDictionaryLayerItemReq proto.InternalMessageInfo

func (m *GetDictionaryLayerItemReq) GetDicType() string {
	if m != nil {
		return m.DicType
	}
	return ""
}

func (m *GetDictionaryLayerItemReq) GetDicCode() string {
	if m != nil {
		return m.DicCode
	}
	return ""
}

func (m *GetDictionaryLayerItemReq) GetDicPCode() string {
	if m != nil {
		return m.DicPCode
	}
	return ""
}

func (m *GetDictionaryLayerItemReq) GetDicLevel() string {
	if m != nil {
		return m.DicLevel
	}
	return ""
}

type DictionaryLayerItem struct {
	DicType              string   `protobuf:"bytes,1,opt,name=dicType,proto3" json:"dicType,omitempty"`
	DicCode              string   `protobuf:"bytes,2,opt,name=dicCode,proto3" json:"dicCode,omitempty"`
	DicPCode             string   `protobuf:"bytes,3,opt,name=dicPCode,proto3" json:"dicPCode,omitempty"`
	DicLevel             string   `protobuf:"bytes,4,opt,name=dicLevel,proto3" json:"dicLevel,omitempty"`
	DisPOrder            string   `protobuf:"bytes,5,opt,name=disPOrder,proto3" json:"disPOrder,omitempty"`
	Name                 string   `protobuf:"bytes,6,opt,name=name,proto3" json:"name,omitempty"`
	Memo                 string   `protobuf:"bytes,7,opt,name=memo,proto3" json:"memo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DictionaryLayerItem) Reset()         { *m = DictionaryLayerItem{} }
func (m *DictionaryLayerItem) String() string { return proto.CompactTextString(m) }
func (*DictionaryLayerItem) ProtoMessage()    {}
func (*DictionaryLayerItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_800d8474b3bfe66d, []int{12}
}

func (m *DictionaryLayerItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DictionaryLayerItem.Unmarshal(m, b)
}
func (m *DictionaryLayerItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DictionaryLayerItem.Marshal(b, m, deterministic)
}
func (m *DictionaryLayerItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DictionaryLayerItem.Merge(m, src)
}
func (m *DictionaryLayerItem) XXX_Size() int {
	return xxx_messageInfo_DictionaryLayerItem.Size(m)
}
func (m *DictionaryLayerItem) XXX_DiscardUnknown() {
	xxx_messageInfo_DictionaryLayerItem.DiscardUnknown(m)
}

var xxx_messageInfo_DictionaryLayerItem proto.InternalMessageInfo

func (m *DictionaryLayerItem) GetDicType() string {
	if m != nil {
		return m.DicType
	}
	return ""
}

func (m *DictionaryLayerItem) GetDicCode() string {
	if m != nil {
		return m.DicCode
	}
	return ""
}

func (m *DictionaryLayerItem) GetDicPCode() string {
	if m != nil {
		return m.DicPCode
	}
	return ""
}

func (m *DictionaryLayerItem) GetDicLevel() string {
	if m != nil {
		return m.DicLevel
	}
	return ""
}

func (m *DictionaryLayerItem) GetDisPOrder() string {
	if m != nil {
		return m.DisPOrder
	}
	return ""
}

func (m *DictionaryLayerItem) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *DictionaryLayerItem) GetMemo() string {
	if m != nil {
		return m.Memo
	}
	return ""
}

type GetDictionaryLayerItemResp struct {
	Items                []*DictionaryLayerItem `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Err                  *Error                 `protobuf:"bytes,2,opt,name=err,proto3" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *GetDictionaryLayerItemResp) Reset()         { *m = GetDictionaryLayerItemResp{} }
func (m *GetDictionaryLayerItemResp) String() string { return proto.CompactTextString(m) }
func (*GetDictionaryLayerItemResp) ProtoMessage()    {}
func (*GetDictionaryLayerItemResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_800d8474b3bfe66d, []int{13}
}

func (m *GetDictionaryLayerItemResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDictionaryLayerItemResp.Unmarshal(m, b)
}
func (m *GetDictionaryLayerItemResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDictionaryLayerItemResp.Marshal(b, m, deterministic)
}
func (m *GetDictionaryLayerItemResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDictionaryLayerItemResp.Merge(m, src)
}
func (m *GetDictionaryLayerItemResp) XXX_Size() int {
	return xxx_messageInfo_GetDictionaryLayerItemResp.Size(m)
}
func (m *GetDictionaryLayerItemResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDictionaryLayerItemResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetDictionaryLayerItemResp proto.InternalMessageInfo

func (m *GetDictionaryLayerItemResp) GetItems() []*DictionaryLayerItem {
	if m != nil {
		return m.Items
	}
	return nil
}

func (m *GetDictionaryLayerItemResp) GetErr() *Error {
	if m != nil {
		return m.Err
	}
	return nil
}

type GetDictionaryItemByPkReq struct {
	DicType              string   `protobuf:"bytes,1,opt,name=dicType,proto3" json:"dicType,omitempty"`
	DicCode              string   `protobuf:"bytes,2,opt,name=dicCode,proto3" json:"dicCode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetDictionaryItemByPkReq) Reset()         { *m = GetDictionaryItemByPkReq{} }
func (m *GetDictionaryItemByPkReq) String() string { return proto.CompactTextString(m) }
func (*GetDictionaryItemByPkReq) ProtoMessage()    {}
func (*GetDictionaryItemByPkReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_800d8474b3bfe66d, []int{14}
}

func (m *GetDictionaryItemByPkReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDictionaryItemByPkReq.Unmarshal(m, b)
}
func (m *GetDictionaryItemByPkReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDictionaryItemByPkReq.Marshal(b, m, deterministic)
}
func (m *GetDictionaryItemByPkReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDictionaryItemByPkReq.Merge(m, src)
}
func (m *GetDictionaryItemByPkReq) XXX_Size() int {
	return xxx_messageInfo_GetDictionaryItemByPkReq.Size(m)
}
func (m *GetDictionaryItemByPkReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDictionaryItemByPkReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetDictionaryItemByPkReq proto.InternalMessageInfo

func (m *GetDictionaryItemByPkReq) GetDicType() string {
	if m != nil {
		return m.DicType
	}
	return ""
}

func (m *GetDictionaryItemByPkReq) GetDicCode() string {
	if m != nil {
		return m.DicCode
	}
	return ""
}

type GetDictionaryItemByPkResp struct {
	Item                 *StaticGetDictionaryItem `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	Err                  *Error                   `protobuf:"bytes,2,opt,name=err,proto3" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *GetDictionaryItemByPkResp) Reset()         { *m = GetDictionaryItemByPkResp{} }
func (m *GetDictionaryItemByPkResp) String() string { return proto.CompactTextString(m) }
func (*GetDictionaryItemByPkResp) ProtoMessage()    {}
func (*GetDictionaryItemByPkResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_800d8474b3bfe66d, []int{15}
}

func (m *GetDictionaryItemByPkResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDictionaryItemByPkResp.Unmarshal(m, b)
}
func (m *GetDictionaryItemByPkResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDictionaryItemByPkResp.Marshal(b, m, deterministic)
}
func (m *GetDictionaryItemByPkResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDictionaryItemByPkResp.Merge(m, src)
}
func (m *GetDictionaryItemByPkResp) XXX_Size() int {
	return xxx_messageInfo_GetDictionaryItemByPkResp.Size(m)
}
func (m *GetDictionaryItemByPkResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDictionaryItemByPkResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetDictionaryItemByPkResp proto.InternalMessageInfo

func (m *GetDictionaryItemByPkResp) GetItem() *StaticGetDictionaryItem {
	if m != nil {
		return m.Item
	}
	return nil
}

func (m *GetDictionaryItemByPkResp) GetErr() *Error {
	if m != nil {
		return m.Err
	}
	return nil
}

func init() {
	proto.RegisterType((*StaticSyncDataReq)(nil), "pb.StaticSyncDataReq")
	proto.RegisterType((*StaticSyncDataResp)(nil), "pb.StaticSyncDataResp")
	proto.RegisterType((*StaticGetDictionaryItemReq)(nil), "pb.StaticGetDictionaryItemReq")
	proto.RegisterType((*StaticGetDictionaryItemResp)(nil), "pb.StaticGetDictionaryItemResp")
	proto.RegisterType((*StaticGetDictionaryItem)(nil), "pb.StaticGetDictionaryItem")
	proto.RegisterType((*StaticGetDicByProdAndBizReq)(nil), "pb.StaticGetDicByProdAndBizReq")
	proto.RegisterType((*StaticGetDicByProdAndBizResp)(nil), "pb.StaticGetDicByProdAndBizResp")
	proto.RegisterType((*StaticGetDicByInsCmpCdReq)(nil), "pb.StaticGetDicByInsCmpCdReq")
	proto.RegisterType((*StaticGetDicByInsCmpCdResp)(nil), "pb.StaticGetDicByInsCmpCdResp")
	proto.RegisterType((*StaticCheckValuesReq)(nil), "pb.StaticCheckValuesReq")
	proto.RegisterType((*StaticCheckValuesResp)(nil), "pb.StaticCheckValuesResp")
	proto.RegisterType((*GetDictionaryLayerItemReq)(nil), "pb.GetDictionaryLayerItemReq")
	proto.RegisterType((*DictionaryLayerItem)(nil), "pb.DictionaryLayerItem")
	proto.RegisterType((*GetDictionaryLayerItemResp)(nil), "pb.GetDictionaryLayerItemResp")
	proto.RegisterType((*GetDictionaryItemByPkReq)(nil), "pb.GetDictionaryItemByPkReq")
	proto.RegisterType((*GetDictionaryItemByPkResp)(nil), "pb.GetDictionaryItemByPkResp")
}

func init() { proto.RegisterFile("static.proto", fileDescriptor_800d8474b3bfe66d) }

var fileDescriptor_800d8474b3bfe66d = []byte{
	// 645 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x56, 0xcd, 0x6e, 0xd3, 0x40,
	0x10, 0xc6, 0x6d, 0x9a, 0xb6, 0x93, 0x1e, 0xe8, 0xd2, 0xa6, 0x8e, 0x93, 0x86, 0xc8, 0xa7, 0x5c,
	0x08, 0x6a, 0x38, 0x72, 0x40, 0xc4, 0x91, 0x50, 0x44, 0x54, 0xa2, 0xa4, 0xaa, 0xc4, 0xd1, 0xf1,
	0x2e, 0xd4, 0x34, 0xb6, 0xb7, 0xbb, 0x2e, 0xc8, 0x7d, 0x01, 0xde, 0x83, 0x87, 0x81, 0xd7, 0x42,
	0xbb, 0xeb, 0x24, 0x76, 0xfc, 0x03, 0x14, 0xca, 0x2d, 0x33, 0xdf, 0xcc, 0xb7, 0xdf, 0xcc, 0xce,
	0x8e, 0x03, 0x07, 0x3c, 0xb4, 0x43, 0xd7, 0xe9, 0x51, 0x16, 0x84, 0x01, 0xda, 0xa2, 0x73, 0xa3,
	0x46, 0x18, 0x0b, 0x98, 0x72, 0x98, 0x67, 0x70, 0x38, 0x93, 0x01, 0xb3, 0xc8, 0x77, 0x86, 0x76,
	0x68, 0x4f, 0xc9, 0x0d, 0x6a, 0xc1, 0xfe, 0x85, 0x3d, 0x5f, 0x90, 0x73, 0xdb, 0x23, 0xba, 0xd6,
	0xd1, 0xba, 0xfb, 0xd3, 0xb5, 0xc3, 0x1c, 0x01, 0xda, 0x4c, 0xe1, 0x14, 0xd5, 0xa1, 0xca, 0x08,
	0xbf, 0x5d, 0x84, 0x32, 0x61, 0x6f, 0x1a, 0x5b, 0xa8, 0x09, 0xdb, 0x84, 0x31, 0x7d, 0xab, 0xa3,
	0x75, 0x6b, 0xfd, 0xfd, 0x1e, 0x9d, 0xf7, 0xe4, 0xf1, 0x53, 0xe1, 0x35, 0x3f, 0x81, 0xa1, 0xa8,
	0xde, 0x90, 0x70, 0xe8, 0x3a, 0xa1, 0x1b, 0xf8, 0x36, 0x8b, 0x46, 0x21, 0xf1, 0x84, 0x0c, 0x1d,
	0x76, 0xb1, 0xeb, 0x5c, 0x44, 0x74, 0x29, 0x62, 0x69, 0xc6, 0x88, 0x15, 0x60, 0x22, 0x89, 0x15,
	0x22, 0xcc, 0x18, 0x91, 0xc2, 0xb7, 0x57, 0x88, 0x94, 0xed, 0x41, 0xb3, 0xf0, 0x2c, 0x4e, 0xd1,
	0x19, 0xec, 0xb8, 0x21, 0xf1, 0xb8, 0xae, 0x75, 0xb6, 0xbb, 0xb5, 0x7e, 0x53, 0x28, 0x2d, 0x8a,
	0x57, 0x91, 0xe5, 0xa5, 0x7d, 0x84, 0x93, 0x82, 0xf4, 0x7f, 0x5c, 0xd7, 0xdb, 0x74, 0x5d, 0x83,
	0x68, 0xc2, 0x02, 0xfc, 0xda, 0xc7, 0x03, 0xf7, 0x4e, 0x34, 0xb1, 0x0e, 0x55, 0xca, 0x02, 0x6c,
	0xe1, 0xf8, 0xac, 0xd8, 0x42, 0x47, 0xb0, 0x33, 0x77, 0xef, 0x2c, 0x1c, 0x1f, 0xa4, 0x0c, 0xd3,
	0x87, 0x56, 0x31, 0xd9, 0x03, 0x74, 0xe9, 0x15, 0x34, 0xd2, 0xe7, 0x8d, 0x7c, 0x6e, 0x79, 0xd4,
	0xc2, 0x42, 0xba, 0x09, 0x07, 0xc2, 0x0c, 0x3c, 0x6a, 0xfb, 0xd1, 0xaa, 0x80, 0x94, 0xcf, 0x5c,
	0xa4, 0x27, 0x28, 0x49, 0xf0, 0x00, 0x72, 0xbf, 0x69, 0x70, 0xa4, 0xf2, 0xad, 0x2b, 0xe2, 0x5c,
	0x5f, 0xda, 0x8b, 0x5b, 0xc2, 0xff, 0xb8, 0xcb, 0xe2, 0x32, 0x43, 0x66, 0xfb, 0xdc, 0xc2, 0xcb,
	0xcb, 0x8c, 0x4d, 0x51, 0xb2, 0x9b, 0x2c, 0xb9, 0xa2, 0x4a, 0x4e, 0xfa, 0x50, 0x1b, 0xe0, 0xc3,
	0x17, 0x3c, 0xf2, 0xf9, 0x48, 0x9c, 0xb7, 0x23, 0x23, 0x12, 0x1e, 0x73, 0x0c, 0xc7, 0x39, 0x1a,
	0xef, 0xfb, 0x44, 0xbf, 0x6a, 0xd0, 0x48, 0x35, 0x6b, 0x6c, 0x47, 0x84, 0xfd, 0xcd, 0x13, 0x35,
	0x60, 0x0f, 0xbb, 0xce, 0x44, 0x42, 0xaa, 0xfc, 0x95, 0x1d, 0x63, 0x63, 0xf2, 0x99, 0x2c, 0xe2,
	0xda, 0x57, 0xb6, 0xf9, 0x43, 0x83, 0x27, 0x39, 0x32, 0xfe, 0xa7, 0x06, 0xb1, 0x19, 0xb1, 0xcb,
	0x27, 0xef, 0x18, 0x26, 0x2c, 0x6e, 0xfd, 0xda, 0x81, 0x10, 0x54, 0x7c, 0xf1, 0x42, 0xab, 0x12,
	0x90, 0xbf, 0x85, 0xcf, 0x23, 0x5e, 0xa0, 0xef, 0x2a, 0x9f, 0xf8, 0x6d, 0x5e, 0x81, 0x51, 0xd4,
	0x52, 0x4e, 0xd1, 0xb3, 0xf4, 0xd0, 0x9e, 0x88, 0x0b, 0xc9, 0x8b, 0xfd, 0x9d, 0x81, 0x3d, 0x07,
	0x3d, 0x33, 0xe9, 0x83, 0x68, 0x72, 0x7d, 0xcf, 0xbb, 0x33, 0xdd, 0x8d, 0x61, 0x58, 0xf3, 0x71,
	0x8a, 0x9e, 0x43, 0x45, 0x48, 0x92, 0x6c, 0xbf, 0x78, 0x6c, 0x32, 0xb0, 0x54, 0x7a, 0xff, 0x7b,
	0x05, 0xaa, 0x2a, 0x1d, 0xbd, 0x84, 0xbd, 0xe5, 0xb7, 0x06, 0x1d, 0xaf, 0x69, 0x13, 0x9f, 0x2c,
	0xa3, 0x9e, 0xe7, 0xe6, 0xd4, 0x7c, 0x84, 0x2e, 0xe1, 0x30, 0xbb, 0x82, 0xdb, 0x65, 0xe2, 0xc8,
	0x8d, 0xf1, 0xb4, 0x14, 0x97, 0xbc, 0xef, 0x01, 0x65, 0x97, 0x24, 0xca, 0x24, 0x6e, 0xec, 0x63,
	0xa3, 0x53, 0x1e, 0x20, 0xa9, 0x67, 0xf0, 0x78, 0x73, 0x9d, 0xa1, 0xd3, 0x6c, 0x5e, 0x62, 0x57,
	0x1a, 0xed, 0x32, 0x58, 0x92, 0x0e, 0xa1, 0x96, 0x58, 0x08, 0x48, 0x5f, 0x27, 0xa4, 0x77, 0x99,
	0xd1, 0x28, 0x40, 0xe2, 0xaa, 0xeb, 0xf9, 0xa3, 0xab, 0x04, 0x16, 0x6e, 0x0a, 0x25, 0xb0, 0x78,
	0xea, 0xe5, 0x45, 0x1d, 0xe7, 0xce, 0x16, 0x6a, 0x65, 0x52, 0x13, 0x63, 0x6c, 0x9c, 0x96, 0xa0,
	0x82, 0x77, 0x5e, 0x95, 0xff, 0x74, 0x5e, 0xfc, 0x0c, 0x00, 0x00, 0xff, 0xff, 0x1c, 0x6c, 0x3e,
	0x2d, 0x0a, 0x09, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// StaticClient is the client API for Static service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type StaticClient interface {
	SyncData(ctx context.Context, in *StaticSyncDataReq, opts ...grpc.CallOption) (*StaticSyncDataResp, error)
	GetDictionaryItem(ctx context.Context, in *StaticGetDictionaryItemReq, opts ...grpc.CallOption) (*StaticGetDictionaryItemResp, error)
	GetDicByProdAndBiz(ctx context.Context, in *StaticGetDicByProdAndBizReq, opts ...grpc.CallOption) (*StaticGetDicByProdAndBizResp, error)
	GetDicByInsCmpCd(ctx context.Context, in *StaticGetDicByInsCmpCdReq, opts ...grpc.CallOption) (*StaticGetDicByInsCmpCdResp, error)
	CheckValues(ctx context.Context, in *StaticCheckValuesReq, opts ...grpc.CallOption) (*StaticCheckValuesResp, error)
	GetDictionaryLayerItem(ctx context.Context, in *GetDictionaryLayerItemReq, opts ...grpc.CallOption) (*GetDictionaryLayerItemResp, error)
	GetDictionaryItemByPk(ctx context.Context, in *GetDictionaryItemByPkReq, opts ...grpc.CallOption) (*GetDictionaryItemByPkResp, error)
}

type staticClient struct {
	cc *grpc.ClientConn
}

func NewStaticClient(cc *grpc.ClientConn) StaticClient {
	return &staticClient{cc}
}

func (c *staticClient) SyncData(ctx context.Context, in *StaticSyncDataReq, opts ...grpc.CallOption) (*StaticSyncDataResp, error) {
	out := new(StaticSyncDataResp)
	err := c.cc.Invoke(ctx, "/pb.Static/SyncData", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *staticClient) GetDictionaryItem(ctx context.Context, in *StaticGetDictionaryItemReq, opts ...grpc.CallOption) (*StaticGetDictionaryItemResp, error) {
	out := new(StaticGetDictionaryItemResp)
	err := c.cc.Invoke(ctx, "/pb.Static/GetDictionaryItem", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *staticClient) GetDicByProdAndBiz(ctx context.Context, in *StaticGetDicByProdAndBizReq, opts ...grpc.CallOption) (*StaticGetDicByProdAndBizResp, error) {
	out := new(StaticGetDicByProdAndBizResp)
	err := c.cc.Invoke(ctx, "/pb.Static/GetDicByProdAndBiz", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *staticClient) GetDicByInsCmpCd(ctx context.Context, in *StaticGetDicByInsCmpCdReq, opts ...grpc.CallOption) (*StaticGetDicByInsCmpCdResp, error) {
	out := new(StaticGetDicByInsCmpCdResp)
	err := c.cc.Invoke(ctx, "/pb.Static/GetDicByInsCmpCd", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *staticClient) CheckValues(ctx context.Context, in *StaticCheckValuesReq, opts ...grpc.CallOption) (*StaticCheckValuesResp, error) {
	out := new(StaticCheckValuesResp)
	err := c.cc.Invoke(ctx, "/pb.Static/CheckValues", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *staticClient) GetDictionaryLayerItem(ctx context.Context, in *GetDictionaryLayerItemReq, opts ...grpc.CallOption) (*GetDictionaryLayerItemResp, error) {
	out := new(GetDictionaryLayerItemResp)
	err := c.cc.Invoke(ctx, "/pb.Static/GetDictionaryLayerItem", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *staticClient) GetDictionaryItemByPk(ctx context.Context, in *GetDictionaryItemByPkReq, opts ...grpc.CallOption) (*GetDictionaryItemByPkResp, error) {
	out := new(GetDictionaryItemByPkResp)
	err := c.cc.Invoke(ctx, "/pb.Static/GetDictionaryItemByPk", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StaticServer is the server API for Static service.
type StaticServer interface {
	SyncData(context.Context, *StaticSyncDataReq) (*StaticSyncDataResp, error)
	GetDictionaryItem(context.Context, *StaticGetDictionaryItemReq) (*StaticGetDictionaryItemResp, error)
	GetDicByProdAndBiz(context.Context, *StaticGetDicByProdAndBizReq) (*StaticGetDicByProdAndBizResp, error)
	GetDicByInsCmpCd(context.Context, *StaticGetDicByInsCmpCdReq) (*StaticGetDicByInsCmpCdResp, error)
	CheckValues(context.Context, *StaticCheckValuesReq) (*StaticCheckValuesResp, error)
	GetDictionaryLayerItem(context.Context, *GetDictionaryLayerItemReq) (*GetDictionaryLayerItemResp, error)
	GetDictionaryItemByPk(context.Context, *GetDictionaryItemByPkReq) (*GetDictionaryItemByPkResp, error)
}

// UnimplementedStaticServer can be embedded to have forward compatible implementations.
type UnimplementedStaticServer struct {
}

func (*UnimplementedStaticServer) SyncData(ctx context.Context, req *StaticSyncDataReq) (*StaticSyncDataResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SyncData not implemented")
}
func (*UnimplementedStaticServer) GetDictionaryItem(ctx context.Context, req *StaticGetDictionaryItemReq) (*StaticGetDictionaryItemResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDictionaryItem not implemented")
}
func (*UnimplementedStaticServer) GetDicByProdAndBiz(ctx context.Context, req *StaticGetDicByProdAndBizReq) (*StaticGetDicByProdAndBizResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDicByProdAndBiz not implemented")
}
func (*UnimplementedStaticServer) GetDicByInsCmpCd(ctx context.Context, req *StaticGetDicByInsCmpCdReq) (*StaticGetDicByInsCmpCdResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDicByInsCmpCd not implemented")
}
func (*UnimplementedStaticServer) CheckValues(ctx context.Context, req *StaticCheckValuesReq) (*StaticCheckValuesResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckValues not implemented")
}
func (*UnimplementedStaticServer) GetDictionaryLayerItem(ctx context.Context, req *GetDictionaryLayerItemReq) (*GetDictionaryLayerItemResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDictionaryLayerItem not implemented")
}
func (*UnimplementedStaticServer) GetDictionaryItemByPk(ctx context.Context, req *GetDictionaryItemByPkReq) (*GetDictionaryItemByPkResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDictionaryItemByPk not implemented")
}

func RegisterStaticServer(s *grpc.Server, srv StaticServer) {
	s.RegisterService(&_Static_serviceDesc, srv)
}

func _Static_SyncData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StaticSyncDataReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StaticServer).SyncData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Static/SyncData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StaticServer).SyncData(ctx, req.(*StaticSyncDataReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Static_GetDictionaryItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StaticGetDictionaryItemReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StaticServer).GetDictionaryItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Static/GetDictionaryItem",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StaticServer).GetDictionaryItem(ctx, req.(*StaticGetDictionaryItemReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Static_GetDicByProdAndBiz_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StaticGetDicByProdAndBizReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StaticServer).GetDicByProdAndBiz(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Static/GetDicByProdAndBiz",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StaticServer).GetDicByProdAndBiz(ctx, req.(*StaticGetDicByProdAndBizReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Static_GetDicByInsCmpCd_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StaticGetDicByInsCmpCdReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StaticServer).GetDicByInsCmpCd(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Static/GetDicByInsCmpCd",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StaticServer).GetDicByInsCmpCd(ctx, req.(*StaticGetDicByInsCmpCdReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Static_CheckValues_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StaticCheckValuesReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StaticServer).CheckValues(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Static/CheckValues",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StaticServer).CheckValues(ctx, req.(*StaticCheckValuesReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Static_GetDictionaryLayerItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDictionaryLayerItemReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StaticServer).GetDictionaryLayerItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Static/GetDictionaryLayerItem",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StaticServer).GetDictionaryLayerItem(ctx, req.(*GetDictionaryLayerItemReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Static_GetDictionaryItemByPk_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDictionaryItemByPkReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StaticServer).GetDictionaryItemByPk(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Static/GetDictionaryItemByPk",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StaticServer).GetDictionaryItemByPk(ctx, req.(*GetDictionaryItemByPkReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _Static_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Static",
	HandlerType: (*StaticServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SyncData",
			Handler:    _Static_SyncData_Handler,
		},
		{
			MethodName: "GetDictionaryItem",
			Handler:    _Static_GetDictionaryItem_Handler,
		},
		{
			MethodName: "GetDicByProdAndBiz",
			Handler:    _Static_GetDicByProdAndBiz_Handler,
		},
		{
			MethodName: "GetDicByInsCmpCd",
			Handler:    _Static_GetDicByInsCmpCd_Handler,
		},
		{
			MethodName: "CheckValues",
			Handler:    _Static_CheckValues_Handler,
		},
		{
			MethodName: "GetDictionaryLayerItem",
			Handler:    _Static_GetDictionaryLayerItem_Handler,
		},
		{
			MethodName: "GetDictionaryItemByPk",
			Handler:    _Static_GetDictionaryItemByPk_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "static.proto",
}
