// Code generated by protoc-gen-go. DO NOT EDIT.
// source: term.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ListTermInfoRequest struct {
	Page                 int32          `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Size                 int32          `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	Term                 *TermInfoField `protobuf:"bytes,3,opt,name=term,proto3" json:"term,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ListTermInfoRequest) Reset()         { *m = ListTermInfoRequest{} }
func (m *ListTermInfoRequest) String() string { return proto.CompactTextString(m) }
func (*ListTermInfoRequest) ProtoMessage()    {}
func (*ListTermInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d8f9b522c29056d7, []int{0}
}

func (m *ListTermInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListTermInfoRequest.Unmarshal(m, b)
}
func (m *ListTermInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListTermInfoRequest.Marshal(b, m, deterministic)
}
func (m *ListTermInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListTermInfoRequest.Merge(m, src)
}
func (m *ListTermInfoRequest) XXX_Size() int {
	return xxx_messageInfo_ListTermInfoRequest.Size(m)
}
func (m *ListTermInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListTermInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListTermInfoRequest proto.InternalMessageInfo

func (m *ListTermInfoRequest) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *ListTermInfoRequest) GetSize() int32 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *ListTermInfoRequest) GetTerm() *TermInfoField {
	if m != nil {
		return m.Term
	}
	return nil
}

type ListTermInfoReply struct {
	Page                 int32            `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Size                 int32            `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	Count                int32            `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	Terms                []*TermInfoField `protobuf:"bytes,4,rep,name=terms,proto3" json:"terms,omitempty"`
	Err                  *Error           `protobuf:"bytes,5,opt,name=err,proto3" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *ListTermInfoReply) Reset()         { *m = ListTermInfoReply{} }
func (m *ListTermInfoReply) String() string { return proto.CompactTextString(m) }
func (*ListTermInfoReply) ProtoMessage()    {}
func (*ListTermInfoReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_d8f9b522c29056d7, []int{1}
}

func (m *ListTermInfoReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListTermInfoReply.Unmarshal(m, b)
}
func (m *ListTermInfoReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListTermInfoReply.Marshal(b, m, deterministic)
}
func (m *ListTermInfoReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListTermInfoReply.Merge(m, src)
}
func (m *ListTermInfoReply) XXX_Size() int {
	return xxx_messageInfo_ListTermInfoReply.Size(m)
}
func (m *ListTermInfoReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ListTermInfoReply.DiscardUnknown(m)
}

var xxx_messageInfo_ListTermInfoReply proto.InternalMessageInfo

func (m *ListTermInfoReply) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *ListTermInfoReply) GetSize() int32 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *ListTermInfoReply) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *ListTermInfoReply) GetTerms() []*TermInfoField {
	if m != nil {
		return m.Terms
	}
	return nil
}

func (m *ListTermInfoReply) GetErr() *Error {
	if m != nil {
		return m.Err
	}
	return nil
}

type TermInfoField struct {
	MchtCd               string   `protobuf:"bytes,1,opt,name=mchtCd,proto3" json:"mchtCd,omitempty"`
	TermId               string   `protobuf:"bytes,2,opt,name=termId,proto3" json:"termId,omitempty"`
	TermTp               string   `protobuf:"bytes,3,opt,name=termTp,proto3" json:"termTp,omitempty"`
	Belong               string   `protobuf:"bytes,4,opt,name=belong,proto3" json:"belong,omitempty"`
	BelongSub            string   `protobuf:"bytes,5,opt,name=belongSub,proto3" json:"belongSub,omitempty"`
	TmnlMoneyIntype      string   `protobuf:"bytes,6,opt,name=tmnlMoneyIntype,proto3" json:"tmnlMoneyIntype,omitempty"`
	TmnlMoney            float64  `protobuf:"fixed64,7,opt,name=tmnlMoney,proto3" json:"tmnlMoney,omitempty"`
	TmnlBrand            string   `protobuf:"bytes,8,opt,name=tmnlBrand,proto3" json:"tmnlBrand,omitempty"`
	TmnlModelNo          string   `protobuf:"bytes,9,opt,name=tmnlModelNo,proto3" json:"tmnlModelNo,omitempty"`
	TmnlBarcode          string   `protobuf:"bytes,10,opt,name=tmnlBarcode,proto3" json:"tmnlBarcode,omitempty"`
	DeviceCd             string   `protobuf:"bytes,11,opt,name=deviceCd,proto3" json:"deviceCd,omitempty"`
	InstallLocation      string   `protobuf:"bytes,12,opt,name=installLocation,proto3" json:"installLocation,omitempty"`
	TmnlIntype           string   `protobuf:"bytes,13,opt,name=tmnlIntype,proto3" json:"tmnlIntype,omitempty"`
	DialOut              string   `protobuf:"bytes,14,opt,name=dialOut,proto3" json:"dialOut,omitempty"`
	DealTypes            string   `protobuf:"bytes,15,opt,name=dealTypes,proto3" json:"dealTypes,omitempty"`
	RecOprId             string   `protobuf:"bytes,16,opt,name=recOprId,proto3" json:"recOprId,omitempty"`
	RecUpdOpr            string   `protobuf:"bytes,17,opt,name=recUpdOpr,proto3" json:"recUpdOpr,omitempty"`
	CreatedAt            string   `protobuf:"bytes,18,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt            string   `protobuf:"bytes,19,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	AppCd                string   `protobuf:"bytes,20,opt,name=appCd,proto3" json:"appCd,omitempty"`
	SystemFlag           string   `protobuf:"bytes,21,opt,name=systemFlag,proto3" json:"systemFlag,omitempty"`
	Status               string   `protobuf:"bytes,22,opt,name=status,proto3" json:"status,omitempty"`
	ActiveCode           string   `protobuf:"bytes,23,opt,name=activeCode,proto3" json:"activeCode,omitempty"`
	NoFlag               string   `protobuf:"bytes,24,opt,name=noFlag,proto3" json:"noFlag,omitempty"`
	MsgResvFld1          string   `protobuf:"bytes,25,opt,name=msgResvFld1,proto3" json:"msgResvFld1,omitempty"`
	MsgResvFld2          string   `protobuf:"bytes,26,opt,name=msgResvFld2,proto3" json:"msgResvFld2,omitempty"`
	MsgResvFld3          string   `protobuf:"bytes,27,opt,name=msgResvFld3,proto3" json:"msgResvFld3,omitempty"`
	MsgResvFld4          string   `protobuf:"bytes,28,opt,name=msgResvFld4,proto3" json:"msgResvFld4,omitempty"`
	MsgResvFld5          string   `protobuf:"bytes,29,opt,name=msgResvFld5,proto3" json:"msgResvFld5,omitempty"`
	MsgResvFld6          string   `protobuf:"bytes,30,opt,name=msgResvFld6,proto3" json:"msgResvFld6,omitempty"`
	MsgResvFld7          string   `protobuf:"bytes,31,opt,name=msgResvFld7,proto3" json:"msgResvFld7,omitempty"`
	MsgResvFld8          string   `protobuf:"bytes,32,opt,name=msgResvFld8,proto3" json:"msgResvFld8,omitempty"`
	MsgResvFld9          string   `protobuf:"bytes,33,opt,name=msgResvFld9,proto3" json:"msgResvFld9,omitempty"`
	MsgResvFld10         string   `protobuf:"bytes,34,opt,name=msgResvFld10,proto3" json:"msgResvFld10,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TermInfoField) Reset()         { *m = TermInfoField{} }
func (m *TermInfoField) String() string { return proto.CompactTextString(m) }
func (*TermInfoField) ProtoMessage()    {}
func (*TermInfoField) Descriptor() ([]byte, []int) {
	return fileDescriptor_d8f9b522c29056d7, []int{2}
}

func (m *TermInfoField) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TermInfoField.Unmarshal(m, b)
}
func (m *TermInfoField) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TermInfoField.Marshal(b, m, deterministic)
}
func (m *TermInfoField) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TermInfoField.Merge(m, src)
}
func (m *TermInfoField) XXX_Size() int {
	return xxx_messageInfo_TermInfoField.Size(m)
}
func (m *TermInfoField) XXX_DiscardUnknown() {
	xxx_messageInfo_TermInfoField.DiscardUnknown(m)
}

var xxx_messageInfo_TermInfoField proto.InternalMessageInfo

func (m *TermInfoField) GetMchtCd() string {
	if m != nil {
		return m.MchtCd
	}
	return ""
}

func (m *TermInfoField) GetTermId() string {
	if m != nil {
		return m.TermId
	}
	return ""
}

func (m *TermInfoField) GetTermTp() string {
	if m != nil {
		return m.TermTp
	}
	return ""
}

func (m *TermInfoField) GetBelong() string {
	if m != nil {
		return m.Belong
	}
	return ""
}

func (m *TermInfoField) GetBelongSub() string {
	if m != nil {
		return m.BelongSub
	}
	return ""
}

func (m *TermInfoField) GetTmnlMoneyIntype() string {
	if m != nil {
		return m.TmnlMoneyIntype
	}
	return ""
}

func (m *TermInfoField) GetTmnlMoney() float64 {
	if m != nil {
		return m.TmnlMoney
	}
	return 0
}

func (m *TermInfoField) GetTmnlBrand() string {
	if m != nil {
		return m.TmnlBrand
	}
	return ""
}

func (m *TermInfoField) GetTmnlModelNo() string {
	if m != nil {
		return m.TmnlModelNo
	}
	return ""
}

func (m *TermInfoField) GetTmnlBarcode() string {
	if m != nil {
		return m.TmnlBarcode
	}
	return ""
}

func (m *TermInfoField) GetDeviceCd() string {
	if m != nil {
		return m.DeviceCd
	}
	return ""
}

func (m *TermInfoField) GetInstallLocation() string {
	if m != nil {
		return m.InstallLocation
	}
	return ""
}

func (m *TermInfoField) GetTmnlIntype() string {
	if m != nil {
		return m.TmnlIntype
	}
	return ""
}

func (m *TermInfoField) GetDialOut() string {
	if m != nil {
		return m.DialOut
	}
	return ""
}

func (m *TermInfoField) GetDealTypes() string {
	if m != nil {
		return m.DealTypes
	}
	return ""
}

func (m *TermInfoField) GetRecOprId() string {
	if m != nil {
		return m.RecOprId
	}
	return ""
}

func (m *TermInfoField) GetRecUpdOpr() string {
	if m != nil {
		return m.RecUpdOpr
	}
	return ""
}

func (m *TermInfoField) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *TermInfoField) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

func (m *TermInfoField) GetAppCd() string {
	if m != nil {
		return m.AppCd
	}
	return ""
}

func (m *TermInfoField) GetSystemFlag() string {
	if m != nil {
		return m.SystemFlag
	}
	return ""
}

func (m *TermInfoField) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *TermInfoField) GetActiveCode() string {
	if m != nil {
		return m.ActiveCode
	}
	return ""
}

func (m *TermInfoField) GetNoFlag() string {
	if m != nil {
		return m.NoFlag
	}
	return ""
}

func (m *TermInfoField) GetMsgResvFld1() string {
	if m != nil {
		return m.MsgResvFld1
	}
	return ""
}

func (m *TermInfoField) GetMsgResvFld2() string {
	if m != nil {
		return m.MsgResvFld2
	}
	return ""
}

func (m *TermInfoField) GetMsgResvFld3() string {
	if m != nil {
		return m.MsgResvFld3
	}
	return ""
}

func (m *TermInfoField) GetMsgResvFld4() string {
	if m != nil {
		return m.MsgResvFld4
	}
	return ""
}

func (m *TermInfoField) GetMsgResvFld5() string {
	if m != nil {
		return m.MsgResvFld5
	}
	return ""
}

func (m *TermInfoField) GetMsgResvFld6() string {
	if m != nil {
		return m.MsgResvFld6
	}
	return ""
}

func (m *TermInfoField) GetMsgResvFld7() string {
	if m != nil {
		return m.MsgResvFld7
	}
	return ""
}

func (m *TermInfoField) GetMsgResvFld8() string {
	if m != nil {
		return m.MsgResvFld8
	}
	return ""
}

func (m *TermInfoField) GetMsgResvFld9() string {
	if m != nil {
		return m.MsgResvFld9
	}
	return ""
}

func (m *TermInfoField) GetMsgResvFld10() string {
	if m != nil {
		return m.MsgResvFld10
	}
	return ""
}

func init() {
	proto.RegisterType((*ListTermInfoRequest)(nil), "pb.ListTermInfoRequest")
	proto.RegisterType((*ListTermInfoReply)(nil), "pb.ListTermInfoReply")
	proto.RegisterType((*TermInfoField)(nil), "pb.TermInfoField")
}

func init() { proto.RegisterFile("term.proto", fileDescriptor_d8f9b522c29056d7) }

var fileDescriptor_d8f9b522c29056d7 = []byte{
	// 623 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x94, 0xdd, 0x6e, 0x13, 0x3d,
	0x10, 0x86, 0xbf, 0xb4, 0x49, 0xdb, 0x38, 0xed, 0x57, 0xea, 0xfe, 0x0d, 0x69, 0x29, 0x21, 0x12,
	0x22, 0x47, 0x15, 0xa4, 0xff, 0x67, 0xd0, 0x48, 0x15, 0x91, 0x0a, 0x95, 0x96, 0x70, 0x01, 0x9b,
	0xf5, 0x10, 0x56, 0x72, 0xd6, 0xc6, 0x76, 0x2a, 0x85, 0x1b, 0xe1, 0x12, 0xb8, 0x4d, 0x34, 0x76,
	0xb2, 0xc9, 0x2e, 0x3d, 0xe0, 0x6c, 0xe7, 0x79, 0xdf, 0x19, 0xcf, 0xac, 0xad, 0x61, 0xcc, 0xa1,
	0x19, 0x9f, 0x6a, 0xa3, 0x9c, 0xe2, 0x2b, 0x7a, 0xd8, 0x6c, 0xa0, 0x31, 0xca, 0x04, 0xd0, 0x16,
	0x6c, 0xf7, 0x3e, 0xb5, 0x6e, 0x80, 0x66, 0xdc, 0xcf, 0xbe, 0xa9, 0x08, 0x7f, 0x4c, 0xd0, 0x3a,
	0xce, 0x59, 0x55, 0xc7, 0x23, 0x84, 0x4a, 0xab, 0xd2, 0xa9, 0x45, 0xfe, 0x9b, 0x98, 0x4d, 0x7f,
	0x22, 0xac, 0x04, 0x46, 0xdf, 0xfc, 0x35, 0xab, 0x52, 0x75, 0x58, 0x6d, 0x55, 0x3a, 0x8d, 0xee,
	0xce, 0xa9, 0x1e, 0x9e, 0xce, 0x4b, 0xdd, 0xa5, 0x28, 0x45, 0xe4, 0xe5, 0xf6, 0xaf, 0x0a, 0xdb,
	0x29, 0x1e, 0xa3, 0xe5, 0xf4, 0x9f, 0x0f, 0xd9, 0x63, 0xb5, 0x44, 0x4d, 0x32, 0xe7, 0x4f, 0xa9,
	0x45, 0x21, 0xe0, 0x6f, 0x58, 0x8d, 0x6a, 0x5b, 0xa8, 0xb6, 0x56, 0x9f, 0x3e, 0x3b, 0xe8, 0xfc,
	0x88, 0xad, 0xa2, 0x31, 0x50, 0xf3, 0x2d, 0xd6, 0xc9, 0xe6, 0x7f, 0x40, 0x44, 0xb4, 0xfd, 0x7b,
	0x83, 0x6d, 0x15, 0xb2, 0xf8, 0x01, 0x5b, 0x1b, 0x27, 0xdf, 0x5d, 0x4f, 0xf8, 0xbe, 0xea, 0xd1,
	0x2c, 0x22, 0x4e, 0xf5, 0xfa, 0xc2, 0xf7, 0x56, 0x8f, 0x66, 0xd1, 0x9c, 0x0f, 0xb4, 0x6f, 0x6f,
	0xc6, 0x07, 0x9a, 0xf8, 0x10, 0xa5, 0xca, 0x46, 0x50, 0x0d, 0x3c, 0x44, 0xfc, 0x98, 0xd5, 0xc3,
	0xd7, 0x97, 0xc9, 0xd0, 0x37, 0x55, 0x8f, 0x16, 0x80, 0x77, 0xd8, 0xb6, 0x1b, 0x67, 0xf2, 0x93,
	0xca, 0x70, 0xda, 0xcf, 0xdc, 0x54, 0x23, 0xac, 0x79, 0x4f, 0x19, 0x53, 0x9d, 0x1c, 0xc1, 0x7a,
	0xab, 0xd2, 0xa9, 0x44, 0x0b, 0x30, 0x57, 0x6f, 0x4d, 0x9c, 0x09, 0xd8, 0x08, 0xa7, 0xe4, 0x80,
	0xb7, 0x58, 0x23, 0x58, 0x05, 0xca, 0xcf, 0x0a, 0xea, 0x5e, 0x5f, 0x46, 0x73, 0xc7, 0x6d, 0x6c,
	0x12, 0x25, 0x10, 0xd8, 0xc2, 0x31, 0x43, 0xbc, 0xc9, 0x36, 0x04, 0x3e, 0xa6, 0x09, 0xf6, 0x04,
	0x34, 0xbc, 0x9c, 0xc7, 0x34, 0x45, 0x9a, 0x59, 0x17, 0x4b, 0x79, 0xaf, 0x92, 0xd8, 0xa5, 0x2a,
	0x83, 0xcd, 0x30, 0x45, 0x09, 0xf3, 0x13, 0xc6, 0xa8, 0xe8, 0x6c, 0xd4, 0x2d, 0x6f, 0x5a, 0x22,
	0x1c, 0xd8, 0xba, 0x48, 0x63, 0xf9, 0x30, 0x71, 0xf0, 0xbf, 0x17, 0xe7, 0x21, 0x4d, 0x28, 0x30,
	0x96, 0x83, 0xa9, 0x46, 0x0b, 0xdb, 0x61, 0xc2, 0x1c, 0x50, 0x77, 0x06, 0x93, 0x07, 0x6d, 0xfa,
	0x02, 0x9e, 0x85, 0xee, 0xe6, 0x31, 0x65, 0x1a, 0x4c, 0xbe, 0x6a, 0xf1, 0xa0, 0x0d, 0xec, 0x84,
	0xcc, 0x1c, 0x90, 0x9a, 0x18, 0x8c, 0x1d, 0x8a, 0x0f, 0x0e, 0x78, 0x50, 0x73, 0x40, 0xea, 0x44,
	0x8b, 0x99, 0xba, 0x1b, 0xd4, 0x1c, 0xd0, 0x4b, 0x8d, 0xb5, 0xee, 0x09, 0xd8, 0xf3, 0x4a, 0x08,
	0x68, 0x46, 0x3b, 0xb5, 0x0e, 0xc7, 0x77, 0x32, 0x1e, 0xc1, 0x7e, 0x98, 0x71, 0x41, 0xe8, 0xa5,
	0x58, 0x17, 0xbb, 0x89, 0x85, 0x83, 0xf0, 0x52, 0x42, 0x44, 0x79, 0x71, 0xe2, 0xd2, 0x47, 0xec,
	0xd1, 0x15, 0x1c, 0x86, 0xbc, 0x05, 0xa1, 0xbc, 0x4c, 0xf9, 0x9a, 0x10, 0xf2, 0x42, 0x44, 0x77,
	0x37, 0xb6, 0xa3, 0x08, 0xed, 0xe3, 0x9d, 0x14, 0xef, 0xe0, 0x79, 0xb8, 0xbb, 0x25, 0x54, 0x74,
	0x74, 0xa1, 0x59, 0x76, 0x74, 0x8b, 0x8e, 0x33, 0x38, 0x2a, 0x3b, 0xce, 0x8a, 0x8e, 0x73, 0x38,
	0x2e, 0x3b, 0xce, 0x8b, 0x8e, 0x0b, 0x78, 0x51, 0x76, 0x5c, 0x14, 0x1d, 0x97, 0x70, 0x52, 0x76,
	0x5c, 0x16, 0x1d, 0x57, 0xf0, 0xb2, 0xec, 0xb8, 0x2a, 0x3a, 0xae, 0xa1, 0x55, 0x76, 0x5c, 0x17,
	0x1d, 0x37, 0xf0, 0xaa, 0xec, 0xb8, 0xe1, 0x6d, 0xb6, 0xb9, 0xf4, 0x7b, 0xde, 0x42, 0xdb, 0x5b,
	0x0a, 0xac, 0xfb, 0x91, 0x55, 0x69, 0x51, 0xf0, 0xf7, 0x6c, 0x73, 0x79, 0x95, 0xf1, 0x43, 0xda,
	0x28, 0x4f, 0xec, 0xd0, 0xe6, 0xfe, 0xdf, 0x82, 0x96, 0xd3, 0xf6, 0x7f, 0xc3, 0x35, 0xbf, 0x7a,
	0xcf, 0xfe, 0x04, 0x00, 0x00, 0xff, 0xff, 0x13, 0xa8, 0xe6, 0x24, 0x99, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TermClient is the client API for Term service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TermClient interface {
	ListTermInfo(ctx context.Context, in *ListTermInfoRequest, opts ...grpc.CallOption) (*ListTermInfoReply, error)
}

type termClient struct {
	cc *grpc.ClientConn
}

func NewTermClient(cc *grpc.ClientConn) TermClient {
	return &termClient{cc}
}

func (c *termClient) ListTermInfo(ctx context.Context, in *ListTermInfoRequest, opts ...grpc.CallOption) (*ListTermInfoReply, error) {
	out := new(ListTermInfoReply)
	err := c.cc.Invoke(ctx, "/pb.Term/ListTermInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TermServer is the server API for Term service.
type TermServer interface {
	ListTermInfo(context.Context, *ListTermInfoRequest) (*ListTermInfoReply, error)
}

// UnimplementedTermServer can be embedded to have forward compatible implementations.
type UnimplementedTermServer struct {
}

func (*UnimplementedTermServer) ListTermInfo(ctx context.Context, req *ListTermInfoRequest) (*ListTermInfoReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListTermInfo not implemented")
}

func RegisterTermServer(s *grpc.Server, srv TermServer) {
	s.RegisterService(&_Term_serviceDesc, srv)
}

func _Term_ListTermInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTermInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TermServer).ListTermInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Term/ListTermInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TermServer).ListTermInfo(ctx, req.(*ListTermInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Term_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Term",
	HandlerType: (*TermServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListTermInfo",
			Handler:    _Term_ListTermInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "term.proto",
}
