// Code generated by protoc-gen-go. DO NOT EDIT.
// source: workflow.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type StartWorkflowRequest struct {
	Type                 string   `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	UserId               string   `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StartWorkflowRequest) Reset()         { *m = StartWorkflowRequest{} }
func (m *StartWorkflowRequest) String() string { return proto.CompactTextString(m) }
func (*StartWorkflowRequest) ProtoMessage()    {}
func (*StartWorkflowRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_892c7f566756b0be, []int{0}
}

func (m *StartWorkflowRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StartWorkflowRequest.Unmarshal(m, b)
}
func (m *StartWorkflowRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StartWorkflowRequest.Marshal(b, m, deterministic)
}
func (m *StartWorkflowRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StartWorkflowRequest.Merge(m, src)
}
func (m *StartWorkflowRequest) XXX_Size() int {
	return xxx_messageInfo_StartWorkflowRequest.Size(m)
}
func (m *StartWorkflowRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StartWorkflowRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StartWorkflowRequest proto.InternalMessageInfo

func (m *StartWorkflowRequest) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *StartWorkflowRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *StartWorkflowRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type StartWorkflowReply struct {
	Err                  *Error   `protobuf:"bytes,1,opt,name=err,proto3" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StartWorkflowReply) Reset()         { *m = StartWorkflowReply{} }
func (m *StartWorkflowReply) String() string { return proto.CompactTextString(m) }
func (*StartWorkflowReply) ProtoMessage()    {}
func (*StartWorkflowReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_892c7f566756b0be, []int{1}
}

func (m *StartWorkflowReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StartWorkflowReply.Unmarshal(m, b)
}
func (m *StartWorkflowReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StartWorkflowReply.Marshal(b, m, deterministic)
}
func (m *StartWorkflowReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StartWorkflowReply.Merge(m, src)
}
func (m *StartWorkflowReply) XXX_Size() int {
	return xxx_messageInfo_StartWorkflowReply.Size(m)
}
func (m *StartWorkflowReply) XXX_DiscardUnknown() {
	xxx_messageInfo_StartWorkflowReply.DiscardUnknown(m)
}

var xxx_messageInfo_StartWorkflowReply proto.InternalMessageInfo

func (m *StartWorkflowReply) GetErr() *Error {
	if m != nil {
		return m.Err
	}
	return nil
}

type ListTaskRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListTaskRequest) Reset()         { *m = ListTaskRequest{} }
func (m *ListTaskRequest) String() string { return proto.CompactTextString(m) }
func (*ListTaskRequest) ProtoMessage()    {}
func (*ListTaskRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_892c7f566756b0be, []int{2}
}

func (m *ListTaskRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListTaskRequest.Unmarshal(m, b)
}
func (m *ListTaskRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListTaskRequest.Marshal(b, m, deterministic)
}
func (m *ListTaskRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListTaskRequest.Merge(m, src)
}
func (m *ListTaskRequest) XXX_Size() int {
	return xxx_messageInfo_ListTaskRequest.Size(m)
}
func (m *ListTaskRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListTaskRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListTaskRequest proto.InternalMessageInfo

type ListTaskReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListTaskReply) Reset()         { *m = ListTaskReply{} }
func (m *ListTaskReply) String() string { return proto.CompactTextString(m) }
func (*ListTaskReply) ProtoMessage()    {}
func (*ListTaskReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_892c7f566756b0be, []int{3}
}

func (m *ListTaskReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListTaskReply.Unmarshal(m, b)
}
func (m *ListTaskReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListTaskReply.Marshal(b, m, deterministic)
}
func (m *ListTaskReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListTaskReply.Merge(m, src)
}
func (m *ListTaskReply) XXX_Size() int {
	return xxx_messageInfo_ListTaskReply.Size(m)
}
func (m *ListTaskReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ListTaskReply.DiscardUnknown(m)
}

var xxx_messageInfo_ListTaskReply proto.InternalMessageInfo

type HandleTaskRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HandleTaskRequest) Reset()         { *m = HandleTaskRequest{} }
func (m *HandleTaskRequest) String() string { return proto.CompactTextString(m) }
func (*HandleTaskRequest) ProtoMessage()    {}
func (*HandleTaskRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_892c7f566756b0be, []int{4}
}

func (m *HandleTaskRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HandleTaskRequest.Unmarshal(m, b)
}
func (m *HandleTaskRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HandleTaskRequest.Marshal(b, m, deterministic)
}
func (m *HandleTaskRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HandleTaskRequest.Merge(m, src)
}
func (m *HandleTaskRequest) XXX_Size() int {
	return xxx_messageInfo_HandleTaskRequest.Size(m)
}
func (m *HandleTaskRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HandleTaskRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HandleTaskRequest proto.InternalMessageInfo

type HandleTaskReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HandleTaskReply) Reset()         { *m = HandleTaskReply{} }
func (m *HandleTaskReply) String() string { return proto.CompactTextString(m) }
func (*HandleTaskReply) ProtoMessage()    {}
func (*HandleTaskReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_892c7f566756b0be, []int{5}
}

func (m *HandleTaskReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HandleTaskReply.Unmarshal(m, b)
}
func (m *HandleTaskReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HandleTaskReply.Marshal(b, m, deterministic)
}
func (m *HandleTaskReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HandleTaskReply.Merge(m, src)
}
func (m *HandleTaskReply) XXX_Size() int {
	return xxx_messageInfo_HandleTaskReply.Size(m)
}
func (m *HandleTaskReply) XXX_DiscardUnknown() {
	xxx_messageInfo_HandleTaskReply.DiscardUnknown(m)
}

var xxx_messageInfo_HandleTaskReply proto.InternalMessageInfo

func init() {
	proto.RegisterType((*StartWorkflowRequest)(nil), "pb.StartWorkflowRequest")
	proto.RegisterType((*StartWorkflowReply)(nil), "pb.StartWorkflowReply")
	proto.RegisterType((*ListTaskRequest)(nil), "pb.ListTaskRequest")
	proto.RegisterType((*ListTaskReply)(nil), "pb.ListTaskReply")
	proto.RegisterType((*HandleTaskRequest)(nil), "pb.HandleTaskRequest")
	proto.RegisterType((*HandleTaskReply)(nil), "pb.HandleTaskReply")
}

func init() { proto.RegisterFile("workflow.proto", fileDescriptor_892c7f566756b0be) }

var fileDescriptor_892c7f566756b0be = []byte{
	// 258 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0xcf, 0x4a, 0xc3, 0x40,
	0x10, 0x87, 0x4d, 0xab, 0xb5, 0x9d, 0xa2, 0x21, 0x13, 0xff, 0x84, 0x78, 0x91, 0x3d, 0x79, 0x0a,
	0x58, 0x3d, 0xe9, 0x0b, 0x28, 0x78, 0x8a, 0x42, 0x8f, 0x92, 0x90, 0x11, 0x4a, 0xd7, 0xee, 0x3a,
	0xd9, 0x52, 0xf2, 0x68, 0xbe, 0x9d, 0xcc, 0xa6, 0xa5, 0x35, 0xed, 0x6d, 0xf6, 0xdb, 0xdf, 0xcc,
	0x7c, 0xcb, 0xc2, 0xf9, 0xca, 0xf0, 0xfc, 0x4b, 0x9b, 0x55, 0x66, 0xd9, 0x38, 0x83, 0x3d, 0x5b,
	0xa6, 0x63, 0x62, 0x36, 0xdc, 0x02, 0x35, 0x85, 0x8b, 0x77, 0x57, 0xb0, 0x9b, 0xae, 0x73, 0x39,
	0xfd, 0x2c, 0xa9, 0x76, 0x88, 0x70, 0xec, 0x1a, 0x4b, 0x49, 0x70, 0x1b, 0xdc, 0x8d, 0x72, 0x5f,
	0x0b, 0x5b, 0x14, 0xdf, 0x94, 0xf4, 0x5a, 0x26, 0x35, 0x5e, 0xc3, 0xe9, 0xb2, 0x26, 0xfe, 0x9c,
	0x55, 0x49, 0xdf, 0xe3, 0x81, 0x1c, 0x5f, 0x2b, 0x75, 0x0f, 0xd8, 0x19, 0x6c, 0x75, 0x83, 0x37,
	0xd0, 0x27, 0x66, 0x3f, 0x75, 0x3c, 0x19, 0x65, 0xb6, 0xcc, 0xbc, 0x4c, 0x2e, 0x54, 0x45, 0x10,
	0xbe, 0xcd, 0x6a, 0xf7, 0x51, 0xd4, 0xf3, 0xb5, 0x86, 0x0a, 0xe1, 0x6c, 0x8b, 0xac, 0x6e, 0x54,
	0x0c, 0xd1, 0x4b, 0xb1, 0xa8, 0x34, 0xed, 0xa6, 0x22, 0x08, 0x77, 0xa1, 0xd5, 0xcd, 0xe4, 0x37,
	0x80, 0xe1, 0x66, 0x35, 0x3e, 0xc3, 0x89, 0x77, 0xc1, 0x44, 0x36, 0x1e, 0x7a, 0x6f, 0x7a, 0x75,
	0xe0, 0x46, 0xf6, 0x1d, 0xe1, 0x23, 0x0c, 0x37, 0x0a, 0x18, 0x4b, 0xaa, 0xe3, 0x98, 0x46, 0xff,
	0x61, 0xdb, 0xf5, 0x04, 0xb0, 0x55, 0xc2, 0x4b, 0x89, 0xec, 0x79, 0xa7, 0x71, 0x17, 0xfb, 0xde,
	0x72, 0xe0, 0xbf, 0xe6, 0xe1, 0x2f, 0x00, 0x00, 0xff, 0xff, 0xe0, 0x4d, 0xfe, 0x6f, 0xbd, 0x01,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// WorkflowClient is the client API for Workflow service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type WorkflowClient interface {
	Start(ctx context.Context, in *StartWorkflowRequest, opts ...grpc.CallOption) (*StartWorkflowReply, error)
	ListTask(ctx context.Context, in *ListTaskRequest, opts ...grpc.CallOption) (*ListTaskReply, error)
	HandleTask(ctx context.Context, in *HandleTaskRequest, opts ...grpc.CallOption) (*HandleTaskReply, error)
}

type workflowClient struct {
	cc *grpc.ClientConn
}

func NewWorkflowClient(cc *grpc.ClientConn) WorkflowClient {
	return &workflowClient{cc}
}

func (c *workflowClient) Start(ctx context.Context, in *StartWorkflowRequest, opts ...grpc.CallOption) (*StartWorkflowReply, error) {
	out := new(StartWorkflowReply)
	err := c.cc.Invoke(ctx, "/pb.Workflow/Start", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowClient) ListTask(ctx context.Context, in *ListTaskRequest, opts ...grpc.CallOption) (*ListTaskReply, error) {
	out := new(ListTaskReply)
	err := c.cc.Invoke(ctx, "/pb.Workflow/ListTask", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowClient) HandleTask(ctx context.Context, in *HandleTaskRequest, opts ...grpc.CallOption) (*HandleTaskReply, error) {
	out := new(HandleTaskReply)
	err := c.cc.Invoke(ctx, "/pb.Workflow/HandleTask", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WorkflowServer is the server API for Workflow service.
type WorkflowServer interface {
	Start(context.Context, *StartWorkflowRequest) (*StartWorkflowReply, error)
	ListTask(context.Context, *ListTaskRequest) (*ListTaskReply, error)
	HandleTask(context.Context, *HandleTaskRequest) (*HandleTaskReply, error)
}

// UnimplementedWorkflowServer can be embedded to have forward compatible implementations.
type UnimplementedWorkflowServer struct {
}

func (*UnimplementedWorkflowServer) Start(ctx context.Context, req *StartWorkflowRequest) (*StartWorkflowReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Start not implemented")
}
func (*UnimplementedWorkflowServer) ListTask(ctx context.Context, req *ListTaskRequest) (*ListTaskReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListTask not implemented")
}
func (*UnimplementedWorkflowServer) HandleTask(ctx context.Context, req *HandleTaskRequest) (*HandleTaskReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HandleTask not implemented")
}

func RegisterWorkflowServer(s *grpc.Server, srv WorkflowServer) {
	s.RegisterService(&_Workflow_serviceDesc, srv)
}

func _Workflow_Start_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartWorkflowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowServer).Start(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Workflow/Start",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowServer).Start(ctx, req.(*StartWorkflowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Workflow_ListTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowServer).ListTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Workflow/ListTask",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowServer).ListTask(ctx, req.(*ListTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Workflow_HandleTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HandleTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowServer).HandleTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Workflow/HandleTask",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowServer).HandleTask(ctx, req.(*HandleTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Workflow_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Workflow",
	HandlerType: (*WorkflowServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Start",
			Handler:    _Workflow_Start_Handler,
		},
		{
			MethodName: "ListTask",
			Handler:    _Workflow_ListTask_Handler,
		},
		{
			MethodName: "HandleTask",
			Handler:    _Workflow_HandleTask_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "workflow.proto",
}
